### ISSUE TITLE
Fail to build with --disable-emoji-dict

### ISSUE THREAD

**Issue by zhmars** [ibus/ibus#2336] opened 2021-08-21 09:40 UTC
Issue description:

When building with `--disable-emoji-dict`, I got following error:

```
 $ ./autogen.sh --prefix='/usr' --sysconfdir='/etc' --libdir='/usr/lib' --disable-emoji-dict
 $ make

...
  CC       ibusxevent.lo
  CC       ibusxml.lo
  CCLD     libibus-1.0.la
  CCLD     unicode-parser
  GISCAN   IBus-1.0.gir
ibusemoji.c:107: Warning: IBus: unexpected annotation: element-type
  GICOMP   IBus-1.0.gir
Generated dicts/unicode-names.dict
Generated dicts/unicode-blocks.dict
make[4]: *** No rule to make target 'ibusemojigen.h', needed by 'all-am'.  Stop.
make[4]: Leaving directory '/tmp/pkg/ibus/ibus-1.5.25/src'
make[3]: *** [Makefile:1155: all-recursive] Error 1
make[3]: Leaving directory '/tmp/pkg/ibus/ibus-1.5.25/src'
make[2]: *** [Makefile:845: all] Error 2
make[2]: Leaving directory '/tmp/pkg/ibus/ibus-1.5.25/src'
make[1]: *** [Makefile:689: all-recursive] Error 1
make[1]: Leaving directory '/tmp/pkg/ibus/ibus-1.5.25'
make: *** [Makefile:596: all] Error 2
```

**Comment by fujiwarat** [comment] 2021-09-25 01:02
Duplicate of #2335

**Closed by fujiwarat** 2021-09-25 01:02 UTC
