### ISSUE TITLE
Unable to switch language

### ISSUE THREAD

**Issue by inabahare** [ibus/ibus#2528] opened 2023-06-17 08:25 UTC
**Which distribution and version?:** 
Arch Linux

**Which desktop environment and version?:** 
KDE (plasma 5.27.5-1)

**Which session type?:** 
Wayland

**IBus version?:** 
IBus 1.5.28

**Issue description:**
I can't switch languages. The little icon in the tray is empty when I click or right click
![image](https://github.com/ibus/ibus/assets/6093917/69f241ac-1705-46dd-be57-a21af3ef39df)
![image](https://github.com/ibus/ibus/assets/6093917/ffea003d-8258-4622-8358-f03a5da50184)

That is with just just Danish and English as inputs 

![image](https://github.com/ibus/ibus/assets/6093917/edc7ff13-5b10-4e26-8513-af36d6dfb22e)

And if I add Japanese with Anthy I get Japanese and "Other - No input method"

![image](https://github.com/ibus/ibus/assets/6093917/1846f579-3b94-4ff0-89f9-50bea65e75dd)

**Steps to reproduce:**
I did as the Arch wiki commanded: https://wiki.archlinux.org/title/IBus

**Can you reproduce your problem when you restart ibus-daemon? (yes / no):** 
Yes

**Do you see any errors when you run ibus-daemon with the verbose option?:**
I don't see any errors. This is what I get

```
inaba@japan ~ $ ibus-daemon --xim --verbose

(ibus-ui-gtk3:10515): IBUS-WARNING **: 10:16:21.194: indicator.vala:268: The query window is root window

(ibus-ui-gtk3:10515): Gtk-WARNING **: 10:16:21.195: no trigger event for menu popup

(ibus-ui-gtk3:10515): Gtk-WARNING **: 10:16:40.345: no trigger event for menu popup

(ibus-ui-gtk3:10515): Gtk-WARNING **: 10:17:05.253: no trigger event for menu popup

(ibus-ui-gtk3:10515): Gtk-WARNING **: 10:17:46.037: no trigger event for menu popup

(ibus-ui-gtk3:10515): Gtk-WARNING **: 10:18:11.260: no trigger event for menu popup
```

**Can you reproduce your problem with a new user account instead of the current your account? (yes / no):** 
Yes

**Comment by fujiwarat** [comment] 2023-06-18 08:21
Duplicate of #2408

**Closed by fujiwarat** 2023-06-18 08:21 UTC
