### ISSUE TITLE
ibus high cpu usage and possible memory leak, while running tkinter application

### ISSUE THREAD

**Issue by Aboghazala** [ibus/ibus#2324] opened 2021-06-15 21:48 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Pop!_OS 20.10 - groovy

Which desktop environment and version?: 
GNOME 3.38.3

Which session type?: 
X11

Which application and version?: 
Tkinter version: 8.6.10
Python version: 3.8.6 [GCC 10.2.0]

IBus version?: 
IBus 1.5.23

Issue description:

when running tkinter application ibus consume 25-30% of cpu power and memory usage increase gradually, closing tkinter application and run it several times will result in more memory usage by ibus "build up and never free memory"
and because of this my tkinter application will take a lot of time to completely load start of 3 seconds on first run to several minutes on following runs as time goes on.

Steps to reproduce:
1. save below python code in a file named test.py 

I made a minimal python code to reproduce the problem:
```
import tkinter as tk
import time

root = tk.Tk()
start = time.time()
f = tk.Frame(root)
f.pack()

def create_lbls(x):
    global f
    f.pack_forget()
    f = tk.Frame(root)
    f.pack()
    for i in range(1, 21):
        tk.Label(f, text=f'label {x + 1} - {i:02d} {"-"*20}').pack()
        root.update_idletasks()

for x in range(50):
    root.after(10, create_lbls, x)

root.mainloop()
```
2. run in shell `python3 test.py`
3. open system monitor and watch ibus-daemon and ibus-x11
4. after running this script several times, ibus-daemon will kick cpu and consume 25-30% of cpu power, and its memory consumption increases over time during tkinter application running
5. ibus-x11, will consume sometimes 1% and other times 20% but its memory consumption increases over time too
6. problem disappear if terminating ibus-x11 and leave only ibus-daemon running

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes, after doing this all ibus things are normal but after a while of continuous running of tkinter app. ibus misbehave and start consume 25-30% and sometimes peak to 40% with continuous used ram size grow

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no output in verbose mode

this is default when nothing is running, ibus 0% cpu usage and ram usage 5.5 MB and ibus-x11 7.3MB
![image](https://user-images.githubusercontent.com/37757246/122126917-b37e0800-ce32-11eb-9389-a34f7a102d77.png)

After repeat running of tkinter app (the above python script), ibus 29% cpu and 414MB memory size
![image](https://user-images.githubusercontent.com/37757246/122127135-05bf2900-ce33-11eb-8763-e90757604f7f.png)

at this stage even opening a calculator and start fast typing random numbers will make ibus kick cpu to 20%

**Comment by Aboghazala** [comment] 2021-06-16 20:28
update:
when quitting `ibus-daemon` using command `ibus exit` and run `ibus-daemon` without `--xim` option seems to have no problem with memory or cpu while running tkinter application, after checking i found out ibus-x11 didn't start
I thought this might help 

running with no `--xim` argument, just `ibus-daemon -d`
![image](https://user-images.githubusercontent.com/37757246/122287443-3e253c80-cef1-11eb-85d4-89e278c984f5.png)

**Comment by firedm** [comment] 2021-07-03 11:30
@fujiwarat 
is there any fix for this problem?
i believe ibus-x11 intercept every drawing action of x-server and pass it to ibus-daemon  which is slowing down any tkinter application's gui loading time (linearly) over time, plus the memory consumption grow with every run, ibus-x11, ibus-daemon reach over 1 GB of memory and continue growing.

if this is not the right place to report ibus bugs please let me know

**Comment by eikesuthau** [comment] 2021-12-17 05:29
A simple work-around is inserting the lines below before initializing tkinter. 
This will avoid keypresses being run through ibus before getting to your
application. If one relies on being able to type CJK characters this is obviously
no option.

```
import os
#disable input methods to improve speed
os.environ['XMODIFIERS'] = "@im=none"
```
I think that this is a bug in tkinter since other GUI programs do
not have this issue. However, ibus seems to have an issue as well:
ibus-daemon consumes 50% of a modern CPU when you hold a
key down which seems excessive.

I hope this helps.

**Comment by Aboghazala** [comment] 2021-12-17 14:43
@eikesuthau 
thanks a lot, i really appreciate this help

my workaround was to kill ibus process and restart it after tkinter initialize 
but definitely your workaround is more cleaner than mine

**Comment by fujiwarat** [comment] 2023-11-21 00:44
Checking the issue from ibus-x11 side, seems `xim_destroy_ic()` is not called as `xim_create_ic()` is called. It means your code has a problem.

```
def create_lbls(x):
    global f
    f.pack_forget()
    f = tk.Frame(root)
```

I think the `f.pack_forget()` does not release the labels but just hide them.
To fix your issue, you need to replace `f.pack_forget()` with `f.destroy()` AFAIK.

**Closed by fujiwarat** 2023-11-21 00:44 UTC

**Comment by dinogomez** [comment] 2024-06-07 15:47
Didn't really wanted to necro, but it was taking me a week or so to debug why the app was rendering so slow. Eventually found @eikesuthau 's fix to be a godsend. Thank you so much.

**Comment by jeb2112** [comment] 2024-06-10 18:18
I'm still not really sure what's going on, but I somehow created this problem for 6 months into a tkinter GUI project. I can probably figure out which commit specifically did it, but in the meantime @eikesuthau fix is doing the job.

**Comment by aharel** [comment] 2024-11-17 10:37
First, many thanks to eikesuthau for the workaround. This issue has plagued us for years.
We have a GUI screen with >1000 widgets on it, and it often hits a problem where ibus-daemon's  CPU usage goes >100% and the entire system slows down. There is a  quadratic slow down - the construction of the screen slows down as more widgets exist on it, and speeds up during the destruction.
From this behavior and the comments above, there are probably two bugs here. One in tkinter which interacts with ibus-daemon for widgets that do not accept key presses.  
One in ibus-daemon which has quadratic performance in the number of xim_create_ic() connections (those where xim_destroy_ic() hasn't yet been called). It seems that the time constant before the quadratic is low, so few hit this bug.

**Comment by fujiwarat** [comment] 2024-11-18 03:47
As I noted, it's an application bug not ibus.

**Comment by rcohen98** [comment] 2026-08-19 08:38
Still present on **IBus 1.5.34-rc2** (Ubuntu 26.04, GNOME, Wayland session so Tk runs under XWayland). Adding measurements rather than another "me too", since this thread never got a quantified impact.

### What it cost

`ibus-daemon` had been running since login and systemd's own accounting on restart read:

```
org.freedesktop.IBus.session.GNOME.service: Consumed 4h 50min 12.584s CPU time
                                            over 1d 4h 35min 22.772s wall clock
```

Sampled directly, it was using **5 s of CPU per 5 s of wall clock while completely idle** — 100% of one core, no typing, no focus changes.

The user-visible effect is on **XIM input-context creation**. Tk creates one context per window and in Tk every widget *is* an X window, so a GUI with ~165 widgets pays for 165 of them:

| | |
|---|---|
| one X window map, XIM enabled | **183 ms** |
| same, `XMODIFIERS=@im=none` | **1.3 ms** |
| our app's startup, XIM enabled | **30.3 s** |
| same, input methods off | **0.11 s** |

### Evidence it is the XIM path and not the display stack

- `strace` shows the client blocked in `poll([{fd=3 (the X socket)}], 1, -1)` for ~180 ms, immediately after a `ChangeProperty` — an *infinite* timeout returning `POLLIN`, i.e. a real reply arriving late, not a timeout being hit.
- A generic X client→client round trip on the same transport (`tk send` between two Tk interpreters, which also uses properties + ClientMessages) takes **0.21 ms**. Same server, same second — 875× faster. XWayland's event delivery is fine.
- `ibus-x11` used **0 s of CPU** over its entire 13281 s life — it is a pass-through.
- `ibus-daemon` consumed **~6 CPU seconds during ~20 window maps**. The time is real CPU work in the daemon, not a stall.

### Restarting the daemon fixes it

```
ibus restart
  daemon idle CPU        5 s / 5 s   ->  0 s / 5 s
  X window map cost      183 ms      ->  1.5 ms   (XIM still enabled)
```

### Honest limitation

**I could not reproduce it from a fresh daemon on demand.** After `ibus restart` I created and destroyed ~4000 XIM contexts in about a minute, hard-killed X clients mid-run, and restarted Xwayland underneath `ibus-x11` — idle CPU stayed at 0 through all of it. That is consistent with the original report's "running this script multiple times progressively worsens the problem": the load that produced it here was roughly a day of automated GUI test sweeps launching Tk applications several hundred times, each building and tearing down a full widget tree around `update_idletasks()`. A one-minute burst does not appear to be enough.

So this is a report of the effect and its cost on a current version, not a from-scratch reproducer. Happy to run anything specific on 1.5.34-rc2 if it would help.
