### ISSUE TITLE
Emoji annotation no longer searches or shows full emoji list

### ISSUE THREAD

**Issue by kewbish** [ibus/ibus#2508] opened 2023-04-29 16:19 UTC
Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

Manjaro Talos 22.1.0.

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

XFCE 4.18.

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

X11.

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

All applications (including Google Chrome 111.0.5563.146).

IBus version?: 
(Run `ibus version`)

IBus 1.5.28.

Issue description:

Previously (not sure when this started as I don't use emoji annotation very frequently), when I pressed my emoji annotation shortcut, a list of emoji categories (food, people, etc.) would appear. If I typed further, it would start an emoji search.

Now, when I press the shortcut, a panel still appears, but only with 'Favourites' (which shows a limited number of emoji) and 'Open unicode choice' (which shows a lot of `U+FFFFFFFF`). When I type further, it doesn't show any emoji results.

https://user-images.githubusercontent.com/45278276/235312645-07e7146f-bb83-46f3-a925-3da136fb2954.mp4

Steps to reproduce:
1. Press emoji annotation shortcut
2. Try to type to start a search
3. No input appears

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Yes, I see a lot of:
```
(ibus-ui-emojier:51003): IBUS-CRITICAL **: 09:06:58.852: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed
```
followed by a lot of:
```
(ibus-ui-emojier:51003): IBUS-CRITICAL **: 09:06:58.971: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed
(ibus-ui-emojier:51003): IBUS-CRITICAL **: 09:06:58.971: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed
(ibus-ui-emojier:51003): IBUS-CRITICAL **: 09:06:58.971: ibus_emojier_update_emoji_to_data_dict: assertion 'data != NULL' failed
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

Haven't tried yet, will try shortly and update.

**Comment by fujiwarat** [comment] 2023-05-01 03:31
Which do you get distribution ibus packages or you build packages from ibus sources by yourself?
I think you need to install https://github.com/ibus/ibus/commit/7c8abbe89403c2fcb08e3fda42049a97187e53ab

**Comment by fujiwarat** [comment] 2023-05-01 03:31
Duplicate of #2476

**Closed by fujiwarat** 2023-05-01 03:31 UTC
