### ISSUE TITLE
Use keyup as a way to trigger hotkeys

### ISSUE THREAD

**Issue by q962** [ibus/ibus#2452] opened 2022-10-16 13:39 UTC
Can the hotkey trigger event be changed to "keyup"?

I changed the hotkey to alt-shift, but this way I can't hit alt-shift-* shortcuts in other software. keydown is not a good design.

I found no option to modify it.

**Comment by fujiwarat** [comment] 2022-10-17 09:24
Duplicate of #1816

**Closed by fujiwarat** 2022-10-17 09:24 UTC

**Comment by q962** [comment] 2022-10-17 12:41
I'm not looking for a way to set shortcuts.

E.g
https://docs.gtk.org/gtk4/signal.EventControllerKey.key-released.html
https://docs.gtk.org/gtk4/signal.EventControllerKey.key-pressed.html

Instead of using 'key-pressed' , use 'key-released' to trigger the relevant action.

You can find a gtk4 program for testing. For example 'gtk4-demo'.

Use `<Ctrl>Shift_L` as a shortcut to switch the ibus input method.
Typing `<Ctrl><Shift>D` to 'gtk4-demo' does not invoke gtk4's inspector.

But if ibus uses the 'keyup' way, this problem can be solved.

**Comment by fujiwarat** [comment] 2022-10-18 11:56
Probably I disagree to use key-release for ibus shortcut keys.

**Comment by q962** [comment] 2022-10-18 12:09
Why?
