### ISSUE TITLE
Invalid reads reported by valgrind causing nautilus crashes?

### ISSUE THREAD

**Issue by seb128** [ibus/ibus#2498] opened 2023-04-03 11:10 UTC
On Ubuntu Lunar we started received report of nautilus crashing when using the search feature, try to reproduce locally on a 
xfce X11 session with the current ibus 1.5.28-2 package it doesn't crash but valgrind reports invalid read entries from ibus-gtk

```
==51301== Invalid read of size 4
==51301==    at 0x48686AB: _process_key_event (ibusimcontext.c:545)
==51301==    by 0x4869518: UnknownInlinedFun (ibusimcontext.c:1197)
==51301==    by 0x4869518: ibus_im_context_filter_keypress (ibusimcontext.c:1140)
==51301==    by 0x4AE18A6: gtk_event_controller_key_handle_event (gtkeventcontrollerkey.c:99)
==51301==    by 0x4C27C42: UnknownInlinedFun (gtkeventcontroller.c:362)
==51301==    by 0x4C27C42: gtk_widget_run_controllers (gtkwidget.c:4565)
==51301==    by 0x4AE1D1F: gtk_event_controller_key_forward (gtkeventcontrollerkey.c:358)
==51301==    by 0x14AE7F: nautilus_window_key_capture.lto_priv.0 (nautilus-window.c:1839)
==51301==    by 0x4A7BADE: _gtk_marshal_BOOLEAN__UINT_UINT_FLAGSv (gtkmarshalers.c:2256)
==51301==    by 0x5556A62: UnknownInlinedFun (gclosure.c:895)
==51301==    by 0x5556A62: g_signal_emit_valist (gsignal.c:3462)
==51301==    by 0x5557922: g_signal_emit (gsignal.c:3612)
==51301==    by 0x4AE198C: gtk_event_controller_key_handle_event (gtkeventcontrollerkey.c:121)
==51301==    by 0x4C27C42: UnknownInlinedFun (gtkeventcontroller.c:362)
==51301==    by 0x4C27C42: gtk_widget_run_controllers (gtkwidget.c:4565)
==51301==    by 0x4C27E43: _gtk_widget_captured_event (gtkwidget.c:4728)
==51301==  Address 0x251cc948 is 24 bytes inside a block of size 112 free'd
==51301==    at 0x484620F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==51301==    by 0x48DE63D: g_source_unref_internal (gmain.c:2422)
==51301==    by 0x48DE9C8: g_source_destroy_internal (gmain.c:1430)
==51301==    by 0x48DF5E2: g_source_remove (gmain.c:2620)
==51301==    by 0x48684C4: _process_key_event_reply_done (ibusimcontext.c:457)
==51301==    by 0x53FF612: g_task_return_now (gtask.c:1309)
==51301==    by 0x5403042: UnknownInlinedFun (gtask.c:1378)
==51301==    by 0x5403042: g_task_return (gtask.c:1335)
==51301==    by 0x54692AB: reply_cb (gdbusproxy.c:2571)
==51301==    by 0x53FF612: g_task_return_now (gtask.c:1309)
==51301==    by 0x5403042: UnknownInlinedFun (gtask.c:1378)
==51301==    by 0x5403042: g_task_return (gtask.c:1335)
==51301==    by 0x5459801: g_dbus_connection_call_done (gdbusconnection.c:5885)
==51301==    by 0x53FF612: g_task_return_now (gtask.c:1309)
==51301==  Block was alloc'd at
==51301==    at 0x4848A13: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==51301==    by 0x48E6550: g_malloc0 (gmem.c:163)
==51301==    by 0x48DF141: g_source_new (gmain.c:1031)
==51301==    by 0x48E1AAC: UnknownInlinedFun (gmain.c:5070)
==51301==    by 0x48E1AAC: g_timeout_source_new (gmain.c:5100)
==51301==    by 0x486860D: _process_key_event (ibusimcontext.c:515)
==51301==    by 0x4869518: UnknownInlinedFun (ibusimcontext.c:1197)
==51301==    by 0x4869518: ibus_im_context_filter_keypress (ibusimcontext.c:1140)
==51301==    by 0x4AE18A6: gtk_event_controller_key_handle_event (gtkeventcontrollerkey.c:99)
==51301==    by 0x4C27C42: UnknownInlinedFun (gtkeventcontroller.c:362)
==51301==    by 0x4C27C42: gtk_widget_run_controllers (gtkwidget.c:4565)
==51301==    by 0x4AE1D1F: gtk_event_controller_key_forward (gtkeventcontrollerkey.c:358)
==51301==    by 0x14AE7F: nautilus_window_key_capture.lto_priv.0 (nautilus-window.c:1839)
==51301==    by 0x4A7BADE: _gtk_marshal_BOOLEAN__UINT_UINT_FLAGSv (gtkmarshalers.c:2256)
==51301==    by 0x5556A62: UnknownInlinedFun (gclosure.c:895)
==51301==    by 0x5556A62: g_signal_emit_valist (gsignal.c:3462)
```

**Comment by fujiwarat** [comment] 2023-04-04 06:48
I don't know if the nautilus crash report is relative with the valgrind report.
I need to look at the stack trace of the nautilus crash.

**Comment by seb128** [comment] 2023-04-05 07:16
Right, I'm unsure if the nautilus reports are due to ibus but the invalid read does seem an ibus problem even if that's not the case of those nautilus reports so still worth fixing

**Comment by fujiwarat** [comment] 2023-07-06 23:44
https://gitlab.gnome.org/GNOME/nautilus/-/issues/2877

**Comment by fujiwarat** [comment] 2023-07-06 23:55
Duplicate of #2486

**Closed** 2023-07-06 23:55 UTC
