### ISSUE TITLE
Dead keys on German keyboard after upgrade to 1.5.29-1.1 in MAME application

### ISSUE THREAD

**Issue by mizapf** [ibus/ibus#2594] opened 2023-12-30 13:41 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
openSUSE Tumbleweed

Which desktop environment and version?: 
Plasma 5

Which session type?: 
X11

Which application and version?: 
MAME (emulator, all versions)

IBus version?: 
1.5.29-1.1

Issue description:
Special keys on my German keyboard are dead im MAME after upgrade from ibus1.5.28-3.1 to 1.5.29-1.1, in particular the umlaut keys (ä, ö, ü). I could not find another application with the same symptom yet.

Steps to reproduce:
Upgrade to ibus1.5.29-1.1
Run MAME with any emulated system or with the on-screen display menu. 
Type ö on a German keyboard; no reaction.
Rollback to ibus1.5.28-3.1; keys work again.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
not tried

Do you see any errors when you run ibus-daemon with the verbose option?:
not tried

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment] 2024-01-03 05:38
I guess mame is a SDL based application as I don't try it.
Duplicate of #2585

**Closed by fujiwarat** 2024-01-03 05:38 UTC
