### ISSUE TITLE
Keyboard keys get stuck down (Xorg/Wayland) in Proton (Experimental?) games

### ISSUE THREAD

**Issue by romulasry** [ibus/ibus#2485] opened 2023-03-07 02:26 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora release 39 (Rawhide)

Which desktop environment and version?: 
Gnome 44.beta

Which session type?: 
Wayland

Which application and version?: 
Proton Experimental as of today March 6, 2023.

IBus version?: 
IBus 1.5.28

Issue description:
Keyboard keys get stuck in Proton Experimental

Steps to reproduce:
1.  Steam
2.  Enable Proton Experimental
3.  Load Game
4.  Play game for a while and wait 2-5 minutes and the keys stick

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(ibus-extension-gtk3:49862): IBUS-CRITICAL **: 18:23:34.920: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): Didn't check

Other steam users seem to be getting the same issue: https://github.com/ValveSoftware/Proton/issues/5294 Except it isn't at low FPS.

**Comment by scramble45** [comment] 2023-03-07 04:30
Arch `6.2.2-zen1-1-zen` with `ibus-daemon - Version 1.5.28` with X

Experiencing the same issue in all proton / wine  apps, WASD keys or others that are pressed for continued amount of time cause it to never stop and you start moving in one direction indefinitely until you let go and press the key a single time, acts like a stuck key. This issue did not seem to be present until this version.

**Comment by LRitzdorf** [comment] 2023-03-07 05:23
Also superficially similar to #2081.

**Comment by Mershl** [comment] 2023-03-07 20:56
Seeing the same on Fedora 38. Downgrading to Fedora 37 fixes the issue.

Fedora 37: `ibus-1.5.27-5.fc37.x86_64` - not affected
Fedora 38: `ibus-1.5.28-1.fc38.x86_64` - affected -> killing ibus-daemon (killall ibus-daemon) fixes the issue for the current boot

**Comment by fujiwarat** [comment] 2023-03-08 10:55
Duplicate of #2480

**Comment by fujiwarat** [comment] 2023-03-16 12:17
Now ibus-1.5.28-2.fc38 and ibus-1.5.28-2.fc39 are available in updates-testing repo.

**Closed** 2023-03-23 04:34 UTC

**Comment by fansari** [comment] 2024-01-05 16:31
I stil have this issue with ibus-1.5.29~rc2-6.fc39.x86_64. "ibus restart" after starting Steam prevents the issue.

**Comment by synden** [comment] 2025-06-29 06:00
> Arch `6.2.2-zen1-1-zen` with `ibus-daemon - Version 1.5.28` with X
> 
> Experiencing the same issue in all proton / wine apps, WASD keys or others that are pressed for continued amount of time cause it to never stop and you start moving in one direction indefinitely until you let go and press the key a single time, acts like a stuck key. This issue did not seem to be present until this version.

I have  gotten this in the past few days... I have 6.15.4-zen2-1-zen with Arch, Hyprland 0.49.0
