### ISSUE TITLE
Lost "Shift" when using QMK layers for shifted keys

### ISSUE THREAD

**Issue by Pistahh** [ibus/ibus#2600] opened 2024-01-05 21:09 UTC
* Ubuntu 23.10
* Gnome
* X11
* ibus 1.5.29
* wezterm 20231228-084719-ff274374

Issue description:

Given a programmable keyboard that is able to send keyboard events such as key presses and key releases in "batches" - sequentially but within a very short time period, it is observed that ibus, when processing these key events, sometimes does not handle modifier states (such as the state of the shift key) correctly, resulting in incorrect ibus-generated key codes sent to applications.

My OS keyboard layout is set to Hungarian as I need Hungarian accents. In this layout `"` is available as `Shift-2`.

It is expected that 
1. pressing and holding the `Shift` key, then
2. pressing and releasing the `2` key, then
3. releasing the `Shift` key

results in the `"` character sent to the application.

In the "good" case indeed this happens, but in the "bad" case the `2` character is sent, as if the `Shift` key weren't held.

  Looking into the linux input layer events all the content of the key events are similar, the only difference is the timing, in the "wrong" case there is only about 1ms between the press and the release events.

**Example for a properly working "good" case:**

There is a "long", 0.1 second delay between pressing and releasing the keys:

```
Event: time 1704482710.029792, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e1
Event: time 1704482710.029792, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 1
Event: time 1704482710.029792, -------------- SYN_REPORT ------------
Event: time 1704482710.030651, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001f
Event: time 1704482710.030651, type 1 (EV_KEY), code 3 (KEY_2), value 1
Event: time 1704482710.030651, -------------- SYN_REPORT ------------

# Note the "delay" here is about 0.12s

Event: time 1704482710.154687, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001f
Event: time 1704482710.154687, type 1 (EV_KEY), code 3 (KEY_2), value 0
Event: time 1704482710.154687, -------------- SYN_REPORT ------------
Event: time 1704482710.155611, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e1
Event: time 1704482710.155611, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 0

```

the application receives it correctly from ibus:

```
17:21:12.354  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
17:21:12.354  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftShift, modifiers: SHIFT, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
17:21:12.354  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=LeftShift mods=SHIFT

# So the Shift was received and handled and it is also recognised in the following event:

17:21:12.359  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(K2), modifiers: SHIFT, leds: (empty), phys_code: Some(K2), raw_code: 11, repeat_count: 1, key_is_down: true, handled: Handled(false) }
17:21:12.359  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('"'), modifiers: SHIFT, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K2), modifiers: SHIFT, leds: (empty), phys_code: Some(K2), raw_code: 11, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
17:21:12.359  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('"') mods=SHIFT
17:21:12.359  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\"", Char('"') SHIFT
17:21:12.505  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('2'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K2), modifiers: NONE, leds: (empty), phys_code: Some(K2), raw_code: 11, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
17:21:12.505  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('2') mods=NONE
17:21:12.509  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftShift, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
17:21:12.509  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=LeftShift mods=NONE
```

**Example for a incorrectly working "wrong" case:**

There is a "short", 1 ms delay between pressing and releasing the keys:

```
Event: time 1704482719.998845, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e1
Event: time 1704482719.998845, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 1
Event: time 1704482719.998845, -------------- SYN_REPORT ------------
Event: time 1704482719.999673, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001f
Event: time 1704482719.999673, type 1 (EV_KEY), code 3 (KEY_2), value 1
Event: time 1704482719.999673, -------------- SYN_REPORT ------------

# Note that the delay here is only about 1ms

Event: time 1704482720.000702, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001f
Event: time 1704482720.000702, type 1 (EV_KEY), code 3 (KEY_2), value 0
Event: time 1704482720.000702, -------------- SYN_REPORT ------------
Event: time 1704482720.001721, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e1
Event: time 1704482720.001721, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 0
```
the application receives an incorrect `2` from ibus:

```
17:21:21.053  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }
17:21:21.053  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftShift, modifiers: SHIFT, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: SHIFT, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
17:21:21.053  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=LeftShift mods=SHIFT

# So the Shift was received and handled but then in the following event  it is not there as a modifier, so wezterm sends `2` instead of `"`.

17:21:21.055  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(K2), modifiers: NONE, leds: (empty), phys_code: Some(K2), raw_code: 11, repeat_count: 1, key_is_down: true, handled: Handled(false) }
17:21:21.055  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('2'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K2), modifiers: NONE, leds: (empty), phys_code: Some(K2), raw_code: 11, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
17:21:21.055  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('2') mods=NONE
17:21:21.055  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "2", Char('2') NONE
17:21:21.055  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('2'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K2), modifiers: NONE, leds: (empty), phys_code: Some(K2), raw_code: 11, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
17:21:21.055  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('2') mods=NONE
17:21:21.056  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: LeftShift, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftShift), modifiers: NONE, leds: (empty), phys_code: Some(LeftShift), raw_code: 50, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
17:21:21.056  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=LeftShift mods=NONE
```
The issue only happens in wezterm with ibus enabled. If I disable ibus in wezterm so it relies on the key events directly sent by the keyboard then it works correctly (by setting `config.use_ime = false`)

The issue also goes away if I run wezterm with ibus enabled but I kill the ibus daemon.

---------------------------------------------------------------------

Technical background, irrelevant to the issue:

I use a keyboard with a programmable firmware (QMK - https://qmk.fm/).

If I configure a key in the QMK keymap directly as `LSFT(KC_2)` - this tells QMK to send the shift-press,2-press,2-release,shift-release events, i.e. the combination that under the Hungarian layout manifests in a `"`.

To ease my workflow I want a dedicated layer for symbols so I don't have to reach up to the number row in the keyboard, so
in my QMK keymap I made a dedicated symbols layer, accessible by the `d` key: `LT(_SYM,KC_D)` - this means that if I just tap the `d` key it literally just sends the `d` keycode, but if I hold it pressed (as if it were e.g. shift) it activates another layer where the keys get different meanings. On this symbol layer the `n` key is defined as `LSFT(KC_2)`.

It is expected that using this keymap holding `d` and then tapping `n` would result in a `"`character, but under wezterm it results in a `2` - as if the shift key wasn't pressed ("wrong" case). This is 100% reproducible on my computer.

Steps to reproduce:
1. Take or build a QMK keyboard
1. create a keymap with `d` configured as `LT(_SYM,KC_D)`  and `n` configured as `LSFT(KC_2)`
1. compile the firmware using this keymap and flash it to the keyboard
1. configure Ubuntu to use Hungarian layout
1. start wezterm
1. press and hold `d` then quickly tap `n`

Can you reproduce your problem when you restart ibus-daemon? (yes / no):
The issue goes away after ibus is killed (by running `ibus exit`) but doesn't come back after restarting it with `ibus-daemon --xim &`

Do you see any errors when you run ibus-daemon with the verbose option?:
No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Not tried.

**Comment by fujiwarat** [comment] 2024-01-06 15:44
IBus uses D-Bus method to communicate the application clients and IBus engines and I think the exact typing delay is not ensured and I'd say QMK keyboard should handle the  key events if it receives 'd' and 'n' keys.

**Comment by Pistahh** [comment] 2024-01-06 16:11
> IBus uses D-Bus method to communicate the application clients and IBus engines and I think the exact typing delay is not ensured and I'd say QMK keyboard should handle the key events if it receives 'd' and 'n' keys.

The issue is not with the keyboard. The issue is that in the circumstance described above the key presses are not processed correctly by ibus (or some other ibus component). The issue is visible in wezterm when it relies on ibus and it goes away if it is configured not to use ibus. The logs taken from the linux event subsystems prove that the keyboard does the right thing.

**Comment by fujiwarat** [comment] 2024-01-07 01:39
I think IBus sends the key events.

**Comment by Pistahh** [comment] 2024-01-07 10:32
> I think IBus sends the key events.

Yes, and (as demonstrated in the ticket)  it sends the wrong ones:
```
17:21:12.505  [...] key: Char('2'), modifiers: NONE [...]
```

instead of
```
17:21:12.505  [...] { key: Char('"'), modifiers: SHIFT
```
.

**Comment by fujiwarat** [comment] 2024-01-07 13:02
You're talking about pressing 'd' and 'n' and I think '2' or '"' should be handled by the application.

**Comment by sigprof** [comment] 2024-01-07 14:45
`d` and `n` there are not really relevant — those keys are not seen by the computer directly.  What the computer actually receives are these HID reports (which are then converted into individual press/release events by the Linux input subsystem):

1. LeftShift pressed
2. (1 ms later) LeftShift and `2` are pressed
3. (1 ms later) LeftShift is pressed
4. (1 ms later) nothing is pressed

This sequence corresponds to what the manual LeftShift+2 press may look like, except the delays between the events are as small as possible (1000 Hz polling rate ⇒ 1 ms delay between reports).  And apparently something in the input stack is not able to handle these events correctly on the reporter's machine.

Another important observation here is that adding an extra delay between the reports 2 and 3 (which is what happens when the `LSFT(KC_2)` key in QMK is pressed manually) avoids the problem.  So maybe the reason why this does not work is that some events are not handled in a strictly synchronous way — e.g., the code which handles the press of `2` does not track the modifier state itself, but reads it from some other component that had already processed the modifier release event which actually came 2 ms later.  (At least this was the case with the infamous GNOME+Wayland bug with lost modifiers — https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5890, where killing IBus was also a workaround.)

**Comment by fujiwarat** [comment] 2024-01-07 15:41
> This sequence corresponds to what the manual LeftShift+2 press may look like, except the delays between the events are as small as possible (1000 Hz polling rate ⇒ 1 ms delay between reports). And apparently something in the input stack is not able to handle these events correctly on the reporter's machine.

Do you mean to create an automatic typing using a machine typing likes a barcode scanner evemu?
You don't see your problem if you create the typing test with a large delay likes a standard manual typing?

It might happen that the IBus typing order is not correct as you wouldn't describe the issue exactly.

**Comment by sigprof** [comment] 2024-01-07 21:27
> Do you mean to create an automatic typing using a machine typing likes a barcode scanner evemu?

That's probably another way to reproduce the behavior (and QMK supports various forms of macros).  However, the original problem happens due to a combination of several QMK features:
- `LSFT(KC_2)` is a way to make a single physical keypress send a combination of a regular key with some modifiers;
- `LT(_SYM,KC_D)` is a way to bind separate actions for a hold and a tap to some key — in this particular case the hold action switches the layer to the one where the `LSFT(KC_2)` binding is present;
- one of the modes to distinguish a hold from a tap chooses the hold action when another key is pressed and then released while the dual-role key is held, and in this case the actions for both the dual-role key hold and the next key tap (press+release) are executed immediately when the next key is released; this result in the quick press and release sequence of LeftShift+2.

In this particular case it could be possible to add a workaround at the QMK side by adding some delay somewhere; however, such workarounds are often unreliable, because a delay which is enough for one system may be still not enough for another slower system.  And the same issue may happen with proprietary hardware, like those barcode scanners, where adding workarounds on the hardware side is not possible at all.  So the proper fix would be to find the place where the loss or misordering of input events actually happens and fix the issue there.

Note that in this case there are no HID reports which have multiple key state changes at the same time (QMK can generate such report in some cases — e.g., when a key+modifiers keycode specifies more than one modifier, all those modifiers would be reported at the same time, but still separately from the actual key to which the modifiers should be applied), so there should not be any ambiguity in the processing order.

**Comment by fujiwarat** [comment] 2024-01-08 09:17
> In this particular case it could be possible to add a workaround at the QMK side by adding some delay somewhere; 

I don't understand why you said another way for my question but seems you use a machine typing and that's why the time between typing keys are very short.

I don't ask whether the workaround is unreliable or not but if the problem does not happen with  a large delay likes a standard manual typing to identify your problem.

**Comment by Pistahh** [comment] 2024-01-08 11:50
I re-wrote the issue description so it focuses on the relevant facts, as it is irrelevant that the actual keyboard uses the QMK firmware.

The primary thing to focus on is that ibus receives some correct input from a keyboard but it produces incorrect output - it "forgets" that the shift key is pressed.

**Comment by wengxt** [comment] 2024-01-16 16:56
I believe it's a wezterm bug. As long as you can't reproduce it with xterm.

The reason is that wezterm uses the state mask from xcb key event, but from the state mask from xkb.

When ibus get the event back to wezterm, the xkb doesn't have shift anymore, but the X key event still carries the state mask.

I noticed there's a recent commit in wezterm that might fix this: https://github.com/wez/wezterm/commit/0466898af7b347ff8c81efd57ed7d8da8eace27e

You might want to check on that

**Comment by wez** [comment] 2024-01-22 15:30
re: the recent wezterm commit, what I saw was interesting: the X server would send a StateNotify event that cleared out all of the modifiers before then sending a KeyPress event with the BtnMask set to include shift.
We're working around this now by interpreting the BtnMask for ourselves, even though the XKB stuff doesn't really want us to do that.
I observed this behavior on Ubuntu 22.04 which runs ibus.
I only happens when shift is sent from a keyboard running QMK that toggles the shift modifier very quickly.

**Comment by wez** [comment] 2024-01-22 15:32
Cross linking back to the discussion on the recent wezterm PR: https://github.com/wez/wezterm/pull/4151#issuecomment-1887208316

**Comment by wengxt** [comment] 2024-01-22 16:05
> re: the recent wezterm commit, what I saw was interesting: the X server would send a StateNotify event that cleared out all of the modifiers before then sending a KeyPress event with the BtnMask set to include shift. We're working around this now by interpreting the BtnMask for ourselves, even though the XKB stuff doesn't really want us to do that. I observed this behavior on Ubuntu 22.04 which runs ibus. I only happens when shift is sent from a keyboard running QMK that toggles the shift modifier very quickly.

@wez 

This very easy to explain: 
XKB state notify, have zero knowledge on the input method, and is generated by X server.
When there's no input method in the middle, X event's state and xkb state should be the same.

However, when there's input method, following sequence may happen:

1. X client get key event (This X Key event carries the right key state)
2. Call XFilterEvent (or what ever API that will send XKeyEvent to input method)
3. X client get xkb state notify that clear the state
4. Input method send by the key because input method find this key should be ignored.
5. X client received the key event from input method (As a payload in a XClientMessage), at this point, xkb state is cleared, but the key event will still carries the key state when it's being sent.

When the sequence is generated by human, the 4,5 will before 3, but in QMK/ZMK case, 3 will before 4,5.

You should always use the state mask in the X event, not using the one from XKB if possible.

**Comment by wez** [comment] 2024-01-22 16:11
hmm, that seems counter to some examples of using xkbdcommon.  I can understand the rationale, it just seems like a bit of a hole in the API for it.  I suppose the question I have as a result of this is: what should I be using to correctly decode the BtnMask of the incoming event into appropriate modifiers for the user (if they have been remapped) if I can't use the modifier state maintained by xkbdcommon?

**Comment by wengxt** [comment] 2024-01-22 16:44
> hmm, that seems counter to some examples of using xkbdcommon. I can understand the rationale, it just seems like a bit of a hole in the API for it. I suppose the question I have as a result of this is: what should I be using to correctly decode the BtnMask of the incoming event into appropriate modifiers for the user (if they have been remapped) if I can't use the modifier state maintained by xkbdcommon?

I suppose you’re using the passive way (update_mask, not update_key).

The “depressed latched locked” doesn’t really make much difference when you want to compute key sym because what it really needs is “effective”. That’s exactly the state in x key event. 

So a thing you can do is that, 
1. save the key state you received from xkb (depressed latched locked)
2. call update_mask(state,0,0) in order to make effective mods equals to state in x key event.
3. get keysym
4. restore the key state to xkb ones with update mask

The state from xkb can still be useful if you need the key mask with other event, e.g. to detect a mouse click with shift.

**Comment by wez** [comment] 2024-01-23 19:24
I didn't realize that I could/should `update_key` instead of `update_mask`.  If I switched to that, would that theoretically solve this without further work?  I've pushed a commit that allows opting into `update_key` under x11 for folks to try out in the meantime.

**Comment by wengxt** [comment] 2024-01-23 20:16
@wez  sorry for the confusion, but I mean you shouldn't use update_key. Only Compositor, or things likke Xserver that can receives unfiltered the key event from hardware may use update_key.

**Comment by wez** [comment] 2024-01-23 22:25
OK, so I'm now always using the xcb modifier mask on X11, but relying on the xkb state under wayland. Should I be doing something different under wayland as well?

**Comment by wengxt** [comment] 2024-01-24 15:49
@wez  based on the current wl_keyboard API there's not much you can do there. There's indeed similar issue, but I don't think it's correct to fix it on app side.

**Comment by wez** [comment] 2024-01-24 16:01
@wengxt thanks for your help; I think things are working much better now!

**Comment by Pistahh** [comment] 2024-01-26 14:32
https://github.com/wez/wezterm/issues/3840#issuecomment-1908335504

I can't see the issue anymore with the latest wezterm nightly.

I'm happy to get this issue closed if the common understanding is that there is nothing to be fixed in ibus.

**Comment by fujiwarat** [comment] 2024-01-26 16:21
Closing the bad report.

**Closed by fujiwarat** 2024-01-26 16:21 UTC
