### ISSUE TITLE
Default Layout Switch Shortcut (<super>space) Must Be Pressed Twice

### ISSUE THREAD

**Issue by BlindRepublic** [ibus/ibus#2432] opened 2022-08-11 22:10 UTC
Which distribution and version?: 
EndeavourOS (Arch Linux)

Which desktop environment and version?: 
Cinnamon

Which session type?: 
X11

Which application and version?: 
Any

IBus version?: 
IBus 1.5.26

Issue description:
When using the `<super>space` as the "next input method" shortcut, the layout switch display doesn't appear unless you press the space key a second time. Setting `<alt>space`, for example, to switch the input will not have this effect.

Steps to reproduce:
1. Open `IBus Preferences`
2. Set up two layouts
3. Set keyboard switching shortcut to `<Super>space`

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
```
(ibus-ui-gtk3:61583): IBUS-WARNING **: 18:06:37.657: panel.vala:280: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:61583): IBUS-WARNING **: 18:06:37.673: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:61583): Gdk-CRITICAL **: 18:06:38.688: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```
The first two errors seem completely unrelated to the issue at hand, though I am unsure about the latter.

Can you reproduce your problem with a new user account instead of the current your account?
Yes

**Comment by fujiwarat** [comment] 2024-03-22 08:17
Duplicate of #2474

**Closed by fujiwarat** 2024-03-22 08:17 UTC

**Comment by wujastyk** [comment] 2025-04-12 20:10
It's not just `super+space`.  I'm having the same problem - must press twice - with the key combination `ctrl+alt+space`.

(System: Cinnamon v: 6.4.8 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7 dm: LightDM v: 1.30.0 Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble)
