### ISSUE TITLE
Ubuntu 18 Ibus shows user password on login screen

### ISSUE THREAD

**Issue by sytranvn** [ibus/ibus#2093] opened 2019-04-12 16:01 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 18.04

Which desktop environment and version?: 
ubutu:GNOME 3.28.2

Which session type?: 
x11

Which application and version?: 
gdm3 3.28.2

IBus version?: 
IBus 1.5.17

Issue description:
User password can be exposed on Ubuntu 18 log in screen
![20190412_223740](https://user-images.githubusercontent.com/13009812/56049888-a954b080-5d74-11e9-926d-043647c4a6cc.jpg)

Steps to reproduce:
1. Select input method eg: Vietnamese(unikey))
1. Lock screen
1. Input the password that contains some key ibus uses to convert to special character
1. Observe the password being exposed on screen

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes, I can reproduce on other devices using Ubuntu 18.04

**Comment by sytranvn** [comment] 2019-04-12 16:11
I don't know other languages so I cannot test this issue for other input methods.

**Comment by fujiwarat** [comment] 2019-04-15 11:05
> Select input method eg: Vietnamese(unikey))

I think the IME should not be selected. How did you select it? I looked at your screenshot and I cannot file the IBus icon to select an IME.

Since I cannot reproduce your problem in Fedora, probably it's good for you to check gnome-shell 3.28.3-0ubuntu0.18.04.4

https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1765304

**Comment by sytranvn** [comment] 2019-04-15 18:33
Sorry for confusion.
First you need to log in and switch input method, then do other steps. Please help to check again.
If it can't be reproduced on Fedora then I will try report to ubuntu.

**Comment by sytranvn** [comment] 2019-04-15 18:46
Sorry for confusion. First step is to log in then select input method in shell menu.

![Screenshot from 2019-04-16 00-46-21](https://user-images.githubusercontent.com/13009812/56157275-491a7480-5fe9-11e9-81ce-2260103a8319.png)

Then lock screen and type password to log in again.

**Comment by fujiwarat** [comment] 2019-04-16 05:44
OK, you meant the lock screen but not log in screen and I can reproduce your problem in Fedora 28 but it's fixed in Fedora 29.
Your problem is fixed in GNOME 3.30.z.

**Closed by fujiwarat** 2019-04-16 05:44 UTC

**Comment by sytranvn** [comment] 2019-04-17 03:45
Great! Thanks @fujiwarat.
