### ISSUE TITLE
1.5.28 regresses dead key handling when using Anthy

### ISSUE THREAD

**Issue by DarkShadow44** [ibus/ibus#2497] opened 2023-03-28 21:57 UTC
Version 1.5.28 breaks usage of dead keys (e.g. accents like ^ ` ´) in a weird way
To be exact, it's commit 19ca10651890ce0d88ec613de0e8930090105dc8

Background info:
When typing in a KDE konsole window and pressing an accent key it shows a preview of the accent. When you then press a letter, it removes the preview and and then puts out an accented letter. This is correct.

But when pressing the same accent key twice, I expect the accent to be written into the console.
Similarly, when pressing an accent key and then space, I also expect the accent to be written into the console.

Since 1.5.28 those things are different:
When pressing an accent key twice, it puts two accents into the preview queue, which IMHO doesn't make sense at all.
When pressing an accent key and then space, it puts the accent and the space into the console. That space should not be there.

I also saw commit 497f0c74230a65309e22ce5569060ce48310406b, but this doesn't fix this issue.

This issue seems to only appear when using ibus with Anthy, I use that for Japanese IME.

Arch Linux (latest)
KDE 5.27.3 (Cinnamon is also affected)
X11
Affected are AFAIK all programs, tested konsole, gimp, dolphin, kwrite and more

**Comment by fujiwarat** [comment] 2023-03-29 11:57
Are you talking about ibus-anthy?
This is the ibus core upstream.

Duplicate of ibus/ibus-anthy/issues/34

**Closed by fujiwarat** 2023-03-29 11:57 UTC

**Comment by DarkShadow44** [comment] 2023-03-29 16:05
Thanks, since upgrading ibus broke it, I assumed it was an ibus issue.
