### ISSUE TITLE
When type very quickly in font dialog the input character order is reversed

### ISSUE THREAD

**Issue by epico** [ibus/ibus#2465] opened 2022-12-15 06:14 UTC
Which distribution and version?: 
Fedora 37

Which desktop environment and version?: 
GNOME

Which session type?: 
X11

Which application and version?: 
gnome-text-editor 43.1

IBus version?: 
IBus 1.5.27

Issue description:
When change the default font in gnome-text-editor in preference dialog, the input character order is reversed.

Steps to reproduce:
1. Launch gnome-text-editor in GNOME Xorg, and open the preference dialog
2. Open the "Select Font" dialog, and type "Source" very quickly to filter the font list
3. The "Sruoce" appears in the text entry

**Comment by fujiwarat** [comment] 2023-04-19 23:11
This was reported earlier but there is no evaluations and discussions so I close this to the later report, sorry.

Duplicate of #2486

**Closed** 2023-04-19 23:11 UTC
