### ISSUE TITLE
A  HDPI bug

### ISSUE THREAD

**Issue by hillwoodroc** [ibus/ibus#2172] opened 2020-01-05 07:41 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
openSUSE Tumbleweed

Which desktop environment and version?: 
GNOME 3.24

Which session type?: 
Wayland.

Which application and version?: 
GNOME application

IBus version?: 
1.5.21

Issue description:
While the HDPI zooming enables, ibus can not follow cursor. There are two screenshots, the first one enabled HDPI zooming, the second one is disabled HDPI zooming. The bug just occurs on GNOME applications. The third one worked fine on Qt application,

![with zooming in 125%](https://user-images.githubusercontent.com/1880237/71776737-36115f80-2fd1-11ea-9178-4abc1eb609a8.png)
![without zooming](https://user-images.githubusercontent.com/1880237/71776738-36a9f600-2fd1-11ea-895c-6a2131a2c434.png)
![work on Qt](https://user-images.githubusercontent.com/1880237/71776891-d2d4fc80-2fd3-11ea-84b0-c1807531290b.png)

**Comment by fujiwarat** [comment] 2020-01-08 09:11
I still cannot configure HDPI in my boxes. I run `gnome-control-center display` and set "1920 x 1400 (4 : 3)" and scale 2 and the lookup window position is fine with gedit and firefox.

**Comment by fujiwarat** [comment] 2020-01-08 09:24
Duplicate of #2157

**Closed by fujiwarat** 2020-01-08 09:24 UTC

**Comment by hillwoodroc** [comment] 2020-01-10 01:42
Please set scale as 125%, this bug does not occur on interger scale.
![2020-01-08 20-30-01屏幕截图](https://user-images.githubusercontent.com/1880237/72118877-8d2a8200-338d-11ea-879c-03b190497190.png)
