### ISSUE TITLE
Can't get rid of the MF shortcut ctrl+shift+U even after changing in ibus-setup

### ISSUE THREAD

**Issue by uriariel** [ibus/ibus#2231] opened 2020-06-21 22:13 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Ubuntu 20.04 LTS kernel 5.4.0-37-generic #41
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
ubuntu:GNOME 3.36.2
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
x11
IBus version?: 
IBus 1.5.22

Issue description:
Can't get rid of the MF shortcut ctrl+shift+U even after changing in ibus-setup

Steps to reproduce:
1. Use ibus

**Comment by fujiwarat** [comment] 2020-07-21 13:04
Probably I think your issue is caused by the Ubuntu specific patch.
Duplicate of #2163

**Closed by fujiwarat** 2020-07-21 13:04 UTC
