### ISSUE TITLE
Chinese input doesn't work when switched directly from Russian

### ISSUE THREAD

**Issue by marmistrz** [ibus/ibus#2010] opened 2018-05-15 07:41 UTC
Which distribution and version?: Arch Linux

Which desktop environment and version?: Cinnamon 3.8.2

Which session type?: X11

Which application and version?: any, let it be firefox

IBus version?: 1.5.18

Issue description: Chinese input doesn't work when switched directly from Russian

Steps to reproduce: 
1. Switch Russian, phonetic keyboard
2. Switch to Chinese pinyin IME
3. Russian characters are typed instead of the Latin ones and as a consequence, the Chinese IME doesn't propose any Chinese characters.

It looks like ibus just forgets to switch back to the Latin keyboard layout as the base for the IME.

Can you reproduce your problem when you restart ibus-daemon? yes

Do you see any errors when you run ibus-daemon with the verbose option?: no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): did not try, but it looks so deterministic, that I think I would reproduce it

**Comment by fujiwarat** [comment] 2018-05-15 08:53
Duplicate of #1943 
It would be better to ask ibus-libpinyin to provide the customized keymap.

**Closed by fujiwarat** 2018-05-15 08:53 UTC
