### ISSUE TITLE
Ibus-Anthy no longer working with several KDE/Qt applications

### ISSUE THREAD

**Issue by jogojapan** [ibus/ibus#2139] opened 2019-10-06 04:38 UTC
Please fill in the following items if you don't know the root cause.

**Which distribution and version?:** Fedora 29 and Fedora 30

**Which desktop environment and version?:** KDE Plasma 5.15.5, KDE Frameworks 5.59.0, Qt 5.12.4

**Which session type?:**
X11

**Which application and version?:**
Konsole 19.04.2

**IBus version?:**
1.5.19-17 and 1.5.20

**Issue description:**
* I was on F29, and as part of a regular "dnf update", ibus was upgraded from 1.5.19-16 to 1.5.19-17. After that, I could not longer activate "Anthy" in Konsole and Skrooge, while in XTerm and Firefox it still works.
* I meanwhile upgraded the system to F30 (Ibus 1.5.20), and it's not working there either.

**Steps to reproduce:**
1. Open Konsole
1. Try switching to Japanese/Hiragana using Hankaku_Zenkaku key--no effect
1. Open Firefox
1. Try switching to Japanese using Hankaku_Zenkaku key--works as expected

**Can you reproduce your problem when you restart ibus-daemon? (yes / no): **
Yes, no difference

**Do you see any errors when you run ibus-daemon with the verbose option?:**
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

No error messages displayed.

**Can you reproduce your problem with a new user account instead of the current your account? (yes / no):**

Haven't tried yet.

**Comment by fujiwarat** [comment] 2019-10-07 05:27
I cannot reproduce your problem in Plasma 5.15.5 in Fedora 30.
Did you set `QT_IM_MODULE`?
```
% echo $QT_IM_MODULE
ibus
```
Did you try `kwrite`?

Can you grep platforminputcontexts with `strace kate`?
```
% strace kate |& grep platforminputcontexts
```

**Comment by jogojapan** [comment] 2019-10-07 07:00
Thanks a lot for looking into this.

Yes, `$QT_IM_MODULE` is set correctly:

    % echo $QT_IM_MODULE
    ibus

I just tried `kwrite`, and there Anthy also doesn't work.

The output of `strace kate |& grep platforminputcontexts` is empty.

**Comment by fujiwarat** [comment] 2019-10-08 12:05
Sorry, `kate` was my typo.
Please try `strace kwrite |& grep platforminputcontexts` instead.

**Comment by jogojapan** [comment] 2019-10-08 22:01
Ah, I see. Here is the output:

    access("/usr/lib64/qt5/plugins/platforminputcontexts/.", F_OK) = 0
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 6
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=65512, ...}) = 0
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=296152, ...}) = 0
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=162816, ...}) = 0
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    lstat("/usr/lib64/qt5/plugins/platforminputcontexts/libqtvirtualkeyboardplugin.so", {st_mode=S_IFREG|0755, st_size=62688, ...}) = 0
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libqtvirtualkeyboardplugin.so", O_RDONLY|O_CLOEXEC) = 6
    access("/usr/bin/platforminputcontexts/.", F_OK) = -1 ENOENT (No such file or directory)
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY) = 11
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY) = 11
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY) = 11
    openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY) = 11

**Comment by fujiwarat** [comment] 2019-10-09 09:47
My understanding is, you cannot activate Hiragana mode with both Zenkaku_Hankaku key and clicking "Hiragana" on panel menu, right?

I still wonder if you really used 1.5.19-17.fc29.

Could you attach the output of `env G_DBUS_DEBUG=all ibus-daemon --xim` when you run `kate` after you run `ibus exit`?

**Comment by jogojapan** [comment] 2019-10-11 22:46
It was 1.5.19-17.fc29 according to `dnf history list`, but other applications were also updated along with the update from -16 to -17, so it might be a side effect of something else.

I am attaching the output of `env G_DBUS_DEBUG=all ibus-daemon --xim`. The last 24 lines were produced after starting Kate. I also pressed Zenkaku_Hankaku in Kate (to no effect) and typed a few things.

Your understanding is correct, I cannot activate Hiragana mode, neither by pressing Zenkaku_Hankaku, no by clicking "Hiragana" from the menu.

[debug_output.txt](https://github.com/ibus/ibus/files/3719833/debug_output.txt)

**Comment by gunnarhj** [comment] 2019-10-14 08:38
@fujiwarat: Isn't this just a variant of #2137? The issue due to the CVE patch shows up sometimes also on KDE, such as last time I checked my Kubuntu installation.

**Comment by fujiwarat** [comment] 2019-10-15 13:05
Thank you. I confirmed #2137 in your log while I don't reproduce the issue in Fedora 30 Plasma desktop.
ibus-1.5.20-4.fc30 does not include the patch.
I think when you run `ibus restart` several times, your applications sometimes succeed to connect to ibus-daemon but sometimes fail to connect to ibus-daemon.

**Comment by fujiwarat** [comment] 2019-10-15 13:05
Duplicate of #2137

**Closed by fujiwarat** 2019-10-15 13:05 UTC
