### ISSUE TITLE
[Feature Request] enhance about different application use different Input Method

### ISSUE THREAD

**Issue by hosxy** [ibus/ibus#2166] opened 2019-12-23 09:00 UTC
Just diasble `share the same input method among all applications`,ibus can use different input methods on different applications,eg:
![ibus](https://user-images.githubusercontent.com/17108640/71345778-35280900-25a1-11ea-8acf-545557c2a486.png)
But it have some disadvantage, it is only effective  on different input method,like libpinyin and EN(English input method)，however libpinyin also have two input  status: Chinese and English,but Chinese and English input status on libpinyin can't use this feature. So I have to switch input methods frequently to use this feature. 
Why not consider supporting this feature on different input status on a input method. it will be convenient, because  I have to press two key to switch input methods,and on libpinyin I only have press one key to switch Chinese and English status.
 And I think different input status on a input method can be regarded as different input method

**Comment by fujiwarat** [comment] 2019-12-25 08:17
Duplicate of #1679

**Closed by fujiwarat** 2019-12-25 08:17 UTC
