### ISSUE TITLE
ibus not dealing some unicode charaters properly

### ISSUE THREAD

**Issue by alkemyst** [ibus/ibus#2658] opened 2024-06-26 14:54 UTC
## OS
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

## Kernel
Linux mo 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## Locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=it_CH.UTF-8
LC_TIME=en_CH.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=it_CH.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=it_CH.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=it_CH.UTF-8
LC_TELEPHONE=it_CH.UTF-8
LC_MEASUREMENT=it_CH.UTF-8
LC_IDENTIFICATION=it_CH.UTF-8
LC_ALL=

## Which session type?:
x11

## Which application and version?: 
konsole

## Issue description:
If I map the keys of the keyboard to some codes, the XCompose seem to work partially. To other codes it does not work

## Steps to reproduce:
1. create the following .XCompose
```
<Multi_key> <Armenian_AYB> <a> : "z"
<Multi_key> <o> <o> : "z"
<Multi_key> <U1014B> <a> : "z"
<Multi_key> <U1D552> <a> : "z"
<U1D552> <a> : "z"
<Multi_key> <Greek_alpha> : "z"
```

2. create a file called current_xkb_config.xkb with the content of this file
[current_xkb_config.txt](https://github.com/user-attachments/files/15990952/current_xkb_config.txt)

3. setup the new keyboard that loads special characters on shift 3--6
```
    key <AE03> {         [               3,     Greek_alpha ] };
    key <AE04> {         [               4,    Armenian_AYB ] };
    key <AE05> {         [               5,          U1014B ] };
    key <AE06> {         [               6,          U1D552 ] };
```

4. restart ibus and load the new keyboard
```
ibus restart
sleep 2
xkbcomp current_xkb_config.xkb $DISPLAY
```

as a result, some combinations work, some do not:
compose -> shift+3 = z (correct)
compose -> shift+4  a = a (wrong)
compose -> shift+5 a = a (wrong)
compose -> shift+6 a = z (right)
shift+6 -> a = 𝕒z (wrong)

note that the keys are correctly loaded:
shift+4 = Ա (correct)
shift+5 = 𐅋 (correct)
shift+6 = 𝕒 (would be correct, if I did not use it for a Compose)

## Can you reproduce your problem with a new user account instead of the current your account?
yes: I created one new for this test

I can run C debugging, and I am willing to help, but I do not know where to start, even to compile it

**Comment by mike-fabian** [comment] 2024-06-27 14:42
All of these work for me, I tried both with ibus and with ibus-typing-booster (which has it's own compose support).

I have these versions: ibus-1.5.30-5.fc40.x86_64 ibus-typing-booster-2.25.9-3.fc40.noarch

My guess is there is something wrong with your custom keyboard layout. I got some errors when trying to use that.

Therefore,  I made a variant of my personal layout to put the same 4 characters on the same 4 keys as you do:

```
mfabian@hathi:/usr/share/X11/xkb/symbols
$ diff -u mike custom 
--- mike	2024-02-13 22:25:09.329571093 +0100
+++ custom	2024-06-27 16:12:53.789624630 +0200
@@ -26,13 +26,13 @@
         // U+030B COMBINING DOUBLE ACUTE ACCENT
         key <AE02> { [ 2, at, twosuperior, U030B ] }; // 2 @ ² ̋
         // U+0304 COMBINING MACRON
-        key <AE03> { [ 3, numbersign, threesuperior, U0304 ] }; // 3 # ³ ̄
+        key <AE03> { [ 3, Greek_alpha, threesuperior, U0304 ] }; // 3 # ³ ̄
         // U+030A COMBINING RING ABOVE
-        key <AE04> { [ 4, dollar, EuroSign, U030A ] }; // 4 $ € ̊
+        key <AE04> { [ 4, Armenian_AYB, EuroSign, U030A ] }; // 4 $ € ̊
         // U+030A COMBINING RING ABOVE
-        key <AE05> { [ 5, percent, EuroSign, U030A ] }; // 5 % € ̊
+        key <AE05> { [ 5, U1014B, EuroSign, U030A ] }; // 5 % € ̊
         // U+0302 COMBINING CIRCUMFLEX ACCENT
-        key <AE06> { [ 6, asciicircum, dead_circumflex, U0302 ] }; // 6 ^ dead_circumflex ̂
+        key <AE06> { [ 6, U1D552, dead_circumflex, U0302 ] }; // 6 ^ dead_circumflex ̂
         // U+031B COMBINING HORN
         key <AE07> { [ 7, ampersand, onehalf, U031B ] }; // 7 & ½ ̛
         // U+0328 COMBINING OGONEK
mfabian@hathi:/usr/share/X11/xkb/symbols
$ 
```

My personal keyboard layout is in the file `mike`, the changed one with your keys on `Shift+3|4|5|6` is in the file `custom`.

(Both my personal layout and the `custom` layout have  the compose key (`Multi_key`) on `PrtSc`.)

ibus can use a keyboard layout saved to a file named `/usr/share/X11/xkb/symbols/custom` by default, after putting the `custom` file there ibus needs to be restarted (`ibus restart`) (or restart your session).

Then ibus should list it:

```
mfabian@hathi:/usr/share/X11/xkb/symbols
$ ibus list-engine | grep custom
  xkb:custom::und - A user-defined custom Layout
mfabian@hathi:/usr/share/X11/xkb/symbols
$ 
```

and you can use `ibus-setup` (when not using Gnome) or the Gnome control center to add that keyboard layout.

Then I have added this to my `~/.XCompose` file:

```
mfabian@hathi:/usr/share/X11/xkb/symbols
$ tail -7 ~/.XCompose

<Multi_key> <Armenian_AYB> <a> : "zArmenian_AYB"
<Multi_key> <o> <o> : "zoo"
<Multi_key> <U1014B> <a> : "zU1014B"
<Multi_key> <U1D552> <a> : "zU1D552"
<U1D552> <a> : "zU1D552-wihout-Multi"
<Multi_key> <Greek_alpha> : "zGreek_alpha"
mfabian@hathi:/usr/share/X11/xkb/symbols
$ 

```

I made the expansions a little longer than just `z` to see more easily what expansion happened.

After changing the `~/.XCompose` file, ibus needs to be restarted to read the new compose data.

Now I can switch to the `custom` keyboard layout using `Super+Space` or the input method menu.

When I switch to the `custom` layout I can use all these compose sequences, they all work without problems.

I can also switch to the `custom` layout and then to ibus-typing-booster. If I type then, the compose support in ibus-typing-booster not the one from ibus is used. That works as well.

So I think everything works fine, something is wrong on your side, either the keyboard layout, or the `~/.XCompose` file, or you forgot to restart ibus when the layout or the compose file changed or your version of ibus is too old.

What version of ibus do you have?

For your reference I attach the `/usr/share/X11/xkb/symbols/custom` file I used for testing here (gzipped as `custom.gz`):

[custom.gz](https://github.com/user-attachments/files/16015773/custom.gz)

You can try that `custom` layout and if that works the problem is your layout.

**Comment by mike-fabian** [comment] 2024-06-27 15:13
In ibus there have been some improvements in the compose support recently, for example this one, which is not even in ibus-1.5.30 (but added by patches to the Fedora 40 package):
https://github.com/fujiwarat/ibus/commit/e7329cb14de4097ca894ce19d1903a7df28acd78

I have not tested yet whether your compose file works with ibus-1.5.29, I might do that later tonight.

As there have not been changes in the compose support in ibus-typing-booster recently, if you try with ibus-typing-booster it should certainly work. If even that does not work, then I really guess it is your layout.

**Comment by mike-fabian** [comment] 2024-06-27 15:14
As ibus-typing-booster does not choose the keyboard layout, choose the keyboard layout first, then switch to ibus-typing-booster, then test the compose sequences.

**Comment by alkemyst** [comment] 2024-06-27 15:17
Great! Thanks: I'll test it ASAP. How do I switch from ibus to ibus-typing-booster ?

**Comment by mike-fabian** [comment] 2024-06-27 20:16
ibus-typing-booster is one of many available input methods using ibus. So you use ibus, and then add ibus-typing-booster. Wenn using Gnome, you add an input source using the Gnome control centre, when using something else than Gnome you use `ibus-setup`.

It  is described here:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/

See the chapter "Adding ibus-typing-booster to your desktop".

**Comment by mike-fabian** [comment] 2024-06-27 20:55
It would be nice if a ibus-1.5.31 release with all patches needed for this could be released soon so that other distributions like Ubuntu can pick it up.

**Comment by alkemyst** [comment] 2024-06-28 08:11
Hi Mike,
I compiled ibus with the release tgz 1.5.30, but I still get the bug. If you tell me which patches to include, I can try to build a 1.5.31 version locally.

**Comment by mike-fabian** [comment] 2024-06-28 08:28
I am pretty sure that this patch is necessaary https://github.com/fujiwarat/ibus/commit/e7329cb14de4097ca894ce19d1903a7df28acd78
but maybe others as well.

I have tested the ibus on Fedora 40, the sources for that are here:

https://src.fedoraproject.org/rpms/ibus/tree/f40

There are 3 patches.

You can ignore https://src.fedoraproject.org/rpms/ibus/blob/f40/f/ibus-xx-desktop-testing-mutter.patch because it is not applied on Fedora 40.

This patch https://src.fedoraproject.org/rpms/ibus/blob/f40/f/ibus-1385349-segv-bus-proxy.patch fixes some segmentation faults but looks unrelated to compose.

This is the important one: https://src.fedoraproject.org/rpms/ibus/blob/f40/f/ibus-HEAD.patch
It is a collection of various patches and also contains https://github.com/fujiwarat/ibus/commit/e7329cb14de4097ca894ce19d1903a7df28acd78

So I think it is very likely that if you build from ibus-1.5.30.tar.gz and apply this https://src.fedoraproject.org/rpms/ibus/blob/f40/f/ibus-HEAD.patch that your problem with compose will be solved.

**Comment by mike-fabian** [comment] 2024-07-01 14:47
And, does it work?

**Comment by alkemyst** [comment] 2024-07-03 20:22
Hi @mike-fabian 
sorry it took a while. Yes, I can confirm that just by adding the [third patch you mentioned](https://src.fedoraproject.org/rpms/ibus/blob/f40/f/ibus-HEAD.patch) on top of IBus 1.5.30, all of the XCompose combinations work flawlessly.

Just for a bit of context, this is very interesting, because it will allow me to add characters like 𝕒 to my keyboard, and then "compose" with letters to form all of the latin characters with double stroke, then do the same with math bold, fraktur, etc.

Thanks a lot!

Of course I concur that having this patch in the next release would be great :-)

**Comment by mike-fabian** [comment] 2024-07-04 07:19
@fujiwarat So your latest patches for ibus already fix everything reported here.

**Comment by fujiwarat** [comment] 2024-08-02 13:47
Duplicate of #2646

**Closed by fujiwarat** 2024-08-02 13:47 UTC
