### ISSUE TITLE
ibus-x11 crashes

### ISSUE THREAD

**Issue by ncfavier** [ibus/ibus#2513] opened 2023-05-27 13:03 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
NixOS unstable

Which desktop environment and version?: 
None

Which session type?: 
X11

Which application and version?: 
alacritty 0.12.1

IBus version?: 
1.5.28

Issue description:
`ibus-x11` suddenly crashes while I'm typing, which freezes alacritty.

<details>
<summary>**Core dump**</summary>

```
May 27 14:57:27 no systemd-coredump[1074434]: Process 3704046 (.ibus-x11-wrapp) of user 1000 dumped core.
                                              
                                              Module libcap.so.2 without build-id.
                                              Module libsystemd.so.0 without build-id.
                                              Module libbrotlicommon.so.1 without build-id.
                                              Module libpcre.so.1 without build-id.
                                              Module libGLX.so.0 without build-id.
                                              Module libXdmcp.so.6 without build-id.
                                              Module libXau.so.6 without build-id.
                                              Module libGLdispatch.so.0 without build-id.
                                              Module libdatrie.so.1 without build-id.
                                              Module libxml2.so.2 without build-id.
                                              Module libjson-glib-1.0.so.0 without build-id.
                                              Module libdbus-1.so.3 without build-id.
                                              Module libatspi.so.0 without build-id.
                                              Module libexpat.so.1 without build-id.
                                              Module libbrotlidec.so.1 without build-id.
                                              Module libbz2.so.1 without build-id.
                                              Module libpcre2-8.so.0 without build-id.
                                              Module libffi.so.8 without build-id.
                                              Module libselinux.so.1 without build-id.
                                              Module libjpeg.so.62 without build-id.
                                              Module libGL.so.1 without build-id.
                                              Module libXrender.so.1 without build-id.
                                              Module libxcb-render.so.0 without build-id.
                                              Module libxcb.so.1 without build-id.
                                              Module libxcb-shm.so.0 without build-id.
                                              Module libpng16.so.16 without build-id.
                                              Module libEGL.so.1 without build-id.
                                              Module libgraphite2.so.3 without build-id.
                                              Module libfreetype.so.6 without build-id.
                                              Module libthai.so.0 without build-id.
                                              Module libXinerama.so.1 without build-id.
                                              Module libXrandr.so.2 without build-id.
                                              Module libXcomposite.so.1 without build-id.
                                              Module libXdamage.so.1 without build-id.
                                              Module libXcursor.so.1 without build-id.
                                              Module libXext.so.6 without build-id.
                                              Module libxkbcommon.so.0 without build-id.
                                              Module libtracker-sparql-3.0.so.0 without build-id.
                                              Module libatk-bridge-2.0.so.0 without build-id.
                                              Module libXi.so.6 without build-id.
                                              Module libepoxy.so.0 without build-id.
                                              Module libfribidi.so.0 without build-id.
                                              Module libfontconfig.so.1 without build-id.
                                              Module libpangoft2-1.0.so.0 without build-id.
                                              Module libXfixes.so.3 without build-id.
                                              Module libX11.so.6 without build-id.
                                              Module libatk-1.0.so.0 without build-id.
                                              Module libharfbuzz.so.0 without build-id.
                                              Module libpango-1.0.so.0 without build-id.
                                              Module libpangocairo-1.0.so.0 without build-id.
                                              Module libz.so.1 without build-id.
                                              Module libibus-1.0.so.5 without build-id.
                                              Module .ibus-x11-wrapped without build-id.
                                              Stack trace of thread 3704046:
                                              #0  0x00007f97cbe31adc __pthread_kill_implementation (libc.so.6 + 0x87adc)
                                              #1  0x00007f97cbde2cb6 raise (libc.so.6 + 0x38cb6)
                                              #2  0x00007f97cbdcc8ba abort (libc.so.6 + 0x228ba)
                                              #3  0x00007f97cbdcd5f5 __libc_message.cold (libc.so.6 + 0x235f5)
                                              #4  0x00007f97cbe3b785 malloc_printerr (libc.so.6 + 0x91785)
                                              #5  0x00007f97cbe3d4b2 _int_free (libc.so.6 + 0x934b2)
                                              #6  0x00007f97cbe3fe83 free (libc.so.6 + 0x95e83)
                                              #7  0x00007f97cbfe0ef9 XFree (libX11.so.6 + 0x48ef9)
                                              #8  0x000000000040eb08 _Xi18nMessageHandler (.ibus-x11-wrapped + 0xeb08)
                                              #9  0x0000000000408da3 WaitXIMProtocol (.ibus-x11-wrapped + 0x8da3)
                                              #10 0x00007f97cc78b066 _gdk_x11_display_queue_events (libgdk-3.so.0 + 0x98066)
                                              #11 0x00007f97cc72e3c0 gdk_display_get_event (libgdk-3.so.0 + 0x3b3c0)
                                              #12 0x00007f97cc78aec2 gdk_event_source_dispatch (libgdk-3.so.0 + 0x97ec2)
                                              #13 0x00007f97cc139dbd g_main_context_dispatch (libglib-2.0.so.0 + 0x5ddbd)
                                              #14 0x00007f97cc13a068 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x5e068)
                                              #15 0x00007f97cc13a31f g_main_loop_run (libglib-2.0.so.0 + 0x5e31f)
                                              #16 0x00007f97cd104e8c ibus_main (libibus-1.0.so.5 + 0x3fe8c)
                                              #17 0x0000000000403b37 main (.ibus-x11-wrapped + 0x3b37)
                                              #18 0x00007f97cbdcdace __libc_start_call_main (libc.so.6 + 0x23ace)
                                              #19 0x00007f97cbdcdb89 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x23b89)
                                              #20 0x0000000000403d15 _start (.ibus-x11-wrapped + 0x3d15)
                                              
                                              Stack trace of thread 3704064:
                                              #0  0x00007f97cbea9d8d syscall (libc.so.6 + 0xffd8d)
                                              #1  0x00007f97cc19390f g_cond_wait (libglib-2.0.so.0 + 0xb790f)
                                              #2  0x00007f97cc10401b g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x2801b)
                                              #3  0x00007f97cc166cd2 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x8acd2)
                                              #4  0x00007f97cc16668d g_thread_proxy (libglib-2.0.so.0 + 0x8a68d)
                                              #5  0x00007f97cbe2fe24 start_thread (libc.so.6 + 0x85e24)
                                              #6  0x00007f97cbeb19b0 __clone3 (libc.so.6 + 0x1079b0)
                                              
                                              Stack trace of thread 3704069:
                                              #0  0x00007f97cbea477f __poll (libc.so.6 + 0xfa77f)
                                              #1  0x00007f97cc139fde g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x5dfde)
                                              #2  0x00007f97cc13a31f g_main_loop_run (libglib-2.0.so.0 + 0x5e31f)
                                              #3  0x00007f97cc3a6946 gdbus_shared_thread_func (libgio-2.0.so.0 + 0x122946)
                                              #4  0x00007f97cc16668d g_thread_proxy (libglib-2.0.so.0 + 0x8a68d)
                                              #5  0x00007f97cbe2fe24 start_thread (libc.so.6 + 0x85e24)
                                              #6  0x00007f97cbeb19b0 __clone3 (libc.so.6 + 0x1079b0)
                                              
                                              Stack trace of thread 3704067:
                                              #0  0x00007f97cbea477f __poll (libc.so.6 + 0xfa77f)
                                              #1  0x00007f97cc139fde g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x5dfde)
                                              #2  0x00007f97cc13a0fc g_main_context_iteration (libglib-2.0.so.0 + 0x5e0fc)
                                              #3  0x00007f97cc13a141 glib_worker_main (libglib-2.0.so.0 + 0x5e141)
                                              #4  0x00007f97cc16668d g_thread_proxy (libglib-2.0.so.0 + 0x8a68d)
                                              #5  0x00007f97cbe2fe24 start_thread (libc.so.6 + 0x85e24)
                                              #6  0x00007f97cbeb19b0 __clone3 (libc.so.6 + 0x1079b0)
                                              ELF object binary architecture: AMD x86-64
```

`.ibus-x11-wrapped` here refers to the actual `ibus-x11` executable; NixOS uses wrapper scripts to set environment variables.
</details>

Steps to reproduce:
No idea.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): happens randomly
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): I don't know

**Comment by fujiwarat** [comment] 2023-05-29 06:18
Duplicate of #2484

**Closed by fujiwarat** 2023-05-29 06:18 UTC
