### ISSUE TITLE
XCompose | Can't type certain compose sequences in urxvt

### ISSUE THREAD

**Issue by Shamaoke** [ibus/ibus#2460] opened 2022-11-17 02:33 UTC
Which distribution and version?:
Arch Linux

Which desktop environment and version?:
Openbox 3.6.1

Which session type?: 
X11

Which application and version?:
urxvt 9.30 and various console applications running in it (Vim, etc.)
Other programs (Firefox, etc.) seems working fine.

IBus version?: 
ibus 1.5.27
The program is run with `ibus-daemon -drx`.

Issue description:
After the latest system update certain compose sequences have ceased to work. Among these keyboard sequences are en-dashes and em-dashes.

Steps to reproduce:
I. en-dash
1. Type `<Compose>`, `<minus>`, `<minus>`, `<period>`;
2. Observe that nothing has been printed to the terminal.

II. em-dash
1. Type `<Compose>`, `<minus>`, `<minus>`, `<minus>`;
2. Observe that nothing has been printed to the terminal.

Can you reproduce your problem when you restart ibus-daemon?
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
Nothing is outputted after I type the compose sequences.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I think, this is irrelevant to the problem.

**Comment by mike-fabian** [comment] 2022-11-17 09:41
I cannot reproduce this on Fedora 37 running the i3 window manager (Xorg) using rxvt-unicode-9.30-4.fc37.x86_64.

It works for me both when selecting a plain keyboard layout (then I am using the Compose support in ibus) and when I use ibus-typing-booster (then I am using the Compose support in ibus-typing-booster). 

> Which application and version?:
> urxvt 9.30 and various console applications running in it (Vim, etc.)
> Other programs (Firefox, etc.) seems working fine.

urvxt is a traditional X11 program, Firefox uses Gtk.

Can you reproduce this also in other X11 programs like xterm?

I cannot reproce this in xterm either, both compose sequences you mention always work for me.

You say that some Compose sequences work but some don’t?

Which locale are you running in?

Do you have a ~/.XCompose file?

**Comment by Shamaoke** [comment] 2022-11-19 03:22
> I cannot reproduce this on Fedora 37

The current version of the X.Org server in Arch is 21.1.4. As far as I understand, Fedora 37 has a different version of it. Perhaps, the problem occurs in the last release version of the server?

> Can you reproduce this also in other X11 programs like xterm?

Yes, I can. I got nothing when typing the compose sequences in xterm.

> You say that some Compose sequences work but some don’t?

The most of them does work. In the past, I have encountered a situation when some rare used compose sequences didn't work. I don't remember what ones they were. But now, after the update, the dashes stopped working.

> Which locale are you running in?

````
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
````

> Do you have a ~/.XCompose file?

Yes, I have it. Deleting it and rebooting the machine doesn't affect the situation in any way.

**Comment by ShimmerFairy** [comment] 2022-11-19 07:46
I have noticed this same problem with emacs, and double-checked in urxvt to make sure. I can't type characters like the em dash (—), but I can in GTK and Qt programs. On the other hand, there are plenty of others I can type, like « or ☺.

I'm on ibus 1.5.27, and I didn't update or recompile it between boots, so it must've been some change in a dependency. After poking around in my gentoo logs, these are the direct dependencies that changed in-between my last (working) boot, and when problems started appearing:

```
gentoo package         previous      current
--------------------------------------------
app-text/iso-codes     4.11.0     -> 4.12.0
dev-libs/glib          2.74.0-r1  -> 2.74.1-r1
gnome-base/librsvg     2.54.5     -> 2.55.1
x11-libs/libX11        1.8.1      -> 1.8.2
x11-libs/gtk+          2.24.33-r1 -> 2.24.33-r2
gui-libs/gtk           4.8.1-r1   -> 4.8.2
dev-lang/python        3.9.14     -> 3.9.15_p3
dev-lang/python        3.10.7     -> 3.10.8_p3
dev-util/glib-utils    2.74.0     -> 2.74.1
app-i18n/unicode-cldr  40.0       -> 42.0
app-i18n/unicode-emoji 14.0       -> 15.0
sys-devel/gettext      0.21-r4    -> 0.21.1
```

I don't know how to narrow down the possible culprit further, I just know that I haven't changed ibus or my own compose files since the last time it worked.

By the way, the issue the other commenter mentioned having in the past is probably #2422 , which I also had problems with. For what it's worth, the package that installs the XLC_LOCALE files mentioned there was also updated between boots for me (from 1.8.1 to 1.8.2), so it could possibly be the same issue again.

**Comment by Shamaoke** [comment] 2022-11-20 03:58
> By the way, the issue the other commenter mentioned having in the past is probably https://github.com/ibus/ibus/issues/2422 , which I also had problems with. For what it's worth, the package that installs the XLC_LOCALE files mentioned there was also updated between boots for me (from 1.8.1 to 1.8.2), so it could possibly be the same issue again.

I have that package updated as well.

<details>
<summary>`pacman -Qi libx11`</summary>

````
Name            : libx11
Version         : 1.8.2-2
Description     : X11 client-side library
Architecture    : x86_64
URL             : https://xorg.freedesktop.org/
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : libxcb  xorgproto
Optional Deps   : None
Required By     : aalib  ardour  at-spi2-core  cairo  ffmpeg  ffmpeg4.4  fltk  lib32-libx11  libva  libwmf  libxext  libxfixes  libxkbfile  libxrender  libxt  lirc  mplayer  mpv  ntk  sdl2  startup-notification  virtualbox  vulkan-intel  webkit2gtk  webkit2gtk-4.1  xkb-switch-git  xorg-x11perf  xorg-xcmsdb  xorg-xcursorgen  xorg-xdpyinfo  xorg-xdriinfo  xorg-xev  xorg-xgamma  xorg-xhost  xorg-xinit  xorg-xinput  xorg-xkbutils  xorg-xkill  xorg-xmodmap  xorg-xpr  xorg-xprop  xorg-xrandr  xorg-xrdb  xorg-xrefresh  xorg-xsetroot  xorg-xvinfo  xorg-xwud
Optional For    : hwloc  suil
Conflicts With  : None
Replaces        : None
Installed Size  : 10.04 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Thu 17 Nov 2022 07:22:34 PM MSK
Install Date    : Fri 18 Nov 2022 03:15:21 AM MSK
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
````

</details>

**Comment by Shamaoke** [comment] 2022-11-20 04:11
I have discovered another character that I can no longer enter either using a compose sequence or using the direct unicode input method. It's the bullet character `•` (U+2022).

**Comment by mike-fabian** [comment] 2022-11-20 19:13
So we know so far that this seems to affect programs using ibus via XIM:

- urvxt, xterm, emacs.

**Comment by mike-fabian** [comment] 2022-11-20 19:19
> I have discovered another character that I can no longer enter either using a compose sequence or using the direct unicode input method. It's the bullet character `•` (U+2022).

That the bullet character `•` (U+2022) is also affected makes me guess this is the same issue as:

https://github.com/ibus/ibus/issues/2422

**Comment by mike-fabian** [comment] 2022-11-20 19:25
But you are using ibus 1.5.27 and that should already contain a patch which fixes   https://github.com/ibus/ibus/issues/2422

**Comment by mike-fabian** [comment] 2022-11-20 19:32
> By the way, the issue the other commenter mentioned having in the past is probably #2422 , which I also had problems with. For what it's worth, the package that installs the XLC_LOCALE files mentioned there was also updated between boots for me (from 1.8.1 to 1.8.2), so it could possibly be the same issue again.

libX11 1.8.2 should contain my patch

https://gitlab.freedesktop.org/xorg/lib/libx11/-/commit/dc553ff908f10832c71dc2b5ba5af7e68589218e

which also should solve the problem.

I.e. having at least one of ibus >= 1.5.27 or libX11 >= 1.8.2 *should* solve the problem.

**Comment by mike-fabian** [comment] 2022-11-20 19:34
Can you check whether using LC_CTYPE=ja_JP.UTF-8 (or any other CJK locale), globally or just for ibus, works around the problem?

If yes, it would be another hint that this is the same as https://github.com/ibus/ibus/issues/2422

**Comment by mike-fabian** [comment] 2022-11-20 19:37
Also, can you check what is in your `/usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE` file? 

If you already have the fixed XLC_LOCALE file, you should *not* find

```
#       cs6 class
cs6     {
        side            GR
        length          1
        ct_encoding     KOI8-R:GR
}
```

in there, there should be no KOI8-R anymore in that file.

**Comment by mike-fabian** [comment] 2022-11-21 19:47
> Can you check whether using LC_CTYPE=ja_JP.UTF-8 (or any other CJK locale), globally or just for ibus, works around the problem?
> 
> If yes, it would be another hint that this is the same as #2422

You can try this by doing:

```
ibus exit
LC_ALL=ja_JP.UTF-8 ibus-daemon -drx
```

and then test whether the problem  is still there.

**Comment by mike-fabian** [comment] 2022-11-29 06:15
@ShimmerFairy @Shamaoke Is the problem still reproducible for you? If yes, can you check my last two comments?

**Comment by Shamaoke** [comment] 2022-11-30 12:07
@mike-fabian Sorry for the long response.

__1.__

> Also, can you check what is in your /usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE file?

The file doesn't contain the whole `cs6` block. The `cs5` block is immediately followed by the `cs7` block.

__2.__

````
ibus exit
LC_ALL=ja_JP.UTF-8 ibus-daemon -drx
````

I tried the command, but unfortunately without a positive result. The bug still here.

__3.__

If it has any matter, I'd like to add that I have the __Anthy__  input method installed in addition to the __English (US)__ input method.

**Comment by mike-fabian** [comment] 2022-12-06 17:13
Maybe this fixes the problem?:
https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/174
https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/167

**Comment by fujiwarat** [comment] 2022-12-08 12:22
Right. it is the regression of libX11 and now it's fixed in upstream.
You could modify /usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE directly likes the upstream patch.

Unfortunately the ibus change does not help this issue because Xutf8TextListToTextProperty() returns 0 == the succeeded value but the compose text is "" with the regression and ibus-x11 checks the return value.

**Closed** 2022-12-08 12:24 UTC
Labels: Type-Defect, OpSys-All, Priority-High, ibus, xorg

**Comment by Shamaoke** [comment] 2022-12-17 03:46
I can confirm that in `libx11 1.8.3` the problem was solved.
