### ISSUE TITLE
Build failures in commit 160d3c975af91eea6b8271b757be769b8ceef98d

### ISSUE THREAD

**Issue by ebassi** [ibus/ibus#1865] opened 2016-06-21 10:19 UTC
There's no `emoji-list.html` file in the Git repository; did you perhaps forgot to add it?

This is causing a build failure in GNOME Continuous:

```
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -DG_LOG_DOMAIN=\"IBUS\" -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DIBUS_CACHE_DIR=\""/var/cache/ibus"\" -DIBUS_DATA_DIR=\"/usr/share/ibus\" -DIBUS_DISABLE_DEPRECATION_WARNINGS -DIBUS_COMPILATION -DISOCODES_PREFIX=\"/usr\" -DX11_DATA_PREFIX=\"/usr\"  -DENABLE_EMOJI_DICT  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/usr/include/libxml2   -O2 -g -m64 -mtune=generic -MT emoji_parser-emoji-parser.o -MD -MP -MF .deps/emoji_parser-emoji-parser.Tpo -c -o emoji_parser-emoji-parser.o `test -f 'emoji-parser.c' || echo './'`emoji-parser.c
make[4]: *** No rule to make target 'emoji-list.html', needed by 'emoji.dict'.  Stop.
make[4]: *** Waiting for unfinished jobs....
```

**Comment by fujiwarat** [comment] 2016-06-22 02:38
Sorry for the build error.
We use git-cl for the IBus code reviews but git-cl have the limitation of the committed file size.
I'm working on pull #1864 and thinking the better solution for the big size.
Could you wget http://unicode.org/emoji/charts/emoji-list.html in ibus/src or 'configure --disable-emoji-dict' for a few days?

**Comment by ebassi** [comment] 2016-06-22 07:44
I [tagged](https://git.gnome.org/browse/gnome-continuous/commit/?id=a074a3472d252917d19c1222211f81ce3aa17f3c) IBus in Continuous before I opened this issue, when I thought it was a non-srcdir build related failure. If the issue is transient, I can keep the tag until #1864 is solved.

**Comment by cgwalters** [comment] 2016-06-23 12:04
GContinuous cares about reproducibility in the same way any serious buildsystem (whether that's RPM/dpkg or Yocto or whatever).  Downloading random files (particularly over http:// with no security) outside of the control of the buildsystem harms reproducibility.

There are a few strategies here:
 - Fix the review bot (5MB isn't really that big...and I bet gzip compressing it would cause the review bot to treat it as binary)
 - Split it out into a separate git repository that's a build dependency

**Comment by ebassi** [comment] 2016-06-23 13:09
An additional option is to commit to the Git repository the result of the HTML processing file, and only update the HTML locally, on release — similarly to how GTK+ resynchronises its compose tables and key symbols from X11.

**Comment by cgwalters** [comment] 2016-06-24 02:39
I'd try gzipping it first since it should be really simple.

**Comment by fujiwarat** [comment] 2016-06-24 02:50
Thank you for the very interesting comments.
Now I agree that downloading files during the build has a problem in the version management while the http repository is managed by git@github.com:ibus/ibus.github.io.git .

The gzip or xz file is about 3MB so it's not so big different against the raw file as the file will be bigger in the future.

I'm thinking the following options:
1. Commit emoji-list.html as the source file in ibus.git without using git-cl as the original suggestion.
2. Commit emoji.dict as the built file in ibus.git
3. Create a new package likes ibus-emoji-dict under github.com/ibus/

BTW, I'm also thinking to port this feature to GtkIMContextSimple in the near future if IBus succeed to works fine with this feature.

@phuang Do you have any suggestions?
I cannot find the bug report repository for git-cl.

**Comment by fujiwarat** [comment] 2016-06-28 07:59
Talking on unicode mailing list.
Now I'm thinking to parse emoji.json from emojione package.

http://unicode.org/pipermail/unicode/2016-June/003766.html
http://unicode.org/pipermail/unicode/2016-June/003771.html

**Comment by fujiwarat** [comment] 2016-07-04 10:51
Created a patch.
https://github.com/fujiwarat/ibus/commit/9a85de7667d75cabf6637caf90dd8a329fbd27eb

**Comment by fujiwarat** [comment] 2016-07-04 10:54
emoji.json is available from https://bugzilla.redhat.com/show_bug.cgi?id=1350700

**Closed** 2016-07-07 03:51 UTC
