### ISSUE TITLE
Unicode keyboard shortcut disabled but it's still being picked up

### ISSUE THREAD

**Issue by hoshsadiq** [ibus/ibus#2244] opened 2020-07-27 09:41 UTC
Environment information: 
```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

$ env | grep -E 'XDG_(SESSION|CURRENT)'
XDG_CURRENT_DESKTOP=pop:GNOME
XDG_SESSION_TYPE=x11

$ ibus version
IBus 1.5.22
```

Which application and version?: 
Any

Issue description:
I've disabled the `Unicode code point` shortcut but it's still being picked up for whatever reason.

Steps to reproduce:
1. run `ibus-setup`
1. Go to Emoji
1. `...` next to `Unicode code point`
1. Delete current shortcut
1. Try Ctrl+Shift+U in any application.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): Not tried yet

**Comment by fujiwarat** [comment] 2020-09-08 01:35
It would be a Pop!_OS issue.
Duplicate of #2163

**Closed by fujiwarat** 2020-09-08 01:35 UTC
