### ISSUE TITLE
Some Keys don't work for keyboard no US since ibus 1.5.29

### ISSUE THREAD

**Issue by webmastercoolspot** [ibus/ibus#2588] opened 2023-12-10 18:28 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Manjaro
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?:  GNOME 45.2
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: Wayland
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: Wine staging GE 8-25
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.29
(Run `ibus version`)

Issue description: Run wine game. Try to bind key that US keyboard not have. Exemple : é / ç / à (French keyboard for my example. 
Bug we can use or keybind this keys. Switch to US layout keyboard and you can bind these key

Revert to ibus 1.5.28 and all working again for temporary fix

Steps to reproduce:
1. Have ibus 1.5.29
1. Run a game in wine that need keybind keyboard
1. Try to keybind specific non english key ( é à ç )
1. Constat that key has no effective

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: i have no test this
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): i don't know but revert ibus version to 1.5.28 solve this problem

**Comment by fujiwarat** [comment] 2023-12-11 06:51
> Try to keybind specific non english key ( é à ç )

How did you bind the non English keys?

**Comment by webmastercoolspot** [comment] 2023-12-11 10:38
I have french layout keyboard (AZERTY) so i can bind this key.

Maybe if you have US layout keyboard (qwerty), try to change layout for azerty (French) for test ?

**Comment by fujiwarat** [comment] 2023-12-12 09:07
If you mean keys on French azerty, it would not be an IBus issue.
I think you don't see your problem with the applications in GNOME.

**Comment by webmastercoolspot** [comment] 2023-12-12 09:48
It's not only french azerty who have problem. It's all non us qwerty who have problem with key not existing in us qwerty keyboard.

If i switch keyboard layout to qwerty in my system, this problem has solved. Or if i downgrade version to ibus 1.58, this problem has solved.

Furtheremore, it's not only wine application who has problem. Other user in Manjaro has this problem with other application and for the moment, the only solution is to downgrade to ibus 1.58.

Other user, same problem with ibus 1.59 :

https://forum.manjaro.org/t/stable-update-2023-12-10-kernels-plasma-phosh-systemd-cinnamon-gnome-libpamac/153045/37

**Comment by fujiwarat** [comment] 2023-12-12 10:12
> Furtheremore, it's not only wine application who has problem. Other user in Manjaro has this problem with other application and for the moment, the only solution is to downgrade to ibus 1.58.
> Other user, same problem with ibus 1.59 :
> https://forum.manjaro.org/t/stable-update-2023-12-10-kernels-plasma-phosh-systemd-cinnamon-gnome-libpamac/153045/37

I don't know which application was used there but I don't see any problems with gnome-text-editor and "de" layout and ibus 1.5.29.
So I think he should clarify the condition.

**Comment by webmastercoolspot** [comment] 2023-12-12 13:56
This user in manjaro forum use Blender application.

I thinks this problem is not in Gnome DE but for another user application in our system

**Comment by fujiwarat** [comment] 2023-12-12 14:25
> This user in manjaro forum use Blender application.

I confirmed Blender works with IBus.
![blender-fujiwara](https://github.com/ibus/ibus/assets/105929/40587cf7-fda2-4aab-a8d6-88453b08af39)

**Comment by webmastercoolspot** [comment] 2023-12-13 01:00
I have made a video for my problem : https://streamable.com/0uetob

But it's only when binding a shortcut in application. Not typing in application.

When i typing in chat, key works. But if i try to bind this key, it doesn't work or if i try to use this keybind who has previously binding, keybind doesn't work

**Comment by fujiwarat** [comment] 2023-12-13 01:14
> But it's only when binding a shortcut in application. Not typing in application.

You should mention your issue at first.

I guess your application does not bind "é à ç " but "209". Previously gnome-shell sent "209" as the bug now we fixed it and send "é à ç " correctly and I guess you encounter your problem.

I guess you encounter your problem in both Wayland and Xorg at present.

**Comment by webmastercoolspot** [comment] 2023-12-13 01:20
So i need to forward this bug to wine developer and/or blender github ?

And i need to keep this bug effective with v1.5.28 until other application do fix this binding bug ?

**Comment by fujiwarat** [comment] 2023-12-13 01:40
It's good to report your issue to your application in Wine.

I'd close this issue later since IBus does not touch the keycode and keysym in GNOME Wayland.
I still think your issue does not depend on IBus version but might GNOME versions.

If you think your issue is caused by ibus, you might like to debug xim_forward_event() in /usr/lib*/ibus-x11 with gdb.

**Comment by Aritty58** [comment] 2023-12-13 21:44
Russian layout doesn't work in games via Wine/Proton with ibus 1.5.29. I noticed it after Fedora 39 release.
ibus restart helps.

**Comment by webmastercoolspot** [comment] 2023-12-14 11:51
Ok good to know i'm not the only one who have this problem.

When you mean restart, you mean to do a systemctl restart ibus ?

In my system Manjaro, i downgrade ibus to version 1.5.28 for solve this problem and hope it will be a fix to wine one day.

**Comment by perl0n** [comment] 2023-12-14 14:13
Hello, 
Same issue with lutris, Steam on Fedora 39 ibus 1.5.2.9 (Gnome/Wayland).
French layout

**Comment by Aritty58** [comment] 2023-12-14 14:31
@webmastercoolspot Command ibus restart in terminal. After starting the game.

**Comment by perl0n** [comment] 2023-12-14 18:20
@Aritty58 Thanks for the tip, command `ibus restart` work for me too

**Comment by fujiwarat** [comment] 2023-12-14 22:50
I think ibus restart is to just unset the current keyboard layout so if you set the layout with Super-space, you will see the problem again.
I think you need to set US layout for your games instead of ibus restart.

**Comment by russulae** [comment] 2023-12-14 23:21
I got the same issue, I think, using Debian, gnome/wayland, and a UK keyboard with caps lock as a compose key.
I saw the problem mostly in libreoffice writer (no issues in a terminal or in gedit) when composing an accentuated character, the character is displayed, but then some keys (delete and backspace, for example) wont work for a while and I've got `ibus_input_context_post_process_key_event: Type 'h' is not supported.` in journalctl
`ibus restart` doesn't solve anything, the compose key doesn't work anymore anywhere while still set up in gnome settings.

**Comment by fujiwarat** [comment] 2023-12-15 00:22
@russulae The compose key issue is different and already fixed in upstream.

**Comment by Aritty58** [comment] 2023-12-15 02:52
@fujiwarat No. Further switching by Super+space works correctly.
One restart of ibus solves the problem until the session is terminated.
This has only manifested itself since 1.5.29.

**Comment by fujiwarat** [comment] 2023-12-15 05:57
> No. Further switching by Super+space works correctly.

That's curious. It might be an issue of `ibus restart` or else.

> Ok... And then how to use game chats!?

I heard the issue happens with the application shortcut keys so you can enable your language layout whenever you use text editor.

I'm interested in the screencast when you get the expected behavior.

**Comment by Bunnysword** [comment] 2023-12-15 12:38
There is a problem with the RU layout. Please fix this.
https://youtu.be/eFnxJtBL5NE

**Comment by fujiwarat** [comment] 2023-12-15 12:48
@Bunnysword 

> https://youtu.be/eFnxJtBL5NE

I don't see any behaviors with game and your language layout. Seems you just move the mouse cursor.

**Comment by Bunnysword** [comment] 2023-12-15 12:59
> I don't see any behaviors with game and your language layout. Seems you just move the mouse cursor.

Please select the ru-layout keyaboard. Select the default ru-layout. Launch the wine\proton game. Try to play on the Russian layout pls.

**Comment by Bunnysword** [comment] 2023-12-15 13:34
> I don't see any behaviors with game and your language layout. Seems you just move the mouse cursor.

https://youtu.be/rLQG26sArJI?si=wKp8OhfS2O9E8eMy

**Comment by fujiwarat** [comment] 2023-12-15 14:08
> Please select the ru-layout keyaboard. Select the default ru-layout. Launch the wine\proton game. Try to play on the Russian layout pls.

Sorry, probably I have no time to setup Wine.

> https://youtu.be/rLQG26sArJI?si=wKp8OhfS2O9E8eMy

It's an interesting movie.

You cannot reproduce your problem with US layout?

I guess a key is expressed with underline if you pressing a key and the underline is hidden if you release the key and the game shows "A...33" when you press 'A' key for 33 seconds for E.g.
I mean your game might handle pre-edit text with the underline using the input method feature.

If that is the behavior, it would be a known issue and fixed in ibus upstream.

I'd like to watch your issue too.

**Comment by Aritty58** [comment] 2023-12-15 16:54
@fujiwarat My demonstration.
This only happens in GNOME and only with ibus 1.5.29.
Restarting ibus works until the session is terminated.
It doesn't happen with the US layout.
https://drive.google.com/file/d/1lWPQp1s0Dw5TG5deGsxGwFS3Rw-Q0Qdt/view?usp=drive_link

**Comment by perl0n** [comment] 2023-12-15 18:04
Hello,
Here's a link to a video where I use Lutris to play Path of Exile
[https://youtu.be/D4nW0HL5vHQ](url)
You can see in the lower left corner of the game a group of flask that are key binded from 1 to 5.
Before running the `ibus restart` command, the bind on my number 2 flask doesn't work, but after the command, the bind on my second flask does.

**Comment by Aritty58** [comment] 2023-12-15 18:16
@perl0n You're running Fedora, aren't you?
Can you test these packages to see if there is a problem?
I can't reproduce.

[ibus-1.5.28.zip](https://github.com/ibus/ibus/files/13688561/ibus-1.5.28.zip)

**Comment by perl0n** [comment] 2023-12-15 18:30
> @perl0n You using Fedora 39? Can you test these packages to see if there is a problem? I can't reproduce.
> 
> [ibus-1.5.28.zip](https://github.com/ibus/ibus/files/13688561/ibus-1.5.28.zip)

Hi,
Yes i'm on Fedora 39.
@webmastercoolspot had test revert with ibus-1.5.28 and that solve the problem (rf first post)

**Comment by webmastercoolspot** [comment] 2023-12-15 18:34
Yes i confirm 

In Manjaro, revert to ibus 1.5.28 solve this problem

**Comment by Aritty58** [comment] 2023-12-15 18:37
I should point out.
The problem also concerns the Belarusian and Ukrainian layouts.

**Comment by Bunnysword** [comment] 2023-12-15 19:16
> @perl0n You using Fedora 39? Can you test these packages to see if there is a problem? I can't reproduce.
> 
> [ibus-1.5.28.zip](https://github.com/ibus/ibus/files/13688561/ibus-1.5.28.zip)

Work! No problem! Perfect work!

**Comment by fujiwarat** [comment] 2023-12-15 23:21
> [ibus-1.5.28.zip](https://github.com/ibus/ibus/files/13688561/ibus-1.5.28.zip)

Do you mean you can reproduce your issue in Fedora 39?

https://bodhi.fedoraproject.org/updates/FEDORA-2023-838b91ccfa

**Comment by Aritty58** [comment] 2023-12-15 23:37
Updated to this version. Yes. The problem is present.
> https://bodhi.fedoraproject.org/updates/FEDORA-2023-838b91ccfa

**Comment by fujiwarat** [comment] 2023-12-15 23:48
Could you please introduce me how to setup Wine and your game in Fedora?

**Comment by fujiwarat** [comment] 2023-12-15 23:58
> @perl0n :
> Same issue with lutris, Steam on Fedora 39 ibus 1.5.2.9 (Gnome/Wayland).

My understanding is it does not require Wine and I will try it later.

**Comment by Aritty58** [comment] 2023-12-16 00:01
It's interesting. Input from "q to ." The input is incorrect in Russian.

![Снимок экрана от 2023-12-16 06-57-58](https://github.com/ibus/ibus/assets/93352572/8b951d4e-d897-4aaa-b8e8-eb5ab0e13583)

**Comment by Aritty58** [comment] 2023-12-16 00:15
@fujiwarat You can use Lutris and Steam. Any game. Excluding native Steam games.

**Comment by fujiwarat** [comment] 2023-12-17 02:44
I'm trying to search a free game with Steam but "Dota 2" and "Counter - Strike 2" needs 14GB which is a big size.
Do you have any ideas?

**Comment by Bunnysword** [comment] 2023-12-17 07:52
> I'm trying to search a free game with Steam but "Dota 2" and "Counter - Strike 2" needs 14GB which is a big size.
> Do you have any ideas?

pls check

https://store.steampowered.com/app/1568590/Goose_Goose_Duck/

**Comment by fujiwarat** [comment] 2023-12-17 09:27
> https://store.steampowered.com/app/1568590/Goose_Goose_Duck/

I think it has Windows and Macintosh marks but not Linux mark and probably I think it does not work in Linux directly.

**Comment by Aritty58** [comment] 2023-12-17 09:44
We use Proton to run Windows games. The problem with games via Proton.
In the native (linux icon) everything is fine.

![Uploading Снимок экрана 2023-12-17 164155.png…]()

**Comment by fujiwarat** [comment] 2023-12-17 12:14
It requires much memory against my VM and I will set up the environment in my host.

**Comment by fujiwarat** [comment] 2023-12-18 23:43
@Aritty58 Thank you. I can play the game with the compatibility setting.

How can I reproduce the issue with the "Goose Goose Duck" game? I played "Classic 1" and "asdw" keys works fine.

**Comment by Aritty58** [comment] 2023-12-19 00:02
@fujiwarat Add Russian layout in gnome-settings. 
Switch the layout to Russian in the game.
You will not be able to move.

https://github.com/ibus/ibus/assets/93352572/7577cd01-a0e3-460c-8f5f-45c320b9f07d

**Comment by fujiwarat** [comment] 2023-12-19 00:39
I think Russian keys should not move the duck and my interesting is the issue after ibus restart.

**Comment by Aritty58** [comment] 2023-12-19 00:41
After command `ibus restart` can. 
And the input will be in Russian.

**Comment by Aritty58** [comment] 2023-12-19 00:43
And with ibus 1.5.28 you don't have to do a restart.

**Comment by Aritty58** [comment] 2023-12-19 01:27
@fujiwarat This is problem. 

https://github.com/ibus/ibus/assets/93352572/749e92b8-7ba4-4e2c-a6a4-4f5db621221a

**Comment by Aritty58** [comment] 2023-12-19 01:30
I also can't use game chats.
https://github.com/ibus/ibus/issues/2588#issuecomment-1858621861

**Comment by Bunnysword** [comment] 2023-12-19 07:07
Ibus 1.5.28 works with RU Bel Ukr layouts in Wine\Proton games. The problem is in 1.5.29, in Wine\Proton games the login using the RU Bel Ukr layout does not work. Restarting ibus resolves the issue before logging out of the session. Please correct.

**Comment by fujiwarat** [comment] 2023-12-19 14:25
When I tried the nick name in "Goose Goose Duck", Russian characters are shown correctly in IBus 1.5.29 but  are shown as "???" incorrectly in IBus 1.5.28 and I guess it's relative with this issue.

"Goose Goose Duck" does not start the game until it gets network players and I spend much time - it's a big issue for me and I also find another game but other games require much disc usag, support English only or non-free.

**Comment by Aritty58** [comment] 2023-12-19 15:52
Actually the input problem is in any game. Any game (except native ones). And that's a bad thing. It spoils the gameplay. 
So far the best way is to restart ibus.
I hope it will be fixed in the future.

**Comment by fujiwarat** [comment] 2023-12-19 16:29
Using Russian keyboard for the ASCII keys is a bad thing.
I guess ibus 1.5.28 has a bug not to send Russian characters correctly and I guess it may be good to fix the bug in `ibus restart`.
Anyway I will identify which patch the behavior is changed later.

**Comment by Bunnysword** [comment] 2023-12-19 17:14
Pls fix ibus ska. Not work ru bel uk layout in proton/wine game`S on GNOME DE! On KDE Plasma worked!

**Comment by fujiwarat** [comment] 2023-12-20 02:31
> Pls fix ibus ska. Not work ru bel uk layout in proton/wine game`S on GNOME DE! On KDE Plasma worked!

IBus does not support setting layouts for X application in Plasma Wayland yet.

**Comment by Aritty58** [comment] 2023-12-20 06:52
In fact, the problem is only the need to use `ibus restart` command once. 
After the command, everything works as it should.

**Comment by Ledidic** [comment] 2023-12-20 09:31
I hope I'm not out of line, but I seem to have the same problem.
Since upgrading from Fedora 38 to Fedora 39 I've had a problem with my keyboard too.
So I have a Fedora 39 with the Gnome desktop under x11. I use a French AZERTY keyboard.
In a game I can no longer map accented keys such as é, è, ç.
Another example: in Blender, there are shortcuts on keys 1, 2 and 3, but since this Fedora upgrade, key 2 (which is also é on a FR keyboard) no longer works. Blender tells me "Insupported key".
I hope to make some progress on this subject.
![Blender_map](https://github.com/ibus/ibus/assets/13223848/619fb7a2-880a-4d31-8fdb-206d5278b86e)

**Comment by fujiwarat** [comment] 2023-12-20 23:51
I understand the issue is caused by the patch ad883dc of #2495 and seems a part of the patch is not relative the fix directly. In the patch, I commit the non-ASCII keys for XKB compose table but actually it effects non-compose keys but now I cannot remember what I tired to fix there. Now I see the logic includes a regression.

After the patch integration, the game text window including chat window can show the language characters if the game support the language characters likes "Goose Goose Duck" and other games does not handle the characters - it might be a bug in the games.
On the other hand, committed characters do not work with the game control likes character movement or game action because IBus commit the characters before the game handle keys.

I think there are still other bugs in each game to handle the language characters but I agree to revert the part of the previous patch.

**Closed** 2023-12-21 01:27 UTC
Labels: Priority-Medium, Type-Defect, ibus, OpSys-Linux, OpSys-Windows, steam, xorg

**Comment by fujiwarat** [comment] 2023-12-21 07:27
@russulae Your issue is #2585 but not this.

**Comment by Aritty58** [comment] 2023-12-21 08:48
@fujiwarat I install ibus-1.5.29~rc2-6 in testing repo on Fedora. 
Problem solved. Thanks:)

**Comment by russulae** [comment] 2023-12-21 15:02
> @russulae Your issue is #2585 but not this.

thanks !

**Comment by BetterToAutomateTheWorld** [comment] 2024-11-26 13:42
Hi guys, 

FIrst thank you for this amazing Github issue thread, a lot of useful informations and exaplnations on what's happening

I'm experiencing exactly this issue on Ubuntu 24.04 LTS KDE X11, up to date
I was thinking this was due to X11 at first, then KDE, then Lutris/Heroic Launcher/Steam, then Wine, it's been since June. 2024 i have this issue and nobody was able to neither understand the issue nor help me :/

I was about to install ibus from `sudo add-apt-repository ppa:ibus/ibus-1.5.31` but i'm wondering if you have a better solution to not be too intrusive on the system side? _(i'm kind of afraid ibus can transform my keyboard input to all dead keys if installing an incompatible version, and that would be a pain to fix if that is the case :))_

Thank you!
