### ISSUE TITLE
Input lag with keyboard input in wine/proton games

### ISSUE THREAD

**Issue by CubeTheThird** [ibus/ibus#2656] opened 2024-06-15 15:31 UTC
Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
Gnome 46.2

Which session type?: 
X11

Which application and version?: 
Proton 8, 9, etc.

IBus version?: 
IBus 1.5.30

Issue description:
With ibus version 1.5.30, there seems to be lag or desync with keyboard input for games running through wine/proton. For example, the game Noita will see delayed inputs, sometimes dropped all together. This occurs despite normal frame rate and mouse cursor movement.
This does not occur with IBus 1.5.29-rc2

Steps to reproduce:
1. Run a game through wine/proton that requires keyboard input
2. Repeatedly press keyboard keys
3. Notice the input lag

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment] 2024-06-18 10:07
I observe a lag with GW2 and any ibus releases and I don't think the issue was integrated recently.

**Comment by fedevx** [comment] 2024-06-18 13:14
I'm experiencing the same issue, also on Arch. This is something that started recently. I'll try downgrading to confirm what has been mentioned here and in https://github.com/ibus/ibus/issues/2618. Perhaps these 2 are the same issue?

What I can confirm is that killing ibus-daemon resolves the issue.

**Comment by fujiwarat** [comment] 2024-06-19 01:57
Then you should provide more information to reproduce your issue.

**Comment by fedevx** [comment] 2024-06-20 14:29
I reverted to version 1.5.29-5. I can conform this version is not affected.

If anyone working on this issue needs more information, please ask, and I'll try to provide it.

**Comment by fujiwarat** [comment] 2024-06-23 03:54
Since you didn't provide more info, closing this issue duplicated as #2618.

See below the link how to provide the info.
https://github.com/ibus/ibus/issues/2618#issuecomment-2098330089

On the other hand, You just mentioned reproduced or not only.

**Closed by fujiwarat** 2024-06-23 03:54 UTC

**Comment by nhockey** [comment] 2024-07-31 01:34
I'm experiencing a strange keyboard input issue. Setting the environment variable XMODIFIERS="@im=null" seems to completely resolve the problem, but I'm unsure why, other than it disabling ibus.

The issue is inconsistent. Sometimes, keystrokes are delayed or lost entirely. For example, I might type a series of characters, but only the last few actually register. Additionally, there are instances where keys appear to be held down long after I've released them, leading to unintended actions in games. This happens with both wired and wireless keyboards. Sometimes the input is all out of order.

To illustrate, I once tried to log into a game but my password didn't register. I clicked on the game window thinking maybe it wasn't focused and typed again, and it worked. However, moments later, while playing the game, my character decided to randomly type my password into world chat.
