### ISSUE TITLE
ibus should use keyboard API like xklavier instead of running setxkbmap directly

### ISSUE THREAD

**Issue by juhp** [ibus/ibus#2415] opened 2022-06-09 03:33 UTC
Apparently ibus runs the xorg setxkbmap program to switch keyboard layouts.
This is okay on Xorg but causes problems in Wayland desktops.
It would be better if ibus moved away from using setxkbmap to an API like libxklavier maybe.

Which distribution and version?: 
Fedora 36

Which desktop environment and version?: 
GNOME/KDE

Which session type?: 
Wayland

IBus version?: 
1.5.26

**Comment by fujiwarat** [comment] 2022-08-27 01:02
Duplicate of #2408

**Closed by fujiwarat** 2022-08-27 01:02 UTC
