### ISSUE TITLE
terminator dead key/compose key press/release events eaten by ibus and gtk never receives

### ISSUE THREAD

**Issue by sboddy** [ibus/ibus#1802] opened 2015-06-12 15:49 UTC
Hope the title isn't too provocative.

What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...): Linux Ubuntu 14.04 (Trusty) - all up-to-date
Architecture (i386, x86_64): i386
IBus version: 1.5.5-1ubuntu3.1
Python version: 2.7.5-5ubuntu3
dbus version: 1.6.18-0ubuntu4.3
python-dbus version: 1.2.0-2build2
python-ibus version: 1.5.5-1ubuntu3.1
gtk version (if bug is about gtk applications): 2.24.23-0ubuntu1.2 / 3.10.8-0ubuntu1.5
(ibus-gtk: 1.5.5-1ubuntu3.1)

What steps will reproduce the problem?
1. Launch Terminator
2. Split with Ctrl+Shift+o to two terminals
3. Broadcast to all Alt+a (or use dropdown menu that looks like three boxes)
4. Type some normal characters, should appear in both terminals
5. Try to enter a dead key or compose sequence, i.e. AltGr+' then e to get é

What is the expected output? What do you see instead?
The é should appear in both terminals. Instead it only appears in the one with the current focus.
If I kill the ibus processes, and repeat the test, the é appears in both terminals as expected.

Please provide any additional information below.
Terminator relies on the key-press-event to detect input into a terminal, then emits that to other listening terminals to control multiple terminals. (Useful in large environments) Some debugging and printing of events shows a difference between what is received when ibus is running and what is received after killing ibus.

Further details can be seen here:
https://bugs.launchpad.net/terminator/+bug/1463704
At first I thought it was the vte component that terminator uses, and raised a bug against it, but that was not the case. Discussion with the vte dev is here:
https://bugzilla.gnome.org/show_bug.cgi?id=750798

**Comment by fujiwarat** [comment] 2015-06-23 09:10
I can reproduce your problem.
I think the eaten events are correct.
https://developer.gnome.org/gtk2/stable/GtkIMContext.html#gtk-im-context-filter-keypress
If input method processed the events, it returns TRUE and then the key events are no longer emitted.
ibus uses gtk_key_snooper prior to key-press-event to prioritize the input method shortcut keys.

I think there are two solutions.
1. terminator connects 'commit' signal of vte and emits 'commit' for self.terminals.
E.g. 
        self.vte.connect('key-press-event', self.on_keypress)
        self.vte.connect('commit', self.on_commit)

    def on_commit(self, widget, text, length):
            if self.group and groupsend == groupsend_type['group']:
                self.terminator.group_emit(self, self.group, 'commit',
                        text, length)
            if groupsend == groupsend_type['all']:
                self.terminator.all_emit(self, 'commit', text, length)

2. ibus disables gdk_key_snooper for terminator so that terminator receives key events at first.

For 1, vte already provides "commit" signal but vte does not provide the way to send the commit string to vte->pvt->im_context.
https://git.gnome.org/browse/vte/tree/src/vte.cc#n833
https://git.gnome.org/browse/vte/tree/src/vte.cc#n9000
So need to ask vte maintainer the way but im_context is generally private so I'm not sure if it can be implemented.

For 2, I created a patch:

--- terminator-0.97/terminatorlib/terminal.py.orig	2015-06-23 17:00:37.613751869 +0900
+++ terminator-0.97/terminatorlib/terminal.py	2015-06-23 17:04:35.301605170 +0900
@@ -809,6 +809,10 @@ class Terminal(gtk.VBox):
             dbg('Terminal::on_keypress: Called on %s with no event' % widget)
             return(False)
 
+        if (event.state | gtk.gdk.MODIFIER_MASK ) ^ gtk.gdk.MODIFIER_MASK != 0:
+            dbg('Terminal::on_keypress: Ingore processed event with event.state %d' % event.state)
+            return(False)
+
         # FIXME: Does keybindings really want to live in Terminator()?
         mapping = self.terminator.keybindings.lookup(event)
 
--- ibus-1.5.10/configure.ac.orig	2015-06-23 16:53:25.572063034 +0900
+++ ibus-1.5.10/configure.ac	2015-06-23 16:54:32.132012682 +0900
@@ -511,7 +511,7 @@ AC_ARG_WITH(no-snooper-apps,
     AS_HELP_STRING([--with-no-snooper-apps[=regex1,regex2]],
         [Does not enable keyboard snooper in those applications (like: .*chrome.*,firefox.*)]),
     NO_SNOOPER_APPS=$with_no_snooper_apps,
-    NO_SNOOPER_APPS=[firefox.*,.*chrome.*,.*chromium.*]
+    NO_SNOOPER_APPS=[firefox.*,.*chrome.*,.*chromium.*,terminator]
 )
 AC_DEFINE_UNQUOTED(NO_SNOOPER_APPS, "$NO_SNOOPER_APPS",
     [Does not enbale keyboard snooper in those applications])

You can test the solution with the terminator patch only and run 'env IBUS_DISABLE_SNOOPER=1 terminator'.
The terminator patch is needed if the snooper is disabled not to receive the duplicated key events because ibus uses an async process for the key events and then:
TerminalA receive key-press-event -> TerminalA all_emit -> TerminalB emit key-press-event -> IBus im module async key-press-event -> TerminalB receive key-press-event -> TerminalB all_emit -> ...

**Comment by fujiwarat** [comment] 2015-06-23 09:15
Hmm.., wiki breaks the patch format.
Paste the patches again.

```
--- terminator-0.97/terminatorlib/terminal.py.orig	2015-06-23 17:00:37.613751869 +0900
+++ terminator-0.97/terminatorlib/terminal.py	2015-06-23 17:04:35.301605170 +0900
@@ -809,6 +809,10 @@ class Terminal(gtk.VBox):
             dbg('Terminal::on_keypress: Called on %s with no event' % widget)
             return(False)
 
+        if (event.state | gtk.gdk.MODIFIER_MASK ) ^ gtk.gdk.MODIFIER_MASK != 0:
+            dbg('Terminal::on_keypress: Ingore processed event with event.state %d' % event.state)
+            return(False)
+
         # FIXME: Does keybindings really want to live in Terminator()?
         mapping = self.terminator.keybindings.lookup(event)
 
--- ibus-1.5.10/configure.ac.orig	2015-06-23 16:53:25.572063034 +0900
+++ ibus-1.5.10/configure.ac	2015-06-23 16:54:32.132012682 +0900
@@ -511,7 +511,7 @@ AC_ARG_WITH(no-snooper-apps,
     AS_HELP_STRING([--with-no-snooper-apps[=regex1,regex2]],
         [Does not enable keyboard snooper in those applications (like: .*chrome.*,firefox.*)]),
     NO_SNOOPER_APPS=$with_no_snooper_apps,
-    NO_SNOOPER_APPS=[firefox.*,.*chrome.*,.*chromium.*]
+    NO_SNOOPER_APPS=[firefox.*,.*chrome.*,.*chromium.*,terminator]
 )
 AC_DEFINE_UNQUOTED(NO_SNOOPER_APPS, "$NO_SNOOPER_APPS",
     [Does not enbale keyboard snooper in those applications])
```

**Comment by fujiwarat** [comment] 2015-06-23 09:18
However 2 fixes the compose keys only but input method is available on the focused terminal only.
To fix both compose keys and input methods commits, need to think 1.
So the solution 2 is a workaround at present.

**Comment by fujiwarat** [comment] 2015-06-25 02:32
@sboddy
Would you apply the change of terminator?
I wait for the integration because only the ibus patch causes the regression in terminator.

**Comment by fujiwarat** [comment] 2015-07-27 04:12
@sboddy
Any chances to update terminator?
If the terminator won't be updated, I will close this.

**Comment by sboddy** [comment] 2015-07-27 10:14
Apologies, was focused elsewhere. I will try and check this out this week.

**Comment by sboddy** [comment] 2015-08-10 20:27
Hi, again, sorry for the delay. I tested it and it has fixed the issue. So that users don't need to pass the env, I'm (for now) forcing that in the startup. So it all works and doesn't seem to cause any side effects for me, but I'm kinda hazy on what IBus is, and does. I tend to think of it as something that people with 3000 letter alphabets need. What I guess I'm asking is what do we *lose* by disabling IBus like this?

Ironically I'm beginning to wonder if the symptom of using the env var without the patch giving double chars might not be related to some bugs we get about duplicated chars. So this might kill two birds with one stone :-)

Thanks for the patch and the patience!

**Comment by fujiwarat** [comment] 2015-08-11 03:02
Thank you for the integration.
http://bazaar.launchpad.net/~gnome-terminator/terminator/trunk/revision/1611#terminator

Actually I asked the patch of terminatorlib/terminal.py  only.
The part of $IBUS_DISABLE_SNOOPER can be fixed with ibus/configure.ac as I noted above:
```
--- ibus-1.5.10/configure.ac.orig	2015-06-23 16:53:25.572063034 +0900
+++ ibus-1.5.10/configure.ac	2015-06-23 16:54:32.132012682 +0900
@@ -511,7 +511,7 @@ AC_ARG_WITH(no-snooper-apps,
     AS_HELP_STRING([--with-no-snooper-apps[=regex1,regex2]],
         [Does not enable keyboard snooper in those applications (like: .*chrome.*,firefox.*)]),
     NO_SNOOPER_APPS=$with_no_snooper_apps,
-    NO_SNOOPER_APPS=[firefox.*,.*chrome.*,.*chromium.*]
+    NO_SNOOPER_APPS=[firefox.*,.*chrome.*,.*chromium.*,terminator]
 )
 AC_DEFINE_UNQUOTED(NO_SNOOPER_APPS, "$NO_SNOOPER_APPS",
     [Does not enbale keyboard snooper in those applications])
```
But if you wish to have the change in terminator and don't need to change ibus/configure.ac, I'm also fine and will close this issue.

**Comment by sboddy** [comment] 2015-08-11 12:13
Hi Takao, The problem was that if a release went out without Terminator and IBus being in sync, then the user would have problems (double-chars, or no broadcast function). This was easiest from being the person who users would blame ;-)

It's up to you if you proceed to commit. If so, then I would remove the then redundant forcing of the var. If not, then it just stays there as a symptom of having to work around the system to achieve the particular goals of Terminator.

Many thanks for the support.

**Comment by fujiwarat** [comment] 2015-08-14 02:27
Integrated the patch.
https://github.com/ibus/ibus/commit/173af53099633fa18713ac45f9f64b50607f83ff

**Closed by fujiwarat** 2015-08-14 02:27 UTC
Labels: Component-ibus, ibus, Priority-Medium, Type-Defect
