### ISSUE TITLE
ibus-table IM incorrectly assumes ambiguity

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1671] opened 2015-05-23 10:44 UTC
```
What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...): Fedora Linux (problem also exists on Arch Linux)
Architecture (i386, x86_64): x86_64
IBus version: 1.5.3
Input method name and version: ipa-x-sampa 1.3.0.20130204 (from ibus-table-others)
Python version: 2.7.5 and 3.3.2
dbus version: 1.6.12
dbus-python version: 1.1.1

What steps will reproduce the problem?
1. Select ipa-x-sampa IM
2. Enter the character s

What is the expected output? What do you see instead?
A candidate window appears allowing the user to select between s, ɕ\, and ʂ`. Further
typing not matching one of these characters causes the entire current candidate to
have no matches. The input sequence for ɕ is s\, but s itself is unambiguous. Instead,
typing s should cause an s to appear and further typing should continue producing correct
IPA, but typing s\ should cause ɕ to appear. Additionally, ɕ should not appear as ɕ\.

Please provide any additional information below.

```

Original issue reported on code.google.com by `leftmostcat` on 2013-09-04 18:58:30

**Comment by mike-fabian** [comment] 2015-05-28 06:24
Original report on google code was: https://code.google.com/p/ibus/issues/detail?id=1655

**Comment by mike-fabian** [comment] 2015-05-28 07:19
> A candidate window appears allowing the user to select between s, ɕ\,
> and ʂ`. Further typing not matching one of these characters causes the
> entire current candidate to have no matches. The input sequence for ɕ
> is s\, but s itself is unambiguous. Instead, typing s should cause an
> s to appear and further typing should continue producing correct IPA,
> but typing s\ should cause ɕ to appear. Additionally, ɕ should not
> appear as ɕ\.

The behaviour described here seems correct to me.

The candidate window shows all matches for “s*” (where * is
an autowildcard added because of the option 

    ### If true then a multi wildcard will be appended
    ### at the end of inputing string automatically.
    AUTO_WILDCARD = TRUE

One could change that behaviour by setting this option to false.
But I believe this option is very useful here, especially if you
do not yet know all IPA-X-SAMPA codes by heart.

“s” plus the autowildcard, i.e. “s*” matches

    s	s	0	### U+0073 LATIN SMALL LETTER S
    s\	ɕ	0	### U+0255 LATIN SMALL LETTER C WITH CURL
    s`	ʂ	0	### U+0282 LATIN SMALL LETTER S WITH HOOK

and the candidate list looks like:

    s (1/3)
    F1. s
    F2. ɕ \
    F3. ʂ `

On top, in the row “s (1/3)” the exact user input is shown,
i.e. without the automatically added wildcard.

In the candidates, exact matches of the user input have no
trailing characters, like

    F1. s

But in case of the candidates F2 and F3, the input the user
actually typed matches only the beginning of the input sequence
only because of the auto wildcard, these candidates are shown
by auto completion. For such candidates, the part of the input sequence
the user has not yet typed is shown after the candidate.

I.e. the input sequence for “ɕ” is “s\”, the user has typed only
“s” so far, it would be necessary to type “\” to complete the
input sequence for “ɕ”. This makes it easier to learn the necessary
input sequences as one sees what one needs to type to complete
a certain candidate.

So I think this behaviour is just fine.

**Comment by mike-fabian** [comment] 2015-05-28 07:33
Closing, because this is not a bug.

**Comment by mike-fabian** [comment] 2015-06-01 05:22
https://code.google.com/p/ibus/issues/detail?id=1655#c3

leftmostcat = Sean Burke writes:

leftmostcat> Thinking about it, my issue isn't that the candidate
leftmostcat> window appears, but that continued unambiguous typing
leftmostcat> (for example, 'sk' is unambiguous in this table) doesn't
leftmostcat> clear the candidate window. Typing 'sk' causes it to fail
leftmostcat> to find candidates, rather than allowing the user to
leftmostcat> continue typing.
leftmostcat> 
leftmostcat> The real issue I have is that, because I do know the
leftmostcat> X-SAMPA sequences for the IPA I want to produce, I should
leftmostcat> be able to type without pauses to select candidates.

**Comment by mike-fabian** [comment] 2015-06-01 05:50
Actually it works as you request as long as the option AUTO_SELECT is set to TRUE.
AUTO_SELECT=TRUE is the default for the ipa-x-sampa table, so if you have changed
this accidentally, you can go back to sane default options by clicking on
“Restore all defaults” in the setup tool of ipa-x-sampa.

It is possible that this didn’t work correctly in the past because I did a lot of fixes in ibus-table,
so please try this with an up-to-date version of ibus-table (currently ibus-table-1.9.6).
![ipa-x-sampa-setup-tool](https://cloud.githubusercontent.com/assets/2330175/7906936/d9ae3a12-0832-11e5-8488-8057ab172e93.png)

**Closed by mike-fabian** 2015-06-01 05:50 UTC
Labels: Component-ibus-table-others, Priority-Medium, Type-Defect
