### ISSUE TITLE
On startup I see Ibus tray icon even if it's disabled in Options

### ISSUE THREAD

**Issue by georgehazan** [ibus/ibus#2472] opened 2023-02-06 17:31 UTC
Which distribution and version?: 
Kubuntu 22.10 + all fixes

Which desktop environment and version?: 
KDE Plasma 5.26.5, KDE Frameworks 5.101.0, Qt 5.15.6

Which session type?: 
X11

Which application and version?: 
Ibus itself

IBus version?: 
IBus 1.5.27

Issue description:
In the Ibus options (screenshot attached) I disabled the tray icon, but it appears nevertheless each time I run Linux.
![Screenshot_20220127_100551](https://user-images.githubusercontent.com/4628541/217042575-01005443-e22b-4e2e-8315-27d22e0ff055.png)

Steps to reproduce:
1. Rclick on Ibus tray icon -> Preferences -> disable Tray Icon
2. Reboot Linux
3. See this tray icon again

If I open Preferences,enable the tray icon and disable it again, the icon disappears... till the next reboot.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

**Comment by alwertus** [comment] 2023-02-11 05:39
I have the same problem

**Comment by sfkpmr** [comment] 2023-02-14 17:45
Duplicate of #2463.

**Closed** 2024-03-22 10:15 UTC
