### ISSUE TITLE
Candidate panel goes off screen

### ISSUE THREAD

**Issue by tleydxdy** [ibus/ibus#2075] opened 2019-01-30 19:58 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Arch
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: i3wm
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: X11
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: firefox
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.19
(Run `ibus version`)

Issue description:
when typing chinese, in firefox (for example here) the candidate box will be off screen, only when minimizing the window to above the half way line would the candidate box shown below. I understand that firefox might not work with ibus, but the candidate panel shouldn't be off screen anyways. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by tleydxdy** [comment] 2019-01-31 18:00
It happens on a HiDPI screen.

**Comment by fujiwarat** [comment] 2019-02-01 07:49
How did you enlarge your screen? I think the default size with HiDPI is no problem.

**Comment by tleydxdy** [comment] 2019-02-04 18:33
I follow the notes in https://wiki.archlinux.org/index.php/HiDPI
Enviroments:
```
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
```
.Xresources:
```
Xft.dpi: 192
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb
```
xorg.conf:
```
Section "Monitor"
    Identifier             "eDP1"
    DisplaySize            423 238
EndSection
```
which calculate to a dpi of 192 too, 
as shown by 
```
$ xdpyinfo | grep -B2 resolution
screen #0:          
  dimensions:    3200x1800 pixels (423x238 millimeters)
  resolution:    192x192 dots per inch
```

**Comment by fujiwarat** [comment] 2019-02-06 06:33
I run `env GDK_SCALE=2 GDK_DPI_SCALE=0.5 firefox` and confirmed the ibus candidate window works fine.
![fujiwara-firefox](https://user-images.githubusercontent.com/105929/52324257-ef636000-2a23-11e9-939f-d5ea0d4c649c.png)

Since firefox is based on GTK3, I think QT_AUTO_SCREEN_SCALE_FACTOR is not needed.

If I drag & drop the firefox window, I noticed the ibus candidate window does not get the latest location of firefox window and I think it's a firefox issue.

> in firefox (for example here) the candidate box will be off screen, only when minimizing the window to above the half way line would the candidate box shown below

I cannot reproduce the off screen and I'd ask you to take the screenshot.

**Comment by tleydxdy** [comment] 2019-02-06 16:06
The problem doesn't seem to happen in the firefox's address bar (so far), but in various input boxes, for example this reply box. I've recorded a video [here](https://cloud.tlebear.win/s/Q4tkNGKGsKWTRiC)

**Comment by fujiwarat** [comment] 2019-02-12 08:18
Seems the application title bar is integrated into the desktop panel in your box.
What happens when the integration mode is disabled?
I mean when you type `firefox` and Enter key on gnome-terminal and firefox is launched, I guess your problem is not reproduced if you don't change the window position of firefox with mouse drag & drog?

**Comment by fujiwarat** [comment] 2019-02-12 08:24
> What happens when the integration mode is disabled?

Seems the integration mode is disabled in the second movie and please ignore this question.

> I mean when you type `firefox` and Enter key on gnome-terminal and firefox is launched, I guess your problem is not reproduced if you don't change the window position of firefox with mouse drag & drog?

I'd still ask the question above.

Also do you see the same problem with ibus-libpinyin?

**Comment by tleydxdy** [comment] 2019-02-12 11:32
I didn't quite understand the problem, but launching firefox from terminal have the same problem, I can only see the panel when the moon is lined up, best demonstrated by [this vid](https://cloud.tlebear.win/s/2bt2xeCqQoiqG34), but I'll leave all the recordings in the [folder](https://cloud.tlebear.win/s/KDH6bL9bJgdQ3WD).

**Comment by tleydxdy** [comment] 2019-03-13 01:33
I'm switching to fcitx for now, it doesn't seem to have the same problem.

**Comment by fujiwarat** [comment] 2019-03-13 07:05
I still don't understand the problem and seems the screencast was deleted.
It would not be a high priority issue for me since the resolution is not default and  I don't have the big screen to reproduce the issue.

**Comment by fujiwarat** [comment] 2020-01-08 09:24
Duplicate of #2157

**Closed by fujiwarat** 2020-01-08 09:24 UTC
