### ISSUE TITLE
(Regression) TrackMania Nations Forever under Wine does not always register key releases under IBus 1.5.28

### ISSUE THREAD

**Issue by joanbm** [ibus/ibus#2480] opened 2023-02-26 01:22 UTC
Which distribution and version?: **Arch Linux (updated as of 2023-02-25)**
Which desktop environment and version?: **Sway 1.8.1**
Which session type?: **Wayland**
Which application and version?: **Wine 8.2, Trackmania Nations Forever**
IBus version?: **IBus 1.5.28**

## Issue description:

While playing TrackMania Nations Forever under Wine, I noticed that sometimes (once in a few minutes) the car continued steering after fully releasing the corresponding input key on my keyboard. Pressing and re-releasing the corresponding input fixed the problem. So, it appears that the game failed to register the key release event.

After some troubleshooting it appears the problem appeared with IBus 1.5.28. Killing IBus or downgrading to IBus 1.5.27 fixes the problem.

The problem seems related to commit 506ac9993d5166196b7c4e9bfa9fb0f9d3792ffa. Setting `IBUS_ENABLE_SYNC_MODE=1` when launching the IBus 1.5.28 daemon fixes the problem as well.

## Steps to reproduce:

1. Install and enable IBus 1.5.28
2. Install TrackMania Nations Forever under Wine
3. Try to play the game normally
4. Notice that sometimes the car steers to some direction without pressing the coresponding input

Can you reproduce your problem when you restart ibus-daemon?: **Yes**
Do you see any errors when you run ibus-daemon with the verbose option?: **No**
Can you reproduce your problem with a new user account instead of the current your account? **Yes**

## Additional information & test program

Since reproducing the bug in Wine is quite hard and uninformative I tried writing a standalone test program (see below) to try to reproduce and debug the issue.

I observe the following problems under `IBUS_ENABLE_SYNC_MODE=2` but not under `IBUS_ENABLE_SYNC_MODE=1`:

1. When randomly pressing keys the errors "ERROR: PRESSING ALREADY PRESSED KEY?" and "RELEASING ALREADY RELEASED KEY?" are printed quite often.

2. Often both the key release and key press events are delived out-of-order (release then press). Most likely this is what causes TMNF to still think the key is pressed.

This reproduces on both my Arch Linux install and also on a clean Fedora Rawhide 2023-02-25 i3 Spin live session.

## Standalone test program

```c
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xos.h>
#include <stdlib.h>
#include <stdio.h>
#include <locale.h>
#include <stdbool.h>
#include <unistd.h>
#include <time.h>

int main() {
	// START Boilerplate thanks to Ted Yin (Determinant): https://gist.github.com/Determinant/19bbecb6db35312861f6cf9f54fdd3a5

	/* fallback to LC_CTYPE in env */
	setlocale(LC_CTYPE, "");
	/* implementation-dependent behavior, on my machine it defaults to
	 * XMODIFIERS in env */
	XSetLocaleModifiers("");

	/* setting up a simple window */
	Display *dpy = XOpenDisplay(NULL);
	int scr = DefaultScreen(dpy);
	Window win = XCreateSimpleWindow(dpy,
	                                 XDefaultRootWindow(dpy),
	                                 0, 0, 100, 100, 5,
	                                 BlackPixel(dpy, scr),
	                                 BlackPixel(dpy, scr));
	XMapWindow(dpy, win);

	/* initialize IM and IC */
	XIM xim = XOpenIM(dpy, NULL, NULL, NULL);
	XIC ic = XCreateIC(xim,
	                   /* the following are in attr, val format, terminated by NULL */
	                   XNInputStyle, XIMPreeditNothing | XIMStatusNothing,
	                   XNClientWindow, win,
	                   NULL);

	/* focus on the only IC */
	XSetICFocus(ic);
	/* capture the input */
	XSelectInput(dpy, win, KeyPressMask | KeyReleaseMask);
	XPoint spot;
	spot.x = 0;
	spot.y = 0;
	XVaNestedList preedit_attr;
	preedit_attr = XVaCreateNestedList(0, XNSpotLocation, &spot, NULL);
	XSetICValues(ic, XNPreeditAttributes, preedit_attr, NULL);
	XFree(preedit_attr);

	// END Boilerplate thanks to Ted Yin (Determinant): https://gist.github.com/Determinant/19bbecb6db35312861f6cf9f54fdd3a5

	srand(time(NULL));

	bool keystate[256] = {0};
	for (;;)
	{
			XEvent ev;
			XNextEvent(dpy, &ev);
			if (XFilterEvent(&ev, None))
					continue;
			usleep(rand() % 100000);
			if (ev.type == KeyPress)
			{
				printf("Press KeyCode: %d\n", ev.xkey.keycode);
				if (ev.xkey.keycode < 256) {
					if (keystate[ev.xkey.keycode]) {
						printf("ERROR: PRESSING ALREADY PRESSED KEY?\n");
					}
					keystate[ev.xkey.keycode] = true;
				}
			}
			else if (ev.type == KeyRelease)
			{
				printf("Release KeyCode: %d\n", ev.xkey.keycode);
				if (ev.xkey.keycode < 256) {
					if (!keystate[ev.xkey.keycode]) {
						printf("ERROR: RELEASING ALREADY RELEASED KEY?\n");
					}
					keystate[ev.xkey.keycode] = false;
				}
			}
	}
}
```

## Sample bad output

``` $ gcc ximghostkeys.c -lX11 && ./a.out
Press KeyCode: 46
Press KeyCode: 45
Press KeyCode: 44
Release KeyCode: 46
Release KeyCode: 45
Release KeyCode: 44
Press KeyCode: 45
Press KeyCode: 46
Release KeyCode: 44
ERROR: RELEASING ALREADY RELEASED KEY?
Release KeyCode: 45
Press KeyCode: 44
Release KeyCode: 46
Release KeyCode: 44
Release KeyCode: 45
ERROR: RELEASING ALREADY RELEASED KEY?
Press KeyCode: 44
Release KeyCode: 46
ERROR: RELEASING ALREADY RELEASED KEY?
Press KeyCode: 45
Press KeyCode: 46
[NOTE: All actual keyboard keys are released at this point]
```

**Comment by fujiwarat** [comment] 2023-02-28 13:42
Thank you for the test case.

**Comment by fujiwarat** [comment] 2023-03-08 10:46
I created the tentative patch above. Could you try it?

**Comment by joanbm** [comment] 2023-03-08 20:40
@fujiwarat I tried your patch and it appears to fix the problem, I was not able to reproduce the problem in 1h of gameplay of TrackMania Nations Forever  (whereas without the patch I reproduced it thrice in 20 minutes).

**Comment by scramble45** [comment] 2023-03-11 22:35
> I created the tentative patch above. Could you try it?

Thanks for getting that fixed, any timeline for when this will get merged in?

**Comment by fujiwarat** [comment] 2023-03-15 01:26
Sorry for the late response. Seems #2484 still happens with this patch and I have investigated it. I added an additional patch.

**Comment by joanbm** [comment] 2023-03-15 21:23
Hmmmm FWIW some notes from my testing those days:

* Using only 9d9dca9e103e88b33e786c4a46f44123a6cf11c6 fixed the original issue and I never experienced a crash during regular use.

* However, while I was doing some testing with the test program above, I noticed that if I pressed as many keys as fast as possible by mashing a N-Key Rollover keyboard with the palm of my hand for a few seconds, I could get ibus-x11 to crash with valgrind reporting invalid `free()` issues at the same function you changed in 33146f4a9a52987980cad9d4fe833bac9ee14fb3.

* With both 9d9dca9e103e88b33e786c4a46f44123a6cf11c6 and 33146f4a9a52987980cad9d4fe833bac9ee14fb3 everything seems fine, I can't reproduce the crash above nor the original issue so far.

**Comment by fujiwarat** [comment] 2023-03-16 10:56
Thank you for the tests.
Let's continue to test the two patches and I added the patches in Fedora 38 updates-testing repository for the tests.
If we don't see any other regressions, I will integrate those to the IBus upstream.

**Closed** 2023-03-23 04:32 UTC
Labels: Priority-Medium, Type-Defect, OpSys-All, ibus, xorg

**Comment by fabiscafe** [comment] 2023-03-23 10:08
@fujiwarat Thanks for this! Is it OK to apply only commit https://github.com/ibus/ibus/commit/497f0c74230a65309e22ce5569060ce48310406b on top of standard ibus 1.15.28 or is there anything else that is required?

**Comment by Plagman** [comment] 2023-06-12 23:13
Any plans to cut a new release with this fix?

**Comment by johnnybubonic** [comment] 2023-09-15 09:15
It will be in 1.5.29 (barring some major breakage with the fix is discovered). It's already in 1.5.29-rc1.

**Comment by fansari** [comment] 2024-01-05 16:35
I stil have this issue with ibus-1.5.29~rc2-6.fc39.x86_64. 
Playing Lacuna is not possible to change the direction of the character.
workaround: "ibus restart" after starting Steam prevents the issue.

**Comment by oemsysadm** [comment] 2024-05-24 15:43
Manjaro Gnome, ibus 1.5.30-1, keys sticking in multiple games (Subnautica, Raft, among others) when running on Proton (GE 9.5, Proton Experimental) through Steam. Seems like maybe this issue?

Keys stick and won't release, then suddenly releases after a while on its own. This started happening somewhat recently. I tried using two different keyboards to rule out hardware issues.

**Comment by nergdron** [comment] 2024-10-07 19:57
note that I think marking this as closed is premature, since this is definitely still happening with version `1.5.30`.
