### ISSUE TITLE
Cannot enable in firefox under wayland

### ISSUE THREAD

**Issue by xofyarg** [ibus/ibus#2245] opened 2020-07-29 20:15 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
debian bullseye

Which desktop environment and version?: 
sway

Which session type?: 
Wayland

Which application and version?: 
Firefox 79

IBus version?: 
IBus 1.5.22

Issue description:
I'm able to invoke ibus in program using xwayland/xim(e.g. rxvt-unicode), firefox(xwayand), by default shortcut Control-Space,  but not with firefox(wayland). The panel didn't come out when I pressed the hotkey.

If enabled "share the same input method among all applications" setting in ibus, enable it on an xwayland application, then move forcus onto firefox(wayland), the panel is blinking when typing, and the composed text can be committed into firefox sometimes, but still barely usable.

Steps to reproduce:
1. set environment variables:
```
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"
```

2. start ibus daemon
```
ibus-daemon -rvx --panel /usr/libexec/ibus-ui-gtk3
```

3. start a wayland firefox session
```
export MOZ_ENABLE_WAYLAND=1
firefox
``` 
4. try to invoke ibus by pressing control-space

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment] 2020-09-08 01:47
Duplicate of #2182

**Closed by fujiwarat** 2020-09-08 01:47 UTC
