### ISSUE TITLE
Memory leaks in src/ibusproperty.c

### ISSUE THREAD

**Issue by hadess** [ibus/ibus#2393] opened 2022-03-29 15:17 UTC
The changes related to static IBusText in 5a455b1ead5d72483952356ddfe25b9e3b637e6f are definitely incorrect.

The `ibus_text_new_from_static_string()` doc doesn't say that `IBusText` shouldn't be unref'ed/freed, but that the text passed to it shouldn't be. There's already code in `ibus_text_destroy` to check whether the string is static to not free it. The object structures should definitely be freed.

CC @ermshiperete

**Comment by fujiwarat** [comment] 2022-03-31 10:18
Thank you for the report.
Duplicate of #2387

**Closed by fujiwarat** 2022-03-31 10:18 UTC
