### ISSUE TITLE
Candidate phrase show error in the second display

### ISSUE THREAD

**Issue by wmzy** [ibus/ibus#2087] opened 2019-03-22 10:43 UTC
Please fill in the following items if you don't know the root cause.

Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 29.

Which desktop environment and version?: 
GNOME 3.24. 

Which session type?: 
Wayland. 

Which application and version?: 
vscode or gnome-terminal

IBus version?: 
1.5.19

Issue description:
![input2](https://user-images.githubusercontent.com/5526525/54817413-d2cc7000-4cd1-11e9-9985-d8be6c8f5d71.gif)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment] 2019-04-16 07:06
Duplicate of #2048

**Closed by fujiwarat** 2019-04-16 07:06 UTC
