### ISSUE TITLE
Candidate can't be shown in hyprland.

### ISSUE THREAD

**Issue by Yulljie** [ibus/ibus#2612] opened 2024-02-16 15:05 UTC
Which distribution and version?: 
Arch linux
Which desktop environment and version?: 
Hyprland v0.35.0

Which session type?: 
Wayland

Which application and version?: 
All apps : (

IBus version?: 
(Run `ibus version`)
1.5.29-rc2

Issue description:
Candidate can't be shown in hyprland,even I used way in https://github.com/hyprwm/Hyprland/issues/288
There's only the first candidate character(I guess) in input box.

Steps to reproduce:
1. install ibus and ibus-libpinyin
2. run ibus-setup,add "export ..."codes into .bashrc
3. Add "Chinese - 智能拼音" into Input Method
4. Input any Chinese character in any window

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by Yulljie** [comment] 2024-02-21 12:03
Maybe I didn't describe the problem clearly
In gnome it's ok :
![截图 2024-02-22 03-47-58](https://github.com/ibus/ibus/assets/78137234/1b534a39-7de7-4162-8235-5f9b06c8fd1c)
In hyprland :
![截图 2024-02-22 03-58-57](https://github.com/ibus/ibus/assets/78137234/93afc4df-6acd-4670-a23a-ded82b92fb97)

Thank you very much : )

**Comment by fujiwarat** [comment] 2024-02-22 01:23
> Maybe I didn't describe the problem clearly

I understand your issue and replied the suggestion above.

**Comment by NyxTrail** [comment] 2024-02-29 07:26
I think both ibus-ui-gtk3 and ibus-wayland will fail in hyprland with error: 'No input_method global' because ibus does not support input method v2 yet: https://github.com/ibus/ibus/issues/2182

(Hyprland also uses wlroots)

**Comment by fujiwarat** [comment] 2024-02-29 07:57
@NyxTrail Thank you.
v2 is in my todo list.

**Comment by fujiwarat** [comment] 2024-02-29 07:58
Duplicate of #2182

**Closed by fujiwarat** 2024-02-29 07:58 UTC
