### ISSUE TITLE
ibus candidate box is not near the text input box

### ISSUE THREAD

**Issue by chenzhiwei** [ibus/ibus#2046] opened 2018-10-03 13:55 UTC
Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

**Ubuntu 18.10 beta**

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

**ubuntu:GNOME** 3.30.0

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

**X11**

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

**Google Chrome Stable: Version 69.0.3497.100 (Official Build) (64-bit)**

IBus version?: 
(Run `ibus version`)

**IBus 1.5.19**

Issue description:

**ibus candidate box is not near the text input box in Google Chrome browser, but in other applications(Chromium Browser, Firefox, Gnome-terminal and so on) it is near the text input box.**

![image](https://user-images.githubusercontent.com/672668/46414872-a722f100-c756-11e8-92c0-9948869122b9.png)

Steps to reproduce:

**I installed Ubuntu 18.10 beta on my MacBook Pro 2015, and activated ibus, then I encountered this issue.**

**Comment by fujiwarat** [comment] 2018-10-05 03:02
> can you try scale the display to 200% and try?

I think you didn't mention this.
Please file a bug to chrome.

Duplicate of 2039

**Closed by fujiwarat** 2018-10-05 03:02 UTC
