### ISSUE TITLE
Compose key broken after upgrade to 1.5.18

### ISSUE THREAD

**Issue by darthoctopus** [ibus/ibus#2004] opened 2018-04-28 15:47 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
GNOME 3.28

Which session type?: 
X11

Which application and version?: 
All

IBus version?: 
1.5.18

Issue description:
compose key fails to work

Steps to reproduce:
1. start ibus daemon
2. attempt to use compose key (e.g. compose + " + U)
3. keys are not composed

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

Other notes
Compose key works momentarily after changing input methods (e.g. when I switch from pinyin/anthy to english, then entering one or two compose sequences works for a few seconds)

Compose sequences are also being correctly sent to e.g. xev, but the composed characters are getting eaten when ibus-daemon is running.

**Comment by fujiwarat** [comment] 2018-05-02 03:49
I cannot reproduce your problem in Fedora.

> Compose key works momentarily after changing input methods (e.g. when I switch from pinyin/anthy to english

Do you mean the English source is `xkb:us::eng` engine?
You can check the current engine with `ibus engine` command.
Since you already add "pinyin" or "anthy" with `gnome-control-center region`, I know you always use ibus

> attempt to use compose key (e.g. compose + " + U)

Which keycap do you use as the compose key and how did you configure the compose key?
You can see `Multi_key` on xev when you press the compose key.
GNOME uses gnome-tweaks to configure the compose keys.

**Comment by darthoctopus** [comment] 2018-05-04 01:03
> Do you mean the English source is `xkb:us::eng engine`?
That's what I get from the output of `ibus engine` under 1.5.17. With 1.5.18 I get
```(process:18856): IBUS-WARNING **: 20:59:36.220: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
No engine is set.```
irrespective of whatever input method is active.

> Which keycap do you use as the compose key and how did you configure the compose key?
I use `ralt` as the compose key, and I do see `Multi_key` in `xev`. I configured it using the GNOME tweak tool. When I restart ibus it stops working, but it works again when I call `setxkbmap -option compose:ralt`. None of this works with 1.5.18.

**Comment by fujiwarat** [comment] 2018-05-04 08:42
> (process:18856): IBUS-WARNING **: 20:59:36.220: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
> No engine is set.

I wonder if you run ibus-daemon.

> Do you see any errors when you run ibus-daemon with the verbose option?:
> (Run ibus-daemon --xim --verbose & and look at the output when you encounter your problem.)
> No

Since GNOME restarts ibus automatically, I also wonder if you could run the command correctly.
Can you try the following commands and check any warnings? :
```
% sudo mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.orig
% ibus exit
% ibus-daemon.orig --xim --verbose &
```

**Comment by darthoctopus** [comment] 2018-05-04 12:29
Per #2005, setting an emoji selection keyboard shortcut resolves the issue. I'd like to consolidate the two issues.

**Comment by gamlerhart** [comment] 2018-05-05 08:01
@darthoctopus The work around setting a emoji keyselection fixed the issue for me.

**Comment by fujiwarat** [comment] 2018-05-07 03:40
Why did you delete the emoji shortcut keys?

**Comment by fujiwarat** [comment] 2018-05-07 03:40
Duplicate of #2005

**Closed by fujiwarat** 2018-05-07 03:40 UTC

**Comment by darthoctopus** [comment] 2018-05-08 02:19
ctrl-shift-e is the default keyboard shortcut for the network inspector in firefox's devtools

**Comment by fujiwarat** [comment] 2018-05-08 03:35
OK, I see. Thank you.
