### ISSUE TITLE
Keyboard Shortcut is not working on some apps 

### ISSUE THREAD

**Issue by elhananjair** [ibus/ibus#2511] opened 2023-05-20 20:18 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Fedora 38
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Plasma 5.27.5
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Firefox 113.0.1 (64-bit) , Kwrite 23.04.1 and Konsole 23.04.1
IBus version?: 
(Run `ibus version`)
23.04.1
Issue description:
I set a keyboard shortcut for switching the next input method, and it works fine on some applications such as Chromium, vscode, and Joplin, but doesn't work on Konsole, or Firefox.

Steps to reproduce:
1.  Go to ibus setting 
2.  Set CTRL + SPACE as a shortcut to the next input method
3.  Open Firefox and hit the shortcut, the input method won't change.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes
Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No
Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment] 2023-05-29 10:54
I've been working on the Plamsa Wayland issues.
Duplicate of #2408

**Closed by fujiwarat** 2023-05-29 10:54 UTC
