### ISSUE TITLE
Can't display candidate box in WOW fullscreen

### ISSUE THREAD

**Issue by leslielg** [ibus/ibus#2346] opened 2021-09-06 05:32 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
ubuntu 20.04
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
default DE that shipped with ubuntu 20.04
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
x11
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
steam proton experiment
IBus version?: 
(Run `ibus version`)
lastes one from ubuntu 20.04 official apt
Issue description:
Can't display candidate characters when World of Warcraft in fullscreen mode
If run WOW in window mode, I can see the candidate box at left bottom.

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by leslielg** [comment] 2021-09-06 05:59
![a699372ac65c103885e2df78a5119313b17e8931](https://user-images.githubusercontent.com/5469646/132167861-0541cf17-6d1c-4d0b-b967-0b5e6ff89460.png)

**Comment by fujiwarat** [comment] 2021-09-07 05:41
Did you check the fix of #2337 ?

**Comment by leslielg** [comment] 2021-09-08 02:40
> Did you check the fix of #2337 ?

Sorry I'm new to this, how to try this fix on ubuntu 20.04? any workaround or test build binary?

**Comment by fujiwarat** [comment] 2021-09-08 12:36
There is no workaround. Please file Ubuntu bug report to import the fix.
Duplicate of #2337

**Closed by fujiwarat** 2021-09-08 12:36 UTC

**Comment by leslielg** [comment] 2021-09-09 03:51
Could you figure out a simpler way to apply such emergency fix? like nightly build .deb package, or .deb per commit

**Comment by fujiwarat** [comment] 2021-09-09 04:17
You could ask Ubuntu downstream the simpler way.

**Comment by leslielg** [comment] 2021-09-09 06:16
That looks too long cycle to know if #2337 fix my issue, any way thanks for your support
