### ISSUE TITLE
4-second hang upon trying to type a password

### ISSUE THREAD

**Issue by picsi** [ibus/ibus#1925] opened 2017-05-05 19:31 UTC
I'm using ibus-anthy for Japanese alongside my main Brazilian Portuguese keyboard layout. While in Portuguese and clicking in a password field, the system will hang for about 4 seconds as it hides the IME dropdown tool from GNOME's tray bar.

Without ibus-anthy the problem doesn't happen, so I'm inclined to believe that it is the culprit.

**Comment by fujiwarat** [comment] 2017-05-08 04:09
I cannot reproduce your problem.
Can you run ibus-anthy by manual and see any errors:
```
% ps -ef | grep ibus-anthy
picsi 21492  5418  0 11:48 tty2     00:00:04 python3 /usr/share/ibus-anthy/engine/main.py --ibus
% kill -9 21492
% ps -ef | grep ibus-anthy
% /usr/libexec/ibus-engine-anthy --ibus
```
And deselect ibus-anthy and select ibus-anthy again and try the password lock.

**Comment by fujiwarat** [comment] 2017-05-23 06:14
No reply. closing.

**Closed by fujiwarat** 2017-05-23 06:14 UTC

**Comment by picsi** [comment] 2017-06-16 11:31
Hi there. Sorry for the delay. I don't seem to have that /libexec/ dir:

    [pizzaiolo@pizzaiolo ~]$ ps -ef | grep ibus-anthy
    pizzaio+  1139   746  0 08:11 ?        00:00:00 /usr/bin/python /usr/share/ibus-anthy/engine/main.py --ibus
    pizzaio+  5175  5164  0 08:22 pts/1    00:00:00 grep ibus-anthy
    [pizzaiolo@pizzaiolo ~]$ kill -9 1139
    [pizzaiolo@pizzaiolo ~]$ ps -ef | grep ibus-anthy
    pizzaio+  5582  5164  0 08:23 pts/1    00:00:00 grep ibus-anthy
    [pizzaiolo@pizzaiolo ~]$ /usr/libexec/ibus-engine-anthy --ibus
    bash: /usr/libexec/ibus-engine-anthy: Arquivo ou diretório não encontrado [file/dir not found]
    [pizzaiolo@pizzaiolo ~]$ sudo python /usr/share/ibus-anthy/engine/main.py --ibus

    (ibus-engine-anthy:6134): IBUS-CRITICAL **: ibus_bus_get_config: assertion 'ibus_bus_is_connected (bus)' failed
    ibus-config is not running or bus address is not correct.

    (ibus-engine-anthy:6134): IBUS-CRITICAL **: ibus_bus_get_config: assertion 'ibus_bus_is_connected (bus)' failed
    ibus-config is not running or bus address is not correct.
    Traceback (most recent call last):
      File "/usr/share/ibus-anthy/engine/main.py", line 192, in <module>
        main()
      File "/usr/share/ibus-anthy/engine/main.py", line 189, in main
        launch_engine(exec_by_ibus)
      File "/usr/share/ibus-anthy/engine/main.py", line 85, in launch_engine
        IMApp(exec_by_ibus).run()
      File "/usr/share/ibus-anthy/engine/main.py", line 71, in __init__
        self.__factory = factory.EngineFactory(self.__bus)
      File "/usr/share/ibus-anthy/engine/factory.py", line 61, in __init__
        bus.get_connection().signal_subscribe('org.freedesktop.DBus',
    AttributeError: 'NoneType' object has no attribute 'signal_subscribe'
    [pizzaiolo@pizzaiolo ~]$ /usr/lib
    lib/   lib32/ lib64/ 
    [pizzaiolo@pizzaiolo ~]$ /usr/lib/

**Comment by fujiwarat** [comment] 2017-06-16 13:28
&gt; 
(ibus-engine-anthy:6134): IBUS-CRITICAL **: ibus_bus_get_config: assertion 'ibus_bus_is_connected (bus)' failed
ibus-config is not running or bus address is not correct.

The error looks you didn't run ibus-daemon or you could open DISPLAY.
Please do not kill ibus-daemon.
Please run the above test locally in your desktop but not run via ssh.

&gt;  I don't seem to have that /libexec/ dir:

I guess your distro have ibus-engine-anthy in /usr/lib/ibus/*.

**Comment by picsi** [comment] 2017-06-16 13:46
Yes, apparently it's on /usr/lib64/ibus/*. 

Is there some verbose flag? I've experienced the lag but ibus did not output any errors.

**Comment by fujiwarat** [comment] 2017-06-19 02:21
> Is there some verbose flag? I've experienced the lag but ibus did not output any errors.

Because anthy is not activated yet when you launch ibus-engine-anthy by manual.
You have to select another engine once after run ibus-enigne-anthy and select anthy again.

**Comment by picsi** [comment] 2017-06-19 02:52
$ /usr/lib64/ibus/ibus-engine-anthy --ibus
    ## switching from default engine to anthy:
    Removing imported_words_ibus__zipcode
    Removing ibus__symbol
    Removing imported_words_ibus__oldchar
    Removing imported_words_ibus__era
    Removing imported_words_ibus__emoji
    ## to make sure, switching to default and then to anthy again:
    Removing imported_words_ibus__zipcode
    Removing ibus__symbol
    Removing imported_words_ibus__oldchar
    Removing imported_words_ibus__era
    Removing imported_words_ibus__emoji
    ## as a test, I open Anthy's preference box
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

I then opened a GUI password field and the lag happened, without any output on the terminal. This problem happens on Firefox as well as in GNOME in general.

**Comment by fujiwarat** [comment] 2017-06-19 05:03
Which desktop are you using? GNOME?
Can you attach a screenshot which can be taken by the desktop tool?

% gnome-screenshot -i

>  While in Portuguese and clicking in a password field,

Where is the password field?

>  as it hides the IME dropdown tool from GNOME's tray bar.

What is it and what is IME dropdown?
Do you mean your problem happens in password fields only?

> This problem happens on Firefox as well as in GNOME in general.

Where do your problem happens on Firefox? It's also good to attach a screenshot.

**Comment by picsi** [comment] 2017-06-19 14:35
This issue only happens in password fields. Any and all password fields on Firefox display this issue. I'm using GNOME, and I've attached a screenshot showing when that happens: 
![captura de tela de 2017-06-19 11-31-48](https://user-images.githubusercontent.com/23157217/27290272-39d3a130-54fc-11e7-993c-a3f15e9a2e25.png)

This is the IME dropdown: 
![captura de tela de 2017-06-19 11-33-53](https://user-images.githubusercontent.com/23157217/27290321-5c3e8bb8-54fc-11e7-9b0e-d7349a1c4aa0.png)

Interestingly, this issue doesn't happen when the terminal asks for my password (when I try to run something as root, for example).

**Comment by fujiwarat** [comment] 2017-06-21 02:39
> I then opened a GUI password field and the lag happened, without any output on the terminal. This problem happens on Firefox as well as in GNOME in general.

So after you see your problem, ibus-anthy is still alive?

> as it hides the IME dropdown tool from GNOME's tray bar.

I think this means ibus-daemon die.

It's good to check the process IDs of `*ibus*` with `ps` command before you hang and after you hang.

**Comment by picsi** [comment] 2017-06-25 13:07
Yes, all ibus-related processes (`ibus-daemon`, `ibus-dconf`, `ibus-engine-simple`, and `ibus-x11`) remain alive and well during and after this error.

**Comment by fujiwarat** [comment] 2017-06-26 03:03
I'm asking to describe the result of `ps` command.

**Comment by fujiwarat** [comment] 2017-06-28 02:32
Any updates?

**Comment by picsi** [comment] 2017-06-29 18:11
[pizzaiolo@pizzaiolo ~]$ ps -ef | grep ibus
    pizzaio+  1046   995  0 08:24 ?        00:00:21 ibus-daemon --xim --panel disable
    pizzaio+  1054  1046  0 08:24 ?        00:00:00 /usr/lib/ibus/ibus-dconf
    pizzaio+  1060     1  0 08:24 ?        00:00:03 /usr/lib/ibus/ibus-x11 --kill-daemon
    pizzaio+  1327  1046  0 08:24 ?        00:00:05 /usr/lib/ibus/ibus-engine-simple
    pizzaio+  1439  1046  0 08:25 ?        00:00:00 /usr/bin/python /usr/share/ibus-anthy/engine/main.py --ibus
    pizzaio+  4878  4854  0 15:02 pts/0    00:00:00 grep ibus
    [pizzaiolo@pizzaiolo ~]$ kill -9 1439
    [pizzaiolo@pizzaiolo ~]$ /usr/lib64/ibus/ibus-engine-anthy --ibus
    ^CTraceback (most recent call last):
      File "/usr/share/ibus-anthy/engine/main.py", line 192, in <module>
        main()
      File "/usr/share/ibus-anthy/engine/main.py", line 189, in main
        launch_engine(exec_by_ibus)
      File "/usr/share/ibus-anthy/engine/main.py", line 85, in launch_engine
        IMApp(exec_by_ibus).run()
      File "/usr/share/ibus-anthy/engine/main.py", line 78, in run
        self.__mainloop.run()
      File "/usr/lib/python3.6/site-packages/gi/overrides/GLib.py", line 589, in run
        raise KeyboardInterrupt
    KeyboardInterrupt
    [pizzaiolo@pizzaiolo ~]$ ps -ef | grep ibus
    pizzaio+  1046   995  0 08:24 ?        00:00:22 ibus-daemon --xim --panel disable
    pizzaio+  1054  1046  0 08:24 ?        00:00:00 /usr/lib/ibus/ibus-dconf
    pizzaio+  1060     1  0 08:24 ?        00:00:03 /usr/lib/ibus/ibus-x11 --kill-daemon
    pizzaio+  1327  1046  0 08:24 ?        00:00:05 /usr/lib/ibus/ibus-engine-simple
    pizzaio+  4942  4854  0 15:07 pts/0    00:00:00 grep ibus

I suspect this might be a distro-specific issue, as I'm now using Antergos and previously I used Parabola (both of which are Arch-based), but I didn't experience this issue while on Parabola 🤔

**Comment by fujiwarat** [comment] 2017-06-30 02:28
Why did you type Ctrl-c?
I'm asking the `ps` result when the system hang hides your IME dropdown menu.
I also doubt why IME drop down menu can be hidden. I.E. General panel activate menus can be open only when you click the panel icon by mouse. Also The password field can be open only when you click the a gnome-shell menu item. And the two modal dialogs cannot be coexist until one of them is closed.

And then your bug description is still broken for me.
