### ISSUE TITLE
ibus-extension-gtk3 eating cpu 

### ISSUE THREAD

**Issue by tokisuno** [ibus/ibus#2531] opened 2023-06-27 12:49 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux 6.3.9

Which desktop environment and version?: 
QTile

Which session type?: 
X11

Which application and version?: 
ibus-daemon

IBus version?: 
1.5.28

Issue description:
launching ibus makes my laptop fans go wild. it seems to hog approx 1 complete thread of CPU usage all the time
![image](https://github.com/ibus/ibus/assets/85533116/fea3cf3c-3904-4078-a9ad-86779132bb69)

Steps to reproduce:
1. Log in and out of system
1. run ibus-daemon -drxR
1. (negative) profit

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

(i was doing ibus-kill and then starting the daemon from there, same results).

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
![image](https://github.com/ibus/ibus/assets/85533116/c21069af-2e88-4d75-8461-e34bdac0b1c8)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
i only have one user account :')

**Comment by fujiwarat** [comment] 2023-06-30 07:50
Duplicate of #2471

**Closed by fujiwarat** 2023-06-30 07:50 UTC
