### ISSUE TITLE
I cant type french in Starcraft 2 and Blender

### ISSUE THREAD

**Issue by drmmwlt** [ibus/ibus#2598] opened 2024-01-05 15:11 UTC
Which distribution and version?: 
Manjaro Linux 23.1.2

Which desktop environment and version?: 
GNOME 45.2 

Which session type?: 
X11

Which application and version?: 
Blender 4.0.2
Starcraft 2 last update

IBus version?: 
IBus 1.5.29-rc2

Issue description:
These french characters doesnt work in blender and starcraft 2 : ² é è ç à ^ ù 

Steps to reproduce:
1. Open Starcraft 2 or Blender
1. Type  ² é è ç à ^ ù with your keyboard

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

**Comment by fujiwarat** [comment] 2024-01-06 15:39
Can you describe how the characters do not work?

**Comment by drmmwlt** [comment] 2024-01-06 16:38
sure, i press on them :  in my desktop or any app, the letters appears for exemple a search bar, and they make the action. 

But in Blender or starcraft 2, there is just no action : the letters doesnt appear anywhere, for exemple in a text box. Or in stracraft 2 my hotkeys (some of thses characters are my hotkeys) makes no action at all and they dont appear in anything like a message box. 

But what is strange in stracraft 2 : its regnognizing a combination with them (for exemple ctrl + ² , or alt + é) but not the key alone (² or é or ^, etc). 

And i've found that i need to type "alt + ²" to get " ² ", and not just type the key " ² " to get " ² " (same thing in blender).  
But yeah its changing badly my whole keyboard experience ..

**Comment by fujiwarat** [comment] 2024-01-07 01:43
> But what is strange in stracraft 2 : its regnognizing a combination with them (for exemple ctrl + ² , or alt + é) but not the key alone (² or é or ^, etc).

Which keyboard layout has "² " and "é" keys?
Did you see your problem with old IBus versions?

**Comment by drmmwlt** [comment] 2024-01-08 03:34
![keyboard not working-b](https://github.com/ibus/ibus/assets/66220502/304f5128-a8b6-4d72-a86c-83dd2b222df3)

here is a picture of my kb, i draw in red the letters that arent working anymore. 
No, there isnt any issue 2-3 months ago

**Comment by fujiwarat** [comment] 2024-01-08 09:12
So which language keyboard layout do you use? I don't ask you the screenshot.
https://en.wikipedia.org/wiki/Keyboard_layout

> No, there isnt any issue 2-3 months ago

Which ibus version did you use 2-3 months ago?

**Comment by drmmwlt** [comment] 2024-01-08 16:38
Ah sorry i didnt understood the question, i use my keyboard as AZERTY french.

i think it was 1.5.28-4  when it worked, here is my last ibus update : 
[2023-12-10T16:54:12+0100] [ALPM] upgraded ibus (1.5.28-4 -> 1.5.29-2)

**Comment by fujiwarat** [comment] 2024-01-10 07:40
OK, I see French AZERTY has "² " (U+00B2 )
Blender seems to use the multibyte characters as control keys and the issue is fixed in #2588 .

**Closed by fujiwarat** 2024-01-10 07:40 UTC
