### ISSUE TITLE
ibus not respecting activation shortcuts or preferences in ibus-setup

### ISSUE THREAD

**Issue by honken** [ibus/ibus#2018] opened 2018-06-18 09:31 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Arch kernel 4.17.2-1

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 3.28.2-1

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Any

IBus version?: 
(Run `ibus version`)
1.5.18
Issue description:
Settings in ibus-setup do not apply.  super-space does not change me from en-us to anthy.  In fact the only way to turn on anthy is via the "ibus engine anthy" command.  Once switched via aforementioned terminal command, the options for anthy do not reflect either, i.e. ctrl+J (or my customization zenkaku/hankaku) for on_off does nothing.

Not sure if related but running "ibus read-config" returns the following error:

(process:15096): GLib-GIO-ERROR **: 18:04:10.394: Settings schema 'org.freedesktop.ibus.general.panel' is not installed

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
I see the below output in journalctl:

6月 18 18:10:21 exps13arch kernel: traps: ibus[15879] trap int3 ip:7f98ca018ed2 sp:7fff25c84760 error:0 in libglib-2.0.so.0.5600.1[7f98c9fc7000+115000]
 6月 18 18:10:21 exps13arch systemd[1]: Started Process Core Dump (PID 15882/UID 0).
-- Subject: Unit systemd-coredump@5-15882-0.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-coredump@5-15882-0.service has finished starting up.
-- 
-- The start-up result is RESULT.
 6月 18 18:10:22 exps13arch systemd-coredump[15883]: Process 15879 (ibus) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 15879:
                                                      #0  0x00007f98ca018ed2 n/a (libglib-2.0.so.0)
                                                      #1  0x00007f98ca019f7d g_log_default_handler (libglib-2.0.so.0)
                                                      #2  0x00007f98ca01a21f g_logv (libglib-2.0.so.0)
                                                      #3  0x00007f98ca01a3a0 g_log (libglib-2.0.so.0)
                                                      #4  0x00007f98ca6453d2 n/a (libgio-2.0.so.0)
                                                      #5  0x00007f98ca2f359b n/a (libgobject-2.0.so.0)
                                                      #6  0x00007f98ca2f5180 g_object_new_valist (libgobject-2.0.so.0)
                                                      #7  0x00007f98ca2f550a g_object_new (libgobject-2.0.so.0)
                                                      #8  0x000056544cb7a2fa n/a (ibus)
                                                      #9  0x000056544cb7ab24 n/a (ibus)
                                                      #10 0x00007f98c9a1006b __libc_start_main (libc.so.6)
                                                      #11 0x000056544cb7872a n/a (ibus)
                                                      
                                                      Stack trace of thread 15881:
                                                      #0  0x00007f98c9ae5531 __clone (libc.so.6)
                                                      #1  0x0000000000000000 n/a (n/a)
-- Subject: Process 15879 (ibus) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 15879 (ibus) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

I don't see any icon indicating the active language but I guess this is due to GNOME removing the classic tray? (sorry first time I've used ibus in a year or so). Many thanks

**Comment by fujiwarat** [comment] 2018-06-18 09:51
`ibus-setup` is not used in GNOME desktop.
Please use `gnome-control-center region` instead.

> Not sure if related but running "ibus read-config" returns the following error:

It was a bug that I also noticed recently and fixed in https://github.com/ibus/ibus/commit/ddc2284200971141947a37057356b4bbd84be7ce

> 6月 18 18:10:22 exps13arch systemd-coredump[15883]: Process 15879 (ibus) of user 1000 dumped core.

I guess Arch provides the debug packages of ibus and glibs.
If you'd like to report the SEGV issue, please install the debug packages and take the stack trace again.

 #0  0x00007f98ca018ed2 n/a (libglib-2.0.so.0)

Otherwise the lines does not give the information with detail.

**Closed by fujiwarat** 2018-06-18 09:51 UTC

**Comment by honken** [comment] 2018-06-18 12:39
I did find that previously but there are zero options on that page (the keyboard icon on that page shows a picture of the keyboard in front me of me). Super-space switches between "en" and "ja" mode but neither actually gives me actual Japanese input. Expected key combos (ctrl+j/zkhk key/alt+shift l, alt+zkhk) seem to do nothing in ja mode.

![screenshot from 2018-06-18 21-30-06](https://user-images.githubusercontent.com/794951/41535865-cc7baef4-733e-11e8-8829-1f581efdf410.png)

Many thanks

**Comment by honken** [comment] 2018-06-18 12:52
OK disregard the last note, I get it now, by adding Japanese (Anthy) and then removing English (US) to the above screen, I can finally switch between the two on a ja keyboard using super-space. Though the "Key Binding" settings within Anthy preferences still seem to do nothing. In the ideal case I woud just have "Japanese (Anthy)" in GNOME Input Sources and then use the circle_input_mode shortcut to switch between "hiragana" and "latin" input mode.

![screenshot from 2018-06-18 21-46-51](https://user-images.githubusercontent.com/794951/41536629-246dc3de-7341-11e8-8b01-52fbaee8f8fc.png)

Hope that makes sense?! Many thanks

**Comment by honken** [comment] 2018-06-19 06:43
1. I do not see any ibus panel menus (docked or floating) where the input mode can be changed. Only menu is the GNOME built-in which has no options:
![screenshot from 2018-06-19 15-30-40](https://user-images.githubusercontent.com/794951/41580687-b7a0c706-73d6-11e8-80c5-41a3f516b632.png)

2. I just tried but none of the circle_input_mode shortcuts work in env GTK_IM_MODULE=ibus gedit - I can't switch out of hiragana input in Anthy mode
3. I spun up a new user account and same issue

Many thanks

**Comment by fujiwarat** [comment] 2018-06-19 07:58
I guess you have not installed IBus GTK3 module.
Can you check the strace log?
```
% which strace
/usr/bin/strace
% strace gedit |& grep immodule
```

**Comment by honken** [comment] 2018-06-19 08:11
I get the following output:
```
[edo@exps13arch ~]$ which strace
/usr/bin/strace
[edo@exps13arch ~]$ strace gedit |& grep immodule
openat(AT_FDCWD, "/usr/lib/gtk-3.0/3.0.0/immodules.cache", O_RDONLY) = 13
stat("/usr/lib/gtk-3.0/3.0.0/immodules/im-ibus.so", {st_mode=S_IFREG|0755, st_size=30512, ...}) = 0
openat(AT_FDCWD, "/usr/lib/gtk-3.0/3.0.0/immodules/im-ibus.so", O_RDONLY|O_CLOEXEC) = 13
^C
```
Many thanks

**Comment by fujiwarat** [comment] 2018-06-19 09:04
OK, seems gedit loads im-ibus.so correctly in your box.
Since gnome-shell restarts ibus-daemon automatically, I think a wrapper to get the verbose log.
```
% sudo mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.orig
% sudo vi /usr/bin/ibus-daemon
% cat /usr/bin/ibus-daemon
#!/bin/sh
${0}.orig --verbose $@
% sudo chmod 755 /usr/bin/ibus-daemon
```

When you log into the GNOME session and switch "Japanese" and "Japanese (Anthy)", do you see any messages with `journalctrl` ?

**Comment by honken** [comment] 2018-06-19 09:22
I get the following every time I switch:
```

6月 19 18:21:22 exps13arch gnome-shell[17243]: Object Shell.GenericContainer (0x55966c5db080), has been already finalized. Impossible to get any property from it.
 6月 19 18:21:22 exps13arch gnome-shell[17243]: Object Shell.GenericContainer (0x55966c5db080), has been already finalized. Impossible to set any property to it.
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: == Stack trace for context 0x559669b39000 ==
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #0 0x7ffccc8ebb70 b   resource:///org/gnome/shell/ui/tweener.js:73 (0x7f30140c7cd0 @ 9)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #1 0x7ffccc8ebc10 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7f30140c7f78 @ 36)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #2 0x7ffccc8ebcb0 b   resource:///org/gnome/shell/ui/tweener.js:92 (0x7f30140c7de0 @ 52)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #3 0x7ffccc8ec850 I   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7f30140d2918 @ 54)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #4 0x7ffccc8ec9a0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7f30140d29a0 @ 1626)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #5 0x7ffccc8eca50 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7f30140d2a28 @ 100)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #6 0x7ffccc8ecae0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7f30140d2ab0 @ 10)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #7 0x7ffccc8ecb60 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f30140cff78 @ 386)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #8 0x7ffccc8ecc10 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7f30140cf5e8 @ 159)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #9 0x7ffccc8ecc80 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30140b5de0 @ 71)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #10 0x7ffccc8ecc80 I   resource:///org/gnome/shell/ui/tweener.js:182 (0x7f30140cf560 @ 15)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: == Stack trace for context 0x559669b39000 ==
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #0 0x7ffccc8ebb70 b   resource:///org/gnome/shell/ui/tweener.js:80 (0x7f30140c7cd0 @ 82)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #1 0x7ffccc8ebc10 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7f30140c7f78 @ 36)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #2 0x7ffccc8ebcb0 b   resource:///org/gnome/shell/ui/tweener.js:92 (0x7f30140c7de0 @ 52)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #3 0x7ffccc8ec850 I   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7f30140d2918 @ 54)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #4 0x7ffccc8ec9a0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7f30140d29a0 @ 1626)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #5 0x7ffccc8eca50 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7f30140d2a28 @ 100)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #6 0x7ffccc8ecae0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7f30140d2ab0 @ 10)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #7 0x7ffccc8ecb60 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f30140cff78 @ 386)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #8 0x7ffccc8ecc10 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7f30140cf5e8 @ 159)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #9 0x7ffccc8ecc80 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30140b5de0 @ 71)
 6月 19 18:21:22 exps13arch org.gnome.Shell.desktop[17243]: #10 0x7ffccc8ecc80 I   resource:///org/gnome/shell/ui/tweener.js:182 (0x7f30140cf560 @ 15)

```
Many thanks

**Comment by fujiwarat** [comment] 2018-06-19 09:58
Did you delete all shortcut keys of emoji shortcut keys on `ibus-setup` -> "Emoji" -> "Emoji choice" ?

```
% gsettings get org.freedesktop.ibus.panel.emoji hotkey
['<Control><Shift>e']
% gsettings reset org.freedesktop.ibus.panel.emoji hotkey
```

**Comment by honken** [comment] 2018-06-19 10:10
I haven't touched the emoji settings but ran it just now, I guess reset changes it back to default?

```
> [edo@exps13arch ~]$ gsettings get org.freedesktop.ibus.panel.emoji hotkey
> ['<Control><Shift>e']
> [edo@exps13arch ~]$ gsettings reset org.freedesktop.ibus.panel.emoji hotkey
> [edo@exps13arch ~]$ gsettings get org.freedesktop.ibus.panel.emoji hotkey
> ['<Control><Shift>e']
```

**Comment by fujiwarat** [comment] 2018-06-20 03:29
OK, I think the emoji setting does not cause any problem.

From your journalctl log, tweener always failed but I don't know if it's relative with your problem.
Since gnome-shell runs ibus-daemon automatically, I'd ask you to run ibus-daemon by manual forcibly below.
I think now your original ibus-daemon is /usr/bin/ibus-daemon.orig and the wrapper is /usr/bin/ibus-daemon as I asked the test in https://github.com/ibus/ibus/issues/2018#issuecomment-398328667
```
% file /usr/bin/ibus-daemon*
/usr/bin/ibus-daemon:      POSIX shell script
/usr/bin/ibus-daemon.orig: ELF 64-bit LSB shared object, x86-64

% ps -ef | grep ibus-daemon
edo  3579  2194  0 12:20 pts/3    00:00:00 /bin/sh /usr/bin/ibus-daemon --xim --panel disable
edo  3581  3579  0 12:20 pts/3    00:00:00 /usr/bin/ibus-daemon.orig --verbose --xim --panel disable
edo  3590  3581  0 12:20 pts/3    00:00:00 /usr/libexec/ibus-dconf
edo  3592  3581  0 12:20 pts/3    00:00:00 /usr/libexec/ibus-ui-gtk3
edo  3595  3581  0 12:20 pts/3    00:00:00 /usr/libexec/ibus-extension-gtk3
edo  3597     1  0 12:20 pts/3    00:00:00 /usr/libexec/ibus-x11 --kill-daemon
edo 3601  1518  0 12:20 ?        00:00:00 /usr/libexec/ibus-portal
edo  3626  3581  0 12:20 pts/3    00:00:00 python3 /usr/share/ibus-anthy/engine/main.py --ibus
edo  3657  3581  0 12:20 pts/3    00:00:00 /usr/libexec/ibus-engine-simple
```

After you confirmed ibus-daemon is running in GNOME, let's remove the wrapper script and restart ibus-daemon.orig by manual.

```
% sudo rm  /usr/bin/ibus-daemon
% ibus exit
% ps -ef | grep ibus
% ibus-daemon --verbose --xim --panel disable
```

And can you reproduce your problem?
Do you see any warnings on the terminal emulator of ibus-daemon or journalctrl?

**Comment by honken** [comment] 2018-06-20 05:54
Hrm not seeing any difference in behavior between the two...

```
[edo@exps13arch ~]$ file /usr/bin/ibus-daemon*
/usr/bin/ibus-daemon:      POSIX shell script, ASCII text executable
/usr/bin/ibus-daemon.orig: ELF 64-bit LSB pie executable x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=55095281dfa66a0729fb1265e33abb2eeb4b334a, stripped
[edo@exps13arch ~]$ ps -ef | grep ibus-daemon
edo       2140     1  0  6月19 ?      00:00:07 /usr/bin/ibus-daemon.orig --verbose -drx --verbose
edo       9035  2562  0 14:49 pts/0    00:00:00 grep ibus-daemon
[edo@exps13arch ~]$ sudo rm /usr/bin/ibus-daemon
[edo@exps13arch ~]$ ibus exit
[edo@exps13arch ~]$ ps -ef | grep ibus
edo       9053  2562  0 14:50 pts/0    00:00:00 grep ibus
[edo@exps13arch ~]$ ibus-daemon --verbose --xim --panel disable
bash: ibus-daemon: command not found  
[edo@exps13arch ~]$ sudo mv /usr/bin/ibus-daemon.orig  /usr/bin/ibus-daemon
[edo@exps13arch ~]$ ibus-daemon --verbose --xim --panel disable

^C

```

**Comment by fujiwarat** [comment] 2018-06-20 07:41
> edo       2140     1  0  6月19 ?      00:00:07 /usr/bin/ibus-daemon.orig --verbose -drx --verbose

Who run ibus-daemon before you run `ibus exit` ?
I expected gnome-shell run ibus-daemon but seems not in your case because '-drx' is not run by gnome-shell.
Sorry, I meant `ps -ef | grep ibus` instead of `ps -ef | grep ibus-daemon`.

Could you try again after you log in GNOME desktop?
Now the original ibus-daemon is /usr/bin/ibus-daemon as you renamed.
```
% ps -ef | grep ibus
% sudo mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.orig
% ibus exit
% ps -ef | grep ibus
% ibus-daemon.orig --verbose --xim
```

**Comment by fujiwarat** [comment] 2018-06-21 03:58
>  6月 20 20:25:11 exps13arch gnome-shell[10337]: ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed

The last line is not expected by me.
Can you check if ibus-daemon and gedit accesses the same file?
```
% strace ibus-daemon.orig --xim --verbose --panel disable |& grep ibus/bus
openat(AT_FDCWD, "$HOME/.config/ibus/bus/1233704605d44edd9b93f3751ba7a73f-unix-0", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 9
```

```
% strace gedit |& grep ibus/bus
openat(AT_FDCWD, "$HOME/.config/ibus/bus/1233704605d44edd9b93f3751ba7a73f-unix-0", O_RDONLY) = 15
openat(AT_FDCWD, "$HOME/.config/ibus/bus/1233704605d44edd9b93f3751ba7a73f-unix-0", O_RDONLY) = 16
```

```
% cat $HOME/.config/ibus/bus/1233704605d44edd9b93f3751ba7a73f-unix-0
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-ou8oTviG,guid=12d399f69bee63bb362ddac85b2b2126
IBUS_DAEMON_PID=25425

% ibus address
unix:abstract=/tmp/dbus-ou8oTviG,guid=12d399f69bee63bb362ddac85b2b2126
```

**Comment by honken** [comment] 2018-06-23 13:03
Output below, many thanks

```
[edo@exps13arch bin]$ strace ibus-daemon.orig --xim --verbose --panel disable |& grep ibus/bus
openat(AT_FDCWD, "/home/edo/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0", O_RDONLY) = 3
access("/usr/var/cache/ibus/bus/registry", F_OK) = -1 ENOENT (No such file or directory)
access("/home/edo/.cache/ibus/bus/registry", F_OK) = 0
openat(AT_FDCWD, "/home/edo/.cache/ibus/bus/registry", O_RDONLY) = 3
access("/home/edo/.config/ibus/bus", F_OK) = 0
stat("/home/edo/.config/ibus/bus", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
unlink("/home/edo/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0") = 0
openat(AT_FDCWD, "/home/edo/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 9
^C
[edo@exps13arch bin]$ strace gedit |& grep ibus/bus
access("/home/edo/.config/ibus/bus", F_OK) = 0
stat("/home/edo/.config/ibus/bus", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
chmod("/home/edo/.config/ibus/bus", 0700) = 0
stat("/home/edo/.config/ibus/bus", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
inotify_add_watch(12, "/home/edo/.config/ibus/bus", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = 2
openat(AT_FDCWD, "/home/edo/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0", O_RDONLY) = 13
[edo@exps13arch bin]$ ibus-daemon.orig --verbose &
[1] 9126
[edo@exps13arch bin]$ strace gedit |& grep ibus/bus
access("/home/edo/.config/ibus/bus", F_OK) = 0
stat("/home/edo/.config/ibus/bus", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
chmod("/home/edo/.config/ibus/bus", 0700) = 0
stat("/home/edo/.config/ibus/bus", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
inotify_add_watch(12, "/home/edo/.config/ibus/bus", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = 2
openat(AT_FDCWD, "/home/edo/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0", O_RDONLY) = 13
openat(AT_FDCWD, "/home/edo/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0", O_RDONLY) = 14
^C
[edo@exps13arch bin]$ cat $HOME/.config/ibus/bus/1233704605d44edd9b93f3751ba7a73f-unix-0
cat: /home/edo/.config/ibus/bus/1233704605d44edd9b93f3751ba7a73f-unix-0: No such file or directory
[edo@exps13arch bin]$ cat $HOME/.config/ibus/bus/9e3e19d11c9b4fd2b6bffdee90842203-unix-0 
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-H3PgsbD8,guid=12010113a39fc48f5ac5f70d5b2e4334
IBUS_DAEMON_PID=9126
[edo@exps13arch bin]$ ibus address
unix:abstract=/tmp/dbus-H3PgsbD8,guid=12010113a39fc48f5ac5f70d5b2e4334
```

**Comment by honken** [comment] 2018-06-25 14:43
Thanks, output below.  Japanese input was working in gedit, but the system tray was still showing default "ja" (as in, latin input with JA keyboard) instead of あ like it normally does.  Still no ibus panel menus and the on/off, cycle inputs shortcuts were not working as usual.  Many thanks

```
[edo@exps13arch python]$ cat a.py 
#!/usr/bin/python
from gi import require_version as gi_require_version
gi_require_version('IBus', '1.0')
from gi.repository import IBus
bus = IBus.Bus()
print(bus.is_connected())

[edo@exps13arch python]$ python a.py 
False
[edo@exps13arch python]$ ibus-daemon.orig --verbose &
[1] 19268
[edo@exps13arch python]$ python a.py 
True
[edo@exps13arch python]$ ibus engine xkb:us::eng
[edo@exps13arch python]$ ibus engine
xkb:us::eng
[edo@exps13arch python]$ ibus engine anthy
[edo@exps13arch python]$ ibus engine
anthy
[edo@exps13arch python]$ gedit
[edo@exps13arch python]$ ibus engine xkb:us::eng
[edo@exps13arch python]$ ibus exit
[edo@exps13arch python]$ 
(ibus-daemon.orig:19268): GLib-WARNING **: 23:38:39.944: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.

[1]+  Done                    ibus-daemon.orig --verbose


```

**Comment by honken** [comment] 2018-06-26 03:42
For case 1 I get the below:

```
[edo@exps13arch ~]$ env GTK_IM_MODULE=gtk-im-context-simple XMODIFIERS=@im=none xterm & xterm% ps -ef | gnome-shell
[1] 4515
bash: xterm%: command not found
org.gnome.Shell already exists on bus and --replace not specified
```

For case 2, attaching the file now.  Many thanks

**Comment by honken** [comment] 2018-06-26 03:43
[ibus.log](https://github.com/ibus/ibus/files/2135478/ibus.log)

**Comment by fujiwarat** [comment] 2018-06-26 04:38
> [edo@exps13arch ~]$ env GTK_IM_MODULE=gtk-im-context-simple XMODIFIERS=@im=none xterm & xterm% ps -ef | gnome-shell


You should not combine all lines.

**Comment by fujiwarat** [comment] 2018-06-26 04:40
`another-terminal%` means a terminal prompt on another terminal application.

Thanks.

**Comment by honken** [comment] 2018-06-26 05:07
Haha oops sorry:

```
[edo@exps13arch ~]$ ibus exit
Can't connect to IBus.
[edo@exps13arch ~]$ env GTK_IM_MODULE=gtk-im-context-simple XMODIFIERS=@im=none xterm &
[1] 12303
```

Then in xterm:
```
ps -ef | grep gnome-shell
edo       4176  4128  1 12:40 tty1     00:00:54 /usr/bin/gnome-shell
edo       4194   511  0 12:40 ?        00:00:00 /usr/lib/gnome-shell-calendar-server
edo       4688  4550  0 12:40 tty1     00:00:00 /usr/bin/python /usr/bin/chrome-gnome-shell /usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json chrome-gnome-shell@gnome.org
edo      12433 12305  0 14:04 pts/1    00:00:00 grep gnome-shell
```
Many thanks

**Comment by fujiwarat** [comment] 2018-06-26 05:50
I mean after you run `ps` command, you will connect to the process with `gdb` command on xterm prompt and run ibus-daemon.orig on gnome-terminal prompt and will get the stack on gdb and run `where` on gdb promt.

Sorry for my subtle commen.

**Comment by fujiwarat** [comment] 2018-06-26 06:12
Seems to SetGlobalEngine for ibus-anthy is succeeded in your box.
Which version of ibus-anthy is used?
The latest is 1.5.10; https://github.com/ibus/ibus-anthy/releases

**Comment by honken** [comment] 2018-06-26 07:55
Right, that's the version I have:
community/ibus-anthy 1.5.10-1 [installed]

Back to gdb, I get this:
```
[edo@exps13arch ~]$ ps -ef | grep gnome-shell
edo       4194   511  0 12:40 ?        00:00:00 /usr/lib/gnome-shell-calendar-server
edo      21571 21541 14 16:49 tty1     00:00:06 /usr/bin/gnome-shell
edo      21938 21788  0 16:49 tty1     00:00:00 /usr/bin/python /usr/bin/chrome-gnome-shell /usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json chrome-gnome-shell@gnome.org
edo      21960   511  0 16:49 ?        00:00:00 /usr/bin/python /usr/bin/chrome-gnome-shell --gapplication-service
edo      22233 22187  0 16:50 pts/2    00:00:00 grep gnome-shell
[edo@exps13arch ~]$ gdb --pid 21571
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 21571
ptrace: Operation not permitted.
```

**Comment by honken** [comment] 2018-06-26 08:03
If I try the above with sudo it crashes X...

**Comment by fujiwarat** [comment] 2018-06-26 10:13
OK, Which version of ibus-anthy is used?
The latest is 1.5.10; https://github.com/ibus/ibus-anthy/releases

**Comment by fujiwarat** [comment] 2018-06-26 11:00
Can you check the gsettings are installed?
```
% gsettings list-schemas | grep anthy
org.freedesktop.ibus.engine.anthy.common
org.freedesktop.ibus.engine.anthy.dict
org.freedesktop.ibus.engine.anthy.thumb
org.freedesktop.ibus.engine.anthy.shortcut
org.freedesktop.ibus.engine.anthy.kana-typing-rule
org.freedesktop.ibus.engine.anthy.romaji-typing-rule
org.freedesktop.ibus.engine.anthy.thumb-typing-rule
% for a in `gsettings list-schemas | grep anthy`
do
gsettings list-recursively $a
done
```

**Comment by honken** [comment] 2018-06-26 23:16
Output below, many thanks!

```
[edo@exps13arch ~]$ gsettings list-schemas | grep anthy
org.freedesktop.ibus.engine.anthy.romaji-typing-rule
org.freedesktop.ibus.engine.anthy.kana-typing-rule
org.freedesktop.ibus.engine.anthy.thumb-typing-rule
org.freedesktop.ibus.engine.anthy.common
org.freedesktop.ibus.engine.anthy.thumb
org.freedesktop.ibus.engine.anthy.dict
org.freedesktop.ibus.engine.anthy.shortcut
```

[list-schemas.txt](https://github.com/ibus/ibus/files/2139300/list-schemas.txt)

**Comment by fujiwarat** [comment] 2018-06-27 07:41
Now I understood your problem.
I didn't assume not to show input modes in ibus-anthy.
The workaround is:
1. Run /usr/lib*/ibus-setup-anthy (The install path of ibus-setup-anthy depends on Arch distribution)
2. Find "General" tab -> "Menu Visibility on Status Icon" -> "Input mode" check button and enable the check button and close the dialog.
3. Log into GNOME session again

I also recommend to enable "Preferences - Anthy" check button so that you can launch the dialog from gnome-shell's panel menu.

**Comment by fujiwarat** [comment] 2018-06-27 07:54
From https://github.com/ibus/ibus/issues/2018#issuecomment-398291824
> 3. I spun up a new user account and same issue

I think your issue should not happen with a new user account.

**Comment by honken** [comment] 2018-07-02 23:30
YES! zk/hk button finally swtiches between hiragana/latin input - thank you so much! (sorry for the delay in response)

Fwiw re: new user account, I definitely did create a new temp user account at one point during troubleshooting and had the same issue.  Thanks again!

**Comment by honken** [comment] 2018-07-02 23:32
I note the status icon disappears completely if you *only* have anthy configured as an input source in GNOME preferences, though I guess that's more of an issue on their end.  hk/zk key still works to switch input, you just can't see the icon.  Anyway, thanks a lot!

**Comment by fujiwarat** [comment] 2018-07-03 02:59
> I note the status icon disappears completely if you only have anthy configured as an input source in GNOME preferences,

That's an expected behavior by gnome-shell if you have only one input sources.

> Fwiw re: new user account, I definitely did create a new temp user account at one point during troubleshooting and had the same issue

But the shortcut key should works if you customize the ibus-anthy setting.

**Comment by honken** [comment] 2018-07-03 05:20
I see, thanks again!
