### ISSUE TITLE
direction-changed signal isn't fired when switching from arabic (qwerty) to Japanese (mozc) or anthy

### ISSUE THREAD

**Issue by makotokato** [ibus/ibus#1848] opened 2016-04-04 03:27 UTC
###### Env
* Fedora 23
  * ibus-gtk3-1.5.11-1-fc23.x86_64
  * ibus-anthy-1.5.8-1-fc23.x86_64
  * ibus-moz-2.17.2077.102-5-fc23.x86_64
  * ibus-1.5.11-1.fc23.x86_64

###### Step
1. Setup the following language.
    English (US) / Japanese (Anthy) / Japanese (Mozc) / Arabic (qwerty)

2. Compile https://bugzilla.gnome.org/show_bug.cgi?id=763853 's test program.
3. Run this.
4. Switch keyboard from English (US) to Arabic (qwetry).  Then "direction-changed" is logged.
5. Switch keyboard from Arabic (qwetry) to Japanese (Anthy) or Japanese (Mozc).

###### Result
"direction-changed" isn't fired.

###### Expected Result
"direction-changed" should be fired.

###### Note
This occurs on ibus-pinyin too.

**Comment by fujiwarat** [comment] 2016-04-04 08:04
Because ibus-anthy does not change the XKB keymaps by default.
ibus-anthy follows the session XKB keymaps and ibus-mozc and ibus-libpinyin too.
ibus-m17n would change the XKB keymaps by default because it works as keyboards instead of input methods.

You could confirm "layout" tag in /usr/share/ibus/component/*.xml while ibus-anthy refers another xml file in the xml file.
Closing not a bug.

**Closed by fujiwarat** 2016-04-04 08:04 UTC

**Comment by makotokato** [comment] 2016-04-04 09:34
Does this mean that Fedora's bug or gtk's bug?

**Comment by makotokato** [comment] 2016-04-04 09:40
Also, filed https://bugzilla.gnome.org/show_bug.cgi?id=764577

**Comment by fujiwarat** [comment] 2016-04-04 10:16
As I noted, some of IBus engines do not change the XKB keymaps so I think it's the expected result not to emit any signals from GdkKeymap.
Or do you mean you customized the engines to have a specific keymap?

**Comment by makotokato** [comment] 2016-04-12 01:15
This issue is ibus only as long as I test.  Fcitx and uim works fine that I except.
I think that best way is that new IM protocol for direction for GTK.  If im module is found, it should use new protocol.

Also, I filed another bug as https://bugzilla.gnome.org/show_bug.cgi?id=763853 that depends on ibus.  After I setup clean debian installation, I will file bug to this as new issue.

**Comment by fujiwarat** [comment] 2016-04-13 06:20
Is it a bug for fcitx and uim?
I have no reason to emit any signals if the keymap is not changed.
I even think GdkKeymap is not required in either GNOME desktop or IBus.

**Comment by makotokato** [comment] 2016-04-13 07:46
Env ... Debian/sid

When using uim, it doesn't allow from arabic to Japanese IM.  So this issue doesn't occur
When using fcitx, 'direction-changed' signal occurs.

This issue is only ibus.

**Comment by fujiwarat** [comment] 2016-04-13 07:54
Actually I don't understand your real problem.
IBus Japanese IME can take Arabic layout by default.
I.E.
When siwtch jp layout to ja IME, ja IME takes jp layout.
When switch us(drovak) to ja IME, ja IME takes us(dvorak) keymap.
When switch fr layout to ja IME, ja IME takes fr layout.

If the user uses multiple keymaps, some of ja IME provides the keymap customization in the setting dialog.
I think all is the expected result.
That's why I asked you customized the engines to have a specific keymap.

**Comment by makotokato** [comment] 2016-04-13 08:05
I don't talk about Xlib, keymap and X architecture.

I talk about https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget-direction-changed

Real problem is 'direction-changed' signal on GTK3 is fired when switching from Arabic to Japanese IM with ibus.  Does Japanese IM (mozc or anthy) is RTL layout?

Also, If not using ibus, this issue doesn't occur.   Why doesn't ibus fix?

**Comment by fujiwarat** [comment] 2016-04-13 08:56
> Does Japanese IM (mozc or anthy) is RTL layout?

Yes by default

**Comment by makotokato** [comment] 2016-04-13 09:00
If Yes, Japanese should be RTL language instead of LTR language.

**Comment by makotokato** [comment] 2016-04-13 09:02
(I don't talk about X keymap).  As General language, Japaense is LTR, Right?

**Comment by fujiwarat** [comment] 2016-04-13 09:06
>  As General language, Japaense is LTR, Right?

No, Ja IME is not JP keymap. Ja IME supports both LTR and RTL.

**Comment by makotokato** [comment] 2016-04-13 09:10
How do you input RTL by Japnese IM (ex. ibus-mozc) ?

**Comment by fujiwarat** [comment] 2016-04-13 09:11
You can type ASCII with ja IME.

**Comment by makotokato** [comment] 2016-04-13 09:14
It can input RTL langauge by alt+grp when using Intl US or Europa keyboard.  (not RTL layout).   But GTK doesn't fire 'direction-changed' signal.

So you say "(ibus) Ja IME supports both LTR and RTL", GTK should fire "direction-changed' signal.

**Comment by fujiwarat** [comment] 2016-04-13 09:17
I think text direction is decided by the typed characters but not keymaps.
I think it's better to handle the signal by the text widget of GtkEntry or GtkTextBuffer but not GtkWidget.

**Comment by fujiwarat** [comment] 2016-04-13 09:37
BTW, ibus-anthy outputs Arabic but not Japanese because it does not have the conversion table between Arabic char and Hiragana and the RTL is right.

**Comment by fujiwarat** [comment] 2016-04-13 09:49
BTW, I asked your real problem, it means what is the trouble if you cannot receive the  "direction-changed" signal.

**Comment by makotokato** [comment] 2016-06-17 10:27
Gecko changes caret if current keyboard is RTL keyboard.

Since direction-changed isn't fired correctly using ibus's input method, we cannot detect whether keyboard language is changed from/to RTL by signal on all situation.  Content process won't call GTK API as possible due to sandbox, so browser process sends information to content process when changed by signal.  But of course, I don't want to poll data change by timer...

Windows and macOS can detect keyboard language is changed (included input method) by protocol / window message.  But GTK doesn't have it and have only direction changed.

**Comment by fujiwarat** [comment] 2016-06-20 02:10
If the keyboard layout is 'ara', the signal is not emitted because the signal is emitted only with the keymaps but not input methods.
The right fix is to provide the customization of keymaps in each input methods likes ibus-anthy.
Otherwise the sysadmin can change the 'layout' tag in /usr/share/ibus/component/*.xml by manual.
