### ISSUE TITLE
"Type 'h' is not supported" in GTK4 apps after composing

### ISSUE THREAD

**Issue by IBBoard** [ibus/ibus#2596] opened 2024-01-02 10:32 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
openSUSE Tumbleweed

Which desktop environment and version?: 
GNOME 45.2

Which session type?: 
X11

Which application and version?: 
GTK4 apps (e.g. gtk4-widget-factory)

IBus version?: 
1.5.29-rc2

Issue description:
Whenever the compose key is used and the composing of a character is finished in a GTK4 app (e.g `Compose` + `a` + `a` to get `å`), the message `IBUS-WARNING **: 10:03:00.025: ibus_input_context_post_process_key_event: Type 'h' is not supported.` is printed to the terminal and all but the last letter of the pre-edit text is left behind.

Steps to reproduce:
1. Open `gtk3-widget-factory`
1. Click into a text box
1. Press `Compose` + `a` + `a`
1. Expected: `å`. Actual: `å`
1. Open `gtk4-widget-factory`
1. Click into a text box
1. Press `Compose` + `a` + `a`
1. Expected: `å`. Actual: `åa` (with the `a` still underlined)
1. Press `d`
1. Expected: `åd` (or maybe `åad` based on the cursor being after the residual pre-edit text). Actual: `åda` (with the `a` still underlined)
1. Press an arrow key or click the mouse to move the cursor.
1. Expected: Pre-edit text disappears. Actual: Pre-edit text disappears.
1. Include `<Multi_key> <bracketleft> <A> <S> <bracketright> : "🂡"` and `<Multi_key> <slash> <exclam> <backslash> : "⚠"` in `~/.XCompose`
1. Type a >=4 character compose sequence (including `Multi_key`)
1. Expected: `🂡` and `⚠`. Actual: `🂡[AS` and `⚠/!`

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

**Comment by IBBoard** [comment] 2024-01-02 10:45
I've tried adding my own debugging, but a standard `sudo make install` doesn't replace the components (it installs to `/usr/local` but still looks in `/usr`) and manually replacing the executables didn't get the right files either, despite replacing everything that showed up in `ps aux|grep ibus`

**Comment by fujiwarat** [comment] 2024-01-03 05:45
Duplicate of #2585
I have a plan to release 1.5.30 beta1 in this month.

**Closed by fujiwarat** 2024-01-03 05:45 UTC

**Comment by IBBoard** [comment] 2024-01-03 09:14
Ah, okay, thanks 🙂 I didn't find that because it didn't mention the log message. And compose is working, it's just leaving pre-edit text behind. I'll see if I can build a patched version to test out.
