### ISSUE TITLE
UFDD5 with fr(bepo_afnor) keymap does not work for copmose keys

### ISSUE THREAD

**Issue by tobiasBora** [ibus/ibus#2646] opened 2024-05-23 07:38 UTC
Which distribution and version?: 
NixOs unstable b8697e57f10292a6165a20f03d2f42920dfaf973

Which desktop environment and version?: 
Operating System: NixOS 24.05
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.1.80 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8365U CPU @ 1.60GHz
Memory: 15.5 Gio of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

Which session type?: 
X11

Which application and version?: 
Any, say firefox 123.0 or konsole 23.09

IBus version?: 
Ibus 1.5.29

Issue description:
When I switch to the bépo afnor layout (`setxkbmap fr bepo_afnor` or via ibus Win+Space with bepo_afnor configured), and press the key `altGr+j` I get, as expected, an UTF-8 prefix FDD5, that is displayed for instance in firefox via: [![enter image description here][1]][1]. The interest is that I'm then supposed to map it via the `~/.XCompose`, like:
```
include "%L"
<UFDD5> <0> : "⁰"
```
to type `⁰` after pressing `altGr+j 0` (where `0` is from the top row).

This used to work perfectly, but now this is not working anymore (for what I know, I just upgraded my NixOs system).

I also checked in xev, and pressing it does produce the `UFDD5` keysym:
```
KeyPress event, serial 40, synthetic NO, window 0x4200001,
    root 0x60a, subw 0x0, time 779062, (91,97), root:(962,539),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 40, synthetic NO, window 0x4200001,
    root 0x60a, subw 0x0, time 779438, (91,97), root:(962,539),
    state 0x90, keycode 44 (keysym 0x100fdd5, UFDD5), same_screen YES,
    XLookupString gives 3 bytes: (ef b7 95) "﷕"
    XmbLookupString gives 3 bytes: (ef b7 95) "﷕"
    XFilterEvent returns: True

KeyRelease event, serial 40, synthetic NO, window 0x4200001,
    root 0x60a, subw 0x0, time 779758, (91,97), root:(962,539),
    state 0x90, keycode 44 (keysym 0x100fdd5, UFDD5), same_screen YES,
    XLookupString gives 3 bytes: (ef b7 95) "﷕"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x4200001,
    root 0x60a, subw 0x0, time 779787, (91,97), root:(962,539),
    state 0x90, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Note that my .XCompose file is properly recognized, for instance if I put in it:
```
<5> <5>: "⁰"
```
then typing `5 5` (using the numbers in the top row via `shift+0`, not the keypad) after running `ibus restart` it prints as expected `⁰`.

I configured my NixOs via:
```
 services.xserver.xkb.layout = "fr";
  services.xserver.xkb.variant = "oss";
  services.xserver.xkb.options = "compose:menu";
  # XKB's configuration also applies in the console
  console.useXkbConfig = true;

  i18n.inputMethod = {
    enabled = "ibus";
    ibus.engines = with pkgs.ibus-engines; [ table table-others ];
  };
```
  [1]: https://i.sstatic.net/rDYIq9kZ.png

Steps to reproduce:
1. Create the above `.XCompose`
2. Run `ibus restart` 
3. Type `setxkbmap fr bepo_afnor` or via Win+space install the bepo_afnor layout
4. Type `AltGr+j Shift+0` on US/FR layout (corresponding to `AltGr+t` in bépo)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
$ ibus exit ; ibus-daemon --xim --verbose &
(ibus-ui-gtk3:12056): IBUS-WARNING **: 09:41:38.418: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:12056): GLib-CRITICAL **: 09:41:41.791: Source ID 23 was not found when attempting to remove it
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

See also https://gitlab.com/bepo/pilotes/-/issues/30#fn-3-4165 to see how it impacts bépo.

**Comment by fujiwarat** [comment] 2024-05-27 05:28
>     state 0x90, keycode 44 (keysym 0x100fdd5, UFDD5), same_screen YES,

I don't know why your keyboard gives `UFDD5` but I think the keysym of AltGr is `ISO_Level3_Shift`.

Also you should delete the `include` line which is not supported in IBus.

**Comment by wismill** [comment] 2024-05-27 06:02
> I don't know why your keyboard gives `UFDD5`

@fujiwarat this is just a Unicode keysym to create a custom dead key. The codepoint is a [non character](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Noncharacters). This is considered standard practice, as non character (also: [PUA](https://en.wikipedia.org/wiki/Private_Use_Areas)) should not conflict with anything.

This is used by various layouts: Bépo, Neo, …

**Comment by fujiwarat** [comment] 2024-05-27 08:15
I don't ask whether is ta standard way or not but the reproducing steps.
You didn't describe to use the custom keymap which modifies AltGr and you should note the most important issue.

Currently IBus supports a few custom keys and this case is not included to fix #2495
I'm thinking how to resolve the issue.

**Comment by tobiasBora** [comment] 2024-05-27 08:20
> I don't ask whether it is a standard way or not but the reproducing steps.
> You didn't describe to use the custom keymap which modifies AltGr and you should note the most important issue.

Well the reproducing step is to run `setxkbmap fr bepo`, then typing `AltGr + J` (J refering to the key marked as J on any azerty/qwerty keyboard) should produce this symbol FDD5. Then, using the above .XCompose:
```
include "%L"
<UFDD5> <0> : "⁰"
```
I would expect `AltGr + J 0` to produce a ⁰ but this is not the case.

**Comment by wismill** [comment] 2024-05-27 09:00
> I don't ask whether it is a standard way or not but the reproducing steps.

@fujiwarat Fair enough. I expected that IBus has a test suite that makes possible to test compose sequences without actually typing the sequence and would make the origin of the keys a lesser question.

> Currently IBus supports a few custom keys and this case is not included to fix #2495 I'm thinking how to resolve the issue.

Interesting. It seems the fix landed in 1.5.30 while @tobiasBora currently uses 1.5.29.

**Comment by fujiwarat** [comment] 2024-05-27 09:04
> @fujiwarat Fair enough. I expected that IBus has a test suite that makes possible to test compose sequences without actually typing the sequence and would make the origin of the keys a lesser question.

I don't think it's relative with my question.
You should describe your issue exactly.

**Comment by fujiwarat** [comment] 2024-05-27 09:08
Changed the wrong subject.

**Comment by wismill** [comment] 2024-05-27 09:17
> I asked why UFDD5 is produced - it should not happen if you didn't cusomize the keymap.

@fujiwarat this is not a custom keymap: it is the official one, distributed by `xkeyboard-config with [this very keysym](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/c895b24cae5eab27b7ebe45953835da82076c69b/symbols/fr#L581).

I think the real question is: does IBus support (all) Unicode keysyms and what are the limitations, if any.

Why? because layouts are regularly added to `xkeyboard-config` and sometimes require a custom dead key because it is not defined in [`xorg-proto`](https://gitlab.freedesktop.org/xorg/proto/xorgproto) yet.

**Comment by fujiwarat** [comment] 2024-05-27 09:40
> @fujiwarat this is not a custom keymap: it is the official one, distributed by xkeyboard-config with [this very keysym](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/c895b24cae5eab27b7ebe45953835da82076c69b/symbols/fr#L581).

When I configure fr(bepo), AltGr outputs <ISO_Level3_Shift> only AltGr-Shift-0 outputs <ISO_Level3_Shift> and <threequaters> but I don't see UFDD5 and I asked.

**Comment by wismill** [comment] 2024-05-27 09:43
In think it is `fr(bepo_afnor)` and [this comment](https://github.com/ibus/ibus/issues/2646#issuecomment-2132920376) has a typo, because the description is correct. @tobiasBora can you confirm and fix the comment if necessary?

**Comment by fujiwarat** [comment] 2024-05-27 09:49
At the moment, I replaced `<ISO_Level3_Shift>` with `<FDD5>`, `<asterisk>` with `<0>` with xmodmap on fr(bepo) keymaps since the test case is AltGr-0 keys.

**Comment by fujiwarat** [comment] 2024-05-27 10:02
AltGr-j outputs `<thorn>` in my env and i see https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/symbols/fr?ref_type=heads#L455

**Comment by wismill** [comment] 2024-05-27 10:11
Try the _**`bepo_afnor`**_ variant, not the `bepo` one ([see above](https://github.com/ibus/ibus/issues/2646#issuecomment-2133090584)).

**Comment by fujiwarat** [comment] 2024-05-27 10:22
OK, I understand your issue with fr(bepo_afnor) and the description was corrected.

**Comment by tobiasBora** [comment] 2024-05-27 10:25
Yes, sorry for typo in my last comment, just corrected

**Comment by fujiwarat** [comment] 2024-05-27 11:16
@tobiasBora @wismill Thank you for the reports and assistances.

I might notice your typo if I would be a bepo user.
The test case is actually AltGr-t, Shift-asterisk with fr(bepo_afnor).

I made the proposed patch above and I will push it to Fedora for the tests before it will be landed.
It fixes most of the Unicode format but others are case by case.

**Comment by tobiasBora** [comment] 2024-05-27 16:18
Awesome, thanks a lot for the quick fix!

**Closed** 2024-06-26 10:49 UTC
Labels: Priority-Medium, Type-Defect, OpSys-All, ibus, compose
