### ISSUE TITLE
ibus dumpped core and stopped working in wezterm

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [ibus/ibus#2494] opened 2023-03-26 05:20 UTC
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
ArchLinux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Plasma 5.27

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
wezterm 20230322-072402-b384dc99

IBus version?: 
(Run `ibus version`)
IBus 1.5.28

Issue description:
IBus just stops working.

`journalctl -b -u ibus` shows the dumped core.

```
Mar 22 18:42:59 omelet-hp-pavilion systemd[1100]: Started Intelligent Input Bus.
Mar 23 00:48:35 omelet-hp-pavilion systemd-coredump[195437]: Process 1181 (ibus-x11) of user 1000 dumped core.
                                                             
                                                             Stack trace of thread 1181:
                                                             #0  0x00007f43fc6b88ec n/a (libc.so.6 + 0x878ec)
                                                             #1  0x00007f43fc669ea8 raise (libc.so.6 + 0x38ea8)
                                                             #2  0x00007f43fc65353d abort (libc.so.6 + 0x2253d)
                                                             #3  0x00007f43fc65429e n/a (libc.so.6 + 0x2329e)
                                                             #4  0x00007f43fc6c2657 n/a (libc.so.6 + 0x91657)
                                                             #5  0x00007f43fc6c4442 n/a (libc.so.6 + 0x93442)
                                                             #6  0x00007f43fc6c6e63 __libc_free (libc.so.6 + 0x95e63)
                                                             #7  0x00007f43fc85a94e XFree (libX11.so.6 + 0x4294e)
                                                             #8  0x000055a9e0aca311 n/a (ibus-x11 + 0xe311)
                                                             #9  0x000055a9e0acc19a n/a (ibus-x11 + 0x1019a)
                                                             #10 0x00007f43fcb9259e n/a (libgdk-3.so.0 + 0x8b59e)
                                                             #11 0x00007f43fcb38029 gdk_display_get_event (libgdk-3.so.0 + 0x31029)
                                                             #12 0x00007f43fcb92a68 n/a (libgdk-3.so.0 + 0x8ba68)
                                                             #13 0x00007f43fc9b5afb g_main_context_dispatch (libglib-2.0.so.0 + 0x5aafb)
                                                             #14 0x00007f43fca125d9 n/a (libglib-2.0.so.0 + 0xb75d9)
                                                             #15 0x00007f43fc9b50cf g_main_loop_run (libglib-2.0.so.0 + 0x5a0cf)
                                                             #16 0x00007f43fd4432b2 ibus_main (libibus-1.0.so.5 + 0x372b2)
                                                             #17 0x000055a9e0abf505 n/a (ibus-x11 + 0x3505)
                                                             #18 0x00007f43fc654790 n/a (libc.so.6 + 0x23790)
                                                             #19 0x00007f43fc65484a __libc_start_main (libc.so.6 + 0x2384a)
                                                             #20 0x000055a9e0abf6f5 n/a (ibus-x11 + 0x36f5)
                                                             
                                                             Stack trace of thread 1217:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1219:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1222:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1223:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1226:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1220:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1227:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1281:
                                                             #0  0x00007f43fc7310dd syscall (libc.so.6 + 0x1000dd)
                                                             #1  0x00007f43fca06a35 g_cond_wait (libglib-2.0.so.0 + 0xaba35)
                                                             #2  0x00007f43fc97ffc4 n/a (libglib-2.0.so.0 + 0x24fc4)
                                                             #3  0x00007f43fc9e543e n/a (libglib-2.0.so.0 + 0x8a43e)
                                                             #4  0x00007f43fc9e37c5 n/a (libglib-2.0.so.0 + 0x887c5)
                                                             #5  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #6  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1224:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1260:
                                                             #0  0x00007f43fc72b9df __poll (libc.so.6 + 0xfa9df)
                                                             #1  0x00007f43fca1253f n/a (libglib-2.0.so.0 + 0xb753f)
                                                             #2  0x00007f43fc9b3382 g_main_context_iteration (libglib-2.0.so.0 + 0x58382)
                                                             #3  0x00007f43fc9b33d2 n/a (libglib-2.0.so.0 + 0x583d2)
                                                             #4  0x00007f43fc9e37c5 n/a (libglib-2.0.so.0 + 0x887c5)
                                                             #5  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #6  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1284:
                                                             #0  0x00007f43fc72b9df __poll (libc.so.6 + 0xfa9df)
                                                             #1  0x00007f43fca1253f n/a (libglib-2.0.so.0 + 0xb753f)
                                                             #2  0x00007f43fc9b50cf g_main_loop_run (libglib-2.0.so.0 + 0x5a0cf)
                                                             #3  0x00007f43fc56be4c n/a (libgio-2.0.so.0 + 0x10fe4c)
                                                             #4  0x00007f43fc9e37c5 n/a (libglib-2.0.so.0 + 0x887c5)
                                                             #5  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #6  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1225:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1218:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1221:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1229:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             
                                                             Stack trace of thread 1228:
                                                             #0  0x00007f43fc6b3766 n/a (libc.so.6 + 0x82766)
                                                             #1  0x00007f43fc6b5f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                                                             #2  0x00007f43f68c257c n/a (iris_dri.so + 0xc257c)
                                                             #3  0x00007f43f690bcec n/a (iris_dri.so + 0x10bcec)
                                                             #4  0x00007f43fc6b6bb5 n/a (libc.so.6 + 0x85bb5)
                                                             #5  0x00007f43fc738d90 n/a (libc.so.6 + 0x107d90)
                                                             ELF object binary architecture: AMD x86-64
```

Steps to reproduce:
I don't know how to reproduce it stably.
Sometimes when I typing in vim in terminal (wezterm) it'll stop working suddenly.
I can still type but it's not doing word compositing.

In some other applications it seems that it'll trigger ibus restart so I won't notice that ibus was dead.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Not sure.
Ibus will be usable just after the restart, but it can still stop working.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
See https://gist.github.com/OmeletWithoutEgg/3ad833d5ac8e4c9d4a69e35148b4aa89
There's some error message saying that "The error was 'BadWindow (invalid Window parameter)'."

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Not sure

**Comment by fujiwarat** [comment] 2023-03-27 10:00
Duplicate of #2484

**Closed by fujiwarat** 2023-03-27 10:00 UTC
